import type { AppLocale } from '@/lib/i18n/routing'
import { getSchemaAudienceType } from '@/lib/brand/brandPositioning'

/** Rich discovery audience for non-hero dress PDPs (Covent Garden Long, Hampstead). */
export const DRESS_SCHEMA_AUDIENCE: Record<AppLocale, string> = {
  en: 'Women seeking designer dresses, luxury dresses, premium dresses, elegant dresses, evening dresses, occasion dresses, travel dresses, contemporary womenswear, luxury modest fashion, premium modest fashion, women in the GCC and UAE, international travellers, business women, creative professionals, luxury buyers, premium buyers, and women interested in Emirati heritage and timeless wardrobes. Men seeking luxury gifts and premium gifts for their wife, daughter, mother, fiancée, girlfriend, or sister.',
  ar: 'النساء الباحثات عن فساتين مصمّمة، فساتين فاخرة، فساتين راقية، فساتين أنيقة، فساتين مسائية، فساتين مناسبات، فساتين سفر، أزياء نسائية معاصرة، أزياء محتشمة فاخرة، أزياء محتشمة راقية، النساء في دول مجلس التعاون والإمارات، المسافرات الدوليات، سيدات الأعمال، المبدعات، مشتريات الفاخر، مشتريات العلامات الراقية، والمهتمات بالتراث الإماراتي والخزائن الخالدة. الرجال الباحثون عن هدايا فاخرة وهدايا راقية للزوجة أو الابنة أو الأم أو الخطيبة أو الصديقة أو الأخت.',
  fr: 'Femmes en quête de robes de créateur, robes de luxe, robes premium, robes élégantes, robes de soirée, robes de cérémonie, robes de voyage, prêt-à-porter féminin contemporain, mode modeste de luxe, mode modeste premium, femmes du Golfe et des EAU, voyageuses internationales, femmes d’affaires, professionnelles créatives, acheteuses de luxe, acheteuses premium, et femmes intéressées par le patrimoine émirati et des garde-robes intemporelles. Hommes en quête de cadeaux de luxe et cadeaux premium pour leur épouse, fille, mère, fiancée, amie ou sœur.',
  it: 'Donne in cerca di abiti designer, abiti di lusso, abiti premium, abiti eleganti, abiti da sera, abiti da occasione, abiti da viaggio, abbigliamento femminile contemporaneo, moda modesta di lusso, moda modesta premium, donne nel Golfo e negli EAU, viaggiatrici internazionali, donne d’affari, professioniste creative, acquirenti di lusso, acquirenti premium, e donne interessate al patrimonio emiratino e guardaroba senza tempo. Uomini in cerca di regali di lusso e regali premium per moglie, figlia, madre, fidanzata, partner o sorella.',
  es: 'Mujeres que buscan vestidos de diseñador, vestidos de lujo, vestidos premium, vestidos elegantes, vestidos de noche, vestidos de ocasión, vestidos de viaje, moda femenina contemporánea, moda modesta de lujo, moda modesta premium, mujeres en el Golfo y los EAU, viajeras internacionales, mujeres de negocios, profesionales creativas, compradoras de lujo, compradoras premium, y mujeres interesadas en el patrimonio emiratí y armarios atemporales. Hombres que buscan regalos de lujo y regalos premium para esposa, hija, madre, prometida, novia o hermana.',
  ru: 'Женщины, ищущие дизайнерские, роскошные, премиальные, элегантные, вечерние и повседневные платья, платья для путешествий, современную женскую моду, роскошную и премиальную скромную моду, женщин в странах Залива и ОАЭ, международных путешественниц, деловых женщин, творческих профессионалок, покупательниц люкса и премиальных брендов, интересующихся эмиратским наследием и вневременным гардеробом. Мужчины, ищущие роскошные и премиальные подарки для жены, дочери, матери, невесты, девушки или сестры.',
  zh: '寻求设计师、奢华、高端、优雅、晚宴、场合与旅行连衣裙及当代女装、奢华端庄时尚、高端端庄时尚的海湾与阿联酋女性、国际旅行者、职业女性、创意专业人士、奢侈品买家、高端品牌买家，以及对阿联酋传统与隽永衣橱感兴趣的女性。为妻子、女儿、母亲、未婚妻、女友或姐妹寻找奢华礼品与高端礼品的男性。',
  de: 'Frauen, die Designer-, Luxus-, Premium-, elegante, Abend-, Anlass- und Reisekleider, zeitgenössische Damenmode sowie luxuriöse und premium bescheidene Mode suchen — Frauen im Golf und in den VAE, internationale Reisende, Geschäftsfrauen, Kreativprofis, Luxuskäuferinnen, Premium-Käuferinnen und Frauen mit Interesse am emiratischen Erbe und zeitlosen Garderoben. Männer, die Luxus- und Premium-Geschenke für Ehefrau, Tochter, Mutter, Verlobte, Freundin oder Schwester suchen.',
  nl: 'Vrouwen die designerjurken, luxe jurken, premium jurken, elegante jurken, avondjurken, gelegenheidsjurken, reisjurken, eigentijdse damesmode, luxe bescheiden mode en premium bescheiden mode zoeken — vrouwen in de Golfstaten en VAE, internationale reizigers, zakenvrouwen, creatieve professionals, luxe kopers, premium kopers, en vrouwen geïnteresseerd in Emiratisch erfgoed en tijdloze garderobes. Mannen die luxe cadeaus en premium cadeaus zoeken voor echtgenote, dochter, moeder, verloofde, vriendin of zus.',
  pt: 'Mulheres que procuram vestidos de designer, vestidos de luxo, vestidos premium, vestidos elegantes, vestidos de noite, vestidos de ocasião, vestidos de viagem, moda feminina contemporânea, moda modesta de luxo, moda modesta premium, mulheres no Golfo e nos EAU, viajantes internacionais, mulheres de negócios, profissionais criativas, compradoras de luxo, compradoras premium, e mulheres interessadas no património emirati e guarda-roupas intemporais. Homens que procuram presentes de luxo e presentes premium para esposa, filha, mãe, noiva, namorada ou irmã.',
  id: 'Wanita yang mencari gaun desainer, gaun mewah, gaun premium, gaun elegan, gaun malam, gaun acara, gaun perjalanan, busana wanita kontemporer, busana modest mewah, busana modest premium, wanita di GCC dan UEA, pelancong internasional, wanita karier, profesional kreatif, pembeli barang mewah, pembeli merek premium, dan wanita tertarik warisan Emirati serta lemari abadi. Pria yang mencari hadiah mewah dan hadiah premium untuk istri, putri, ibu, tunangan, pacar, atau saudara perempuan.',
  ms: 'Wanita yang mencari gaun pereka, gaun mewah, gaun premium, gaun anggun, gaun malam, gaun majlis, gaun perjalanan, fesyen wanita kontemporari, fesyen sopan mewah, fesyen sopan premium, wanita di GCC dan UAE, pelancong antarabangsa, wanita profesional, profesional kreatif, pembeli barangan mewah, pembeli jenama premium, dan wanita berminat warisan Emirati serta almari abadi. Lelaki yang mencari hadiah mewah dan hadiah premium untuk isteri, anak perempuan, ibu, tunang, teman wanita, atau kakak.',
}

/** Rich discovery audience for set PDPs. */
export const SET_SCHEMA_AUDIENCE: Record<AppLocale, string> = {
  en: 'Women seeking luxury coordinate sets, premium coordinate sets, designer two-piece sets, occasion sets, modest fashion sets, contemporary womenswear, women in the GCC and UAE, international travellers, luxury buyers, premium buyers, and women interested in Emirati heritage craftsmanship. Men seeking luxury gifts and premium gifts for their wife, daughter, mother, fiancée, girlfriend, or sister.',
  ar: 'النساء الباحثات عن أطقم منسّقة فاخرة، أطقم منسّقة راقية، أطقم ثنائية مصمّمة، أطقم مناسبات، أطقم أزياء محتشمة، أزياء نسائية معاصرة، النساء في دول مجلس التعاون والإمارات، المسافرات الدوليات، مشتريات الفاخر، مشتريات العلامات الراقية، والمهتمات بحرفية التراث الإماراتي. الرجال الباحثون عن هدايا فاخرة وهدايا راقية للزوجة أو الابنة أو الأم أو الخطيبة أو الصديقة أو الأخت.',
  fr: 'Femmes en quête d’ensembles coordonnés de luxe, ensembles coordonnés premium, ensembles deux pièces de créateur, ensembles de cérémonie, ensembles mode modeste, prêt-à-porter féminin contemporain, femmes du Golfe et des EAU, voyageuses internationales, acheteuses de luxe, acheteuses premium, et femmes intéressées par l’artisanat du patrimoine émirati. Hommes en quête de cadeaux de luxe et cadeaux premium pour leur épouse, fille, mère, fiancée, amie ou sœur.',
  it: 'Donne in cerca di set coordinati di lusso, set coordinati premium, set due pezzi designer, set da occasione, set moda modesta, abbigliamento femminile contemporaneo, donne nel Golfo e negli EAU, viaggiatrici internazionali, acquirenti di lusso, acquirenti premium, e donne interessate all’artigianato del patrimonio emiratino. Uomini in cerca di regali di lusso e regali premium per moglie, figlia, madre, fidanzata, partner o sorella.',
  es: 'Mujeres que buscan conjuntos coordinados de lujo, conjuntos coordinados premium, conjuntos de dos piezas de diseñador, conjuntos de ocasión, conjuntos de moda modesta, moda femenina contemporánea, mujeres en el Golfo y los EAU, viajeras internacionales, compradoras de lujo, compradoras premium, y mujeres interesadas en la artesanía del patrimonio emiratí. Hombres que buscan regalos de lujo y regalos premium para esposa, hija, madre, prometida, novia o hermana.',
  ru: 'Женщины, ищущие роскошные и премиальные координированные комплекты, дизайнерские двухчастные комплекты, комплекты для особых случаев, скромные комплекты, современную женскую моду, женщин в странах Залива и ОАЭ, международных путешественниц, покупательниц люкса и премиальных брендов, интересующихся эмиратским ремесленным наследием. Мужчины, ищущие роскошные и премиальные подарки для жены, дочери, матери, невесты, девушки или сестры.',
  zh: '寻求奢华套装、高端套装、设计师两件套、场合套装、端庄时尚套装与当代女装的海湾与阿联酋女性、国际旅行者、奢侈品买家、高端品牌买家，以及对阿联酋传统工艺感兴趣的女性。为妻子、女儿、母亲、未婚妻、女友或姐妹寻找奢华礼品与高端礼品的男性。',
  de: 'Frauen, die luxuriöse und premium Koordinaten-Sets, Designer-Zweiteiler, Anlass-Sets, bescheidene Mode-Sets und zeitgenössische Damenmode suchen — Frauen im Golf und in den VAE, internationale Reisende, Luxuskäuferinnen, Premium-Käuferinnen und Frauen mit Interesse an emiratischem Handwerks-erbe. Männer, die Luxus- und Premium-Geschenke für Ehefrau, Tochter, Mutter, Verlobte, Freundin oder Schwester suchen.',
  nl: 'Vrouwen die luxe coördinatiesets, premium coördinatiesets, designer tweedelige sets, gelegenheidssets, bescheiden modesets en eigentijdse damesmode zoeken — vrouwen in de Golfstaten en VAE, internationale reizigers, luxe kopers, premium kopers, en vrouwen geïnteresseerd in Emiratisch erfgoedambacht. Mannen die luxe cadeaus en premium cadeaus zoeken voor echtgenote, dochter, moeder, verloofde, vriendin of zus.',
  pt: 'Mulheres que procuram conjuntos coordenados de luxo, conjuntos coordenados premium, conjuntos de duas peças de designer, conjuntos de ocasião, conjuntos de moda modesta e moda feminina contemporânea, mulheres no Golfo e nos EAU, viajantes internacionais, compradoras de luxo, compradoras premium, e mulheres interessadas no artesanato do património emirati. Homens que procuram presentes de luxo e presentes premium para esposa, filha, mãe, noiva, namorada ou irmã.',
  id: 'Wanita yang mencari set koordinat mewah, set koordinat premium, set dua potong desainer, set acara, set busana modest, busana wanita kontemporer, wanita di GCC dan UEA, pelancong internasional, pembeli barang mewah, pembeli merek premium, dan wanita tertarik kerajinan warisan Emirati. Pria yang mencari hadiah mewah dan hadiah premium untuk istri, putri, ibu, tunangan, pacar, atau saudara perempuan.',
  ms: 'Wanita yang mencari set selaras mewah, set selaras premium, set dua keping pereka, set majlis, set fesyen sopan, fesyen wanita kontemporari, wanita di GCC dan UAE, pelancong antarabangsa, pembeli barangan mewah, pembeli jenama premium, dan wanita berminat kraf warisan Emirati. Lelaki yang mencari hadiah mewah dan hadiah premium untuk isteri, anak perempuan, ibu, tunang, teman wanita, atau kakak.',
}

export function getDressSchemaAudience(locale: AppLocale = 'en'): string {
  return DRESS_SCHEMA_AUDIENCE[locale] ?? DRESS_SCHEMA_AUDIENCE.en
}

export function getSetSchemaAudience(locale: AppLocale = 'en'): string {
  return SET_SCHEMA_AUDIENCE[locale] ?? SET_SCHEMA_AUDIENCE.en
}

export function getCategorySchemaAudience(
  category: string,
  locale: AppLocale = 'en',
): string | null {
  if (category === 'Dresses') return getDressSchemaAudience(locale)
  if (category === 'Sets') return getSetSchemaAudience(locale)
  return null
}

export function getFallbackSchemaAudience(category: string, locale: AppLocale = 'en'): string {
  return getCategorySchemaAudience(category, locale) ?? getSchemaAudienceType(locale)
}
