import type { AppLocale } from '@/lib/i18n/routing'
import {
  getLocalizedCoventGardenSignatureSetExclusiveKeywords,
} from '@/lib/products/coventGardenSignatureSetSchemaKeywordsI18n'
import {
  getLocalizedCoventGardenSignatureSetFaq,
  getLocalizedCoventGardenSignatureSetSchemaFacts,
  COVENT_GARDEN_SIGNATURE_SET_SLUG,
} from '@/lib/products/coventGardenSignatureSetSchemaLocalePacks'

export { COVENT_GARDEN_SIGNATURE_SET_SLUG } from '@/lib/products/coventGardenSignatureSetSchemaLocalePacks'

/** Schema `audienceType` — premium contemporary set discovery. */
export const COVENT_GARDEN_SIGNATURE_SET_SCHEMA_AUDIENCE: Record<AppLocale, string> = {
  en: 'Women seeking contemporary premium womenswear, designer two-piece sets, premium dress and jacket sets, coordinated sets, modest fashion, premium modest fashion, contemporary tailoring, elegant workwear, formal daywear, refined everyday dressing, business meeting outfits, afternoon tea outfits, dinner outfits, gallery opening outfits, cultural event outfits, women in the GCC, women in the UAE, Emirati women, Saudi women, Qatari women, Kuwaiti women, European women, British women, American women, Canadian women, Asian women, expatriates in the GCC, international clients, business women, entrepreneurs, executives, creative professionals, premium fashion buyers, contemporary fashion buyers, abaya buyers seeking coordinated looks, and women interested in Emirati heritage expressed through contemporary fashion. Men seeking meaningful premium gifts for their wife, daughter, mother, fiancée, girlfriend, or sister.',
  ar: 'النساء الباحثات عن أطقم منسّقة فاخرة، أطقم منسّقة راقية، أطقم ثنائية مصمّمة، أطقم فستان وجاكيت، أطقم للعمل، أطقم مناسبات، أطقم أزياء محتشمة، أزياء نسائية معاصرة، أزياء أوروبية، أزياء شرق أوسطية، أزياء محتشمة فاخرة، أزياء محتشمة راقية، أزياء محتشمة مصمّمة، النساء في دول مجلس التعاون الخليجي، النساء في الإمارات، المرأة الإماراتية، السعودية، القطرية، الكويتية، الأوروبية، الأمريكية، الكندية، الآسيوية، المسافرات الدوليات، سيدات الأعمال، المبدعات، مشتريات الفاخر، مشتريات الأزياء المعاصرة، المهتمات بالتراث الإماراتي ونسيج الخوص، والباحثات عن خزائن خالدة وتنسيق منسّق. الرجال الباحثون عن هدايا فاخرة وهدايا راقية للزوجة أو الابنة أو الأم أو الخطيبة أو الصديقة أو الأخت.',
  fr: 'Femmes en quête d’ensembles coordonnés de luxe, ensembles coordonnés premium, ensembles deux pièces de créateur, ensembles robe et veste, ensembles pour le travail, ensembles de cérémonie, ensembles mode modeste, prêt-à-porter féminin contemporain, mode européenne, mode du Moyen-Orient, mode modeste de luxe, mode modeste premium, mode modeste de créateur, femmes du Golfe, femmes des Émirats, femmes émiraties, saoudiennes, qatariennes, koweïtiennes, européennes, américaines, canadiennes, asiatiques, voyageuses internationales, femmes d’affaires, professionnelles créatives, acheteuses de luxe, acheteuses premium, acheteuses de mode contemporaine, femmes intéressées par le patrimoine émirati et le tissage Al Khous, et femmes recherchant des garde-robes intemporelles et un dressing coordonné. Hommes en quête de cadeaux de luxe et cadeaux premium pour leur épouse, fille, mère, fiancée, amie ou sœur.',
  it: 'Donne in cerca di set coordinati di lusso, set coordinati premium, set due pezzi di designer, set abito e giacca, set da lavoro, set da occasione, set moda modesta, abbigliamento femminile contemporaneo, moda europea, moda mediorientale, moda modesta di lusso, moda modesta premium, moda modesta designer, donne nel Golfo, donne negli EAU, donne emiratine, saudite, qatariote, kuwaitiane, europee, americane, canadesi, asiatiche, viaggiatrici internazionali, donne d’affari, professioniste creative, acquirenti di lusso, acquirenti premium, acquirenti di moda contemporanea, donne interessate al patrimonio emiratino e alla tessitura Al Khous, e donne che cercano guardaroba senza tempo e abbigliamento coordinato. Uomini in cerca di regali di lusso e regali premium per moglie, figlia, madre, fidanzata, partner o sorella.',
  es: 'Mujeres que buscan conjuntos coordinados de lujo, conjuntos coordinados premium, conjuntos de dos piezas de diseñador, conjuntos de vestido y chaqueta, conjuntos para el trabajo, conjuntos de ocasión, conjuntos de moda modesta, moda femenina contemporánea, moda europea, moda de Oriente Medio, moda modesta de lujo, moda modesta premium, moda modesta de diseñador, mujeres en el Golfo, mujeres en los EAU, mujeres emiratíes, saudíes, qataríes, kuwaitíes, europeas, estadounidenses, canadienses, asiáticas, viajeras internacionales, mujeres de negocios, profesionales creativas, compradoras de lujo, compradoras premium, compradoras de moda contemporánea, mujeres interesadas en el patrimonio emiratí y el tejido Al Khous, y mujeres que buscan armarios atemporales y vestir coordinado. Hombres que buscan regalos de lujo y regalos premium para esposa, hija, madre, prometida, novia o hermana.',
  ru: 'Женщины, ищущие роскошные и премиальные координированные комплекты, дизайнерские двухчастные комплекты, комплекты платье и жакет, комплекты для работы, комплекты для особых случаев, скромные комплекты, современную женскую моду, европейскую моду, ближневосточную моду, роскошную и премиальную скромную моду, дизайнерскую скромную моду, женщин в странах Залива и ОАЭ, эмираток, саудовок, катарок, кувейтянок, европеек, американок, канадок, азиаток, международных путешественниц, деловых женщин, творческих профессионалок, покупательниц люкса и премиальных брендов, женщин, интересующихся эмиратским наследием и плетением Al Khous, и женщин, ищущих вневременной гардероб и согласованный стиль. Мужчины, ищущие роскошные и премиальные подарки для жены, дочери, матери, невесты, девушки или сестры.',
  zh: '寻求奢华套装、高端套装、设计师两件套、连衣裙夹克套装、职场套装、场合套装、端庄时尚套装、当代女装、欧洲时尚、中东时尚、奢华端庄时尚、高端端庄时尚、设计师端庄时尚的海湾与阿联酋女性、国际旅行者、职业女性、创意专业人士、奢侈品买家、高端品牌买家、对阿联酋传统与 Al Khous 编织感兴趣的女性，以及追求隽永衣橱与协调着装的女性。为妻子、女儿、母亲、未婚妻、女友或姐妹寻找奢华礼品与高端礼品的男性。',
  de: 'Frauen, die luxuriöse und premium Koordinaten-Sets, Designer-Zweiteiler, Kleid-und-Jacke-Sets, Business-Sets, Anlass-Sets, bescheidene Mode-Sets und zeitgenössische Damenmode suchen — Frauen im Golf und in den VAE, emiratischen, saudischen, katarischen, kuwaitischen, europäischen, amerikanischen, kanadischen und asiatischen Frauen, internationalen Reisenden, Geschäftsfrauen, Kreativprofis, Luxuskäuferinnen, Premium-Käuferinnen, zeitgenössischen Modekäuferinnen, Frauen mit Interesse am emiratischen Erbe und Al-Khous-Weben, und Frauen, die zeitlose Garderoben und koordiniertes Styling suchen. Männer, die Luxus- und Premium-Geschenke für Ehefrau, Tochter, Mutter, Verlobte, Freundin oder Schwester suchen.',
  nl: 'Vrouwen die luxe coördinatiesets, premium coördinatiesets, designer tweedelige sets, jurk-en-jas-sets, werksets, gelegenheidssets, bescheiden modesets en eigentijdse damesmode zoeken — vrouwen in de Golfstaten en VAE, Emiratische, Saoedische, Qatarese, Koeweitse, Europese, Amerikaanse, Canadese en Aziatische vrouwen, internationale reizigers, zakenvrouwen, creatieve professionals, luxe kopers, premium kopers, eigentijdse modekopers, vrouwen geïnteresseerd in Emiratisch erfgoed en Al Khous-weven, en vrouwen die tijdloze garderobes en gecoördineerde stijl zoeken. Mannen die luxe cadeaus en premium cadeaus zoeken voor echtgenote, dochter, moeder, verloofde, vriendin of zus.',
  pt: 'Mulheres que procuram conjuntos coordenados de luxo, conjuntos coordenados premium, conjuntos de duas peças de designer, conjuntos vestido e casaco, conjuntos para trabalho, conjuntos de ocasião, conjuntos de moda modesta e moda feminina contemporânea, mulheres no Golfo e nos EAU, mulheres emiratis, sauditas, qatarenses, kuwaitianas, europeias, americanas, canadianas, asiáticas, viajantes internacionais, mulheres de negócios, profissionais criativas, compradoras de luxo, compradoras premium, compradoras de moda contemporânea, mulheres interessadas no património emirati e na tecelagem Al Khous, e mulheres que procuram guarda-roupas intemporais e vestir coordenado. Homens que procuram presentes de luxo e presentes premium para esposa, filha, mãe, noiva, namorada ou irmã.',
  id: 'Wanita yang mencari set koordinat mewah, set koordinat premium, set dua potong desainer, set gaun dan jaket, set kerja, set acara, set busana modest, busana wanita kontemporer, fashion Eropa, fashion Timur Tengah, busana modest mewah, busana modest premium, busana modest desainer, wanita di GCC dan UEA, wanita Emirati, Saudi, Qatar, Kuwait, Eropa, Amerika, Kanada, Asia, pelancong internasional, wanita karier, profesional kreatif, pembeli barang mewah, pembeli fashion kontemporer, wanita tertarik warisan Emirati dan tenun Al Khous, serta wanita yang mencari lemari abadi dan gaya terkoordinasi. Pria yang mencari hadiah mewah dan hadiah premium untuk istri, putri, ibu, tunangan, pacar, atau saudara perempuan.',
  ms: 'Wanita yang mencari set selaras mewah, set selaras premium, set dua keping pereka, set gaun dan jaket, set kerja, set majlis, set fesyen sopan, fesyen wanita kontemporari, fesyen Eropah, fesyen Timur Tengah, fesyen sopan mewah, fesyen sopan premium, fesyen sopan pereka, wanita di GCC dan UAE, wanita Emirati, Saudi, Qatar, Kuwait, Eropah, Amerika, Kanada, Asia, pelancong antarabangsa, wanita profesional, profesional kreatif, pembeli barangan mewah, pembeli fesyen kontemporari, wanita berminat warisan Emirati dan tenunan Al Khous, serta wanita yang mencari almari abadi dan gaya selaras. Lelaki yang mencari hadiah mewah dan hadiah premium untuk isteri, anak perempuan, ibu, tunang, teman wanita, atau kakak.',
}

export function isCoventGardenSignatureSetSlug(slug: string): boolean {
  return slug.toLowerCase() === COVENT_GARDEN_SIGNATURE_SET_SLUG
}

export function getCoventGardenSignatureSetSchemaAudience(locale: AppLocale = 'en'): string {
  return COVENT_GARDEN_SIGNATURE_SET_SCHEMA_AUDIENCE[locale] ?? COVENT_GARDEN_SIGNATURE_SET_SCHEMA_AUDIENCE.en
}

export function getCoventGardenSignatureSetSchemaKeywords(
  locale: AppLocale = 'en',
  colorName?: string,
): string {
  return getLocalizedCoventGardenSignatureSetExclusiveKeywords(locale, colorName).join(', ')
}

export {
  getLocalizedCoventGardenSignatureSetSchemaFacts,
  getLocalizedCoventGardenSignatureSetFaq,
} from '@/lib/products/coventGardenSignatureSetSchemaLocalePacks'

export type { ProductFaqItem, ProductSchemaFacts } from '@/lib/products/productSchemaMeta'
