import type { AppLocale } from '@/lib/i18n/routing'

/**
 * Global PDP schema audience extension — appended to every catalogue PDP `audienceType`.
 * Occasion and client-segment framing only; no royal endorsement or named-individual claims.
 */
const GLOBAL_PDP_SCHEMA_AUDIENCE_EXTENSION: Record<AppLocale, string> = {
  en: ', embassy staff and diplomats, women working with Arab clients, Gulf partners, and government relations teams, international affairs and protocol professionals, hospitality and concierge teams guiding guests on modest and formal occasionwear, women selecting pieces for embassy receptions, official visits, state dinners, and cultural engagements, advisors helping international visitors dress appropriately for Gulf and Emirati occasions, royal family members travelling abroad, royal household members and sheikhas abroad, princesses and queens travelling internationally, VIP guests and private clientele, ultra-high-net-worth individuals, high-net-worth family members, family office personal shoppers, luxury concierge buyers, women attending diplomatic galas, royal courts abroad, private members clubs, and exclusive international events',

  ar: ', موظفو السفارات والدبلوماسيون، النساء العاملات مع عملاء عرب وشركاء خليجيين وفرق العلاقات الحكومية، متخصصات الشؤون الدولية والبروتوكول، فرق الضيافة والكونسيرج التي ترشد الضيوف لاختيار ملابس المناسبات المحتشمة والرسمية، النساء اللواتي يختارن قطعاً لاستقبالات السفارات والزيارات الرسمية وعشاءات الدولة والفعاليات الثقافية، المستشارون الذين يساعدون الزوار الدوليين على اختيار ملابس مناسبة للمناسبات الخليجية والإماراتية، أفراد العائلات المالكة المسافرون إلى الخارج، أفراد البيوت الملكية والشيخات في الخارج، الأميرات والملكات المسافرات دولياً، ضيوف كبار الشخصيات والعملاء الخاصون، أصحاب الثروات الفائقة، أفراد العائلات ذات الثروات العالية، مشترون شخصيون لمكاتب العائلات، مشتريات الكونسيرج الفاخر، النساء الحاضرات لحفلات دبلوماسية وقصور ملكية في الخارج ونوادي الأعضاء الخاصة وفعاليات دولية حصرية',

  fr: ", personnel d'ambassade et diplomates, femmes travaillant avec des clients arabes, partenaires du Golfe et équipes relations gouvernementales, professionnelles des affaires internationales et du protocole, équipes hôtelières et conciergerie guidant les invitées sur la tenue modeste et de cérémonie, femmes choisissant des pièces pour réceptions d'ambassade, visites officielles, dîners d'État et engagements culturels, conseillères aidant les visiteuses internationales à s'habiller pour les occasions du Golfe et émiraties, membres de familles royales voyageant à l'étranger, membres de maisons royales et sheikhas à l'international, princesses et reines en voyage, invitées VIP et clientèle privée, ultra-high-net-worth, membres de familles fortunées, personal shoppers de family offices, acheteuses conciergerie de luxe, femmes assistant à galas diplomatiques, cours royales à l'étranger, clubs privés et événements internationaux exclusifs",

  it: ', personale di ambasciate e diplomatici, donne che lavorano con clienti arabi, partner del Golfo e team di relazioni governative, professioniste di affari internazionali e protocollo, team hospitality e concierge che guidano le ospiti nella scelta di abbigliamento modesto e da cerimonia, donne che scelgono capi per ricevimenti in ambasciata, visite ufficiali, cene di Stato e impegni culturali, consulenti che aiutano visitatrici internazionali a vestirsi per occasioni del Golfo ed emiratine, membri di famiglie reali in viaggio all estero, membri di case reali e sheikha all estero, principesse e regine in viaggio internazionale, ospiti VIP e clientela privata, ultra-high-net-worth, membri di famiglie ad alto patrimonio, personal shopper di family office, acquirenti concierge di lusso, donne a gala diplomatiche, corti reali all estero, club privati ed eventi internazionali esclusivi',

  es: ', personal de embajadas y diplomáticos, mujeres que trabajan con clientes árabes, socios del Golfo y equipos de relaciones gubernamentales, profesionales de asuntos internacionales y protocolo, equipos de hospitalidad y conserjería que orientan a invitadas sobre moda modesta y de ceremonia, mujeres que eligen piezas para recepciones en embajada, visitas oficiales, cenas de Estado y compromisos culturales, asesoras que ayudan a visitantes internacionales a vestirse para ocasiones del Golfo y emiratíes, miembros de familias reales que viajan al extranjero, miembros de casas reales y sheikhas en el exterior, princesas y reinas en viajes internacionales, invitadas VIP y clientela privada, ultra-high-net-worth, miembros de familias de alto patrimonio, personal shoppers de family offices, compradoras de conserjería de lujo, mujeres en galas diplomáticas, cortes reales en el extranjero, clubes privados y eventos internacionales exclusivos',

  ru: ', сотрудники посольств и дипломаты, женщины, работающие с арабскими клиентами, партнёрами из стран Залива и правительственными командами, специалистки по международным делам и протоколу, команды гостеприимства и консьерж-сервиса, помогающие гостьям выбрать скромную и торжественную одежду, женщины, выбирающие вещи для приёмов в посольствах, официальных визитов, государственных ужинов и культурных мероприятий, консультантки, помогающие международным гостьям одеваться для случаев в странах Залива и ОАЭ, члены королевских семей, путешествующие за рубеж, члены королевских домов и шейхи за границей, принцессы и королевы в международных поездках, VIP-гости и частные клиентки, состоятельнейшие лица, члены семей с высоким капиталом, персональные шопперы family office, покупательницы luxury concierge, женщины на дипломатических гала, при дворах за рубежом, в частных клубах и на эксклюзивных международных мероприятиях',

  zh: '，使馆工作人员与外交官，与阿拉伯客户、海湾合作伙伴及政府关系团队共事的女性，国际事务与礼宾专业人士，为宾客提供端庄与正式场合着装指引的酒店与礼宾团队，为使馆招待会、官方访问、国宴及文化活动选购服饰的女性，帮助国际访客为海湾与阿联酋场合恰当着装的顾问，出国旅行的王室家族成员、王室成员与海外谢赫夫人，国际出行的公主与女王，VIP宾客与私人客户，超高净值人士，高净值家族成员，家族办公室私人采购，奢华礼宾采购者，出席外交晚宴、海外王室场合、私人会员俱乐部及独家国际活动的女性',

  de: ', Botschaftspersonal und Diplomatinnen, Frauen, die mit arabischen Kundinnen, Golf-Partnern und Regierungsbeziehungsteams arbeiten, Fachkräfte für internationale Angelegenheiten und Protokoll, Hospitality- und Concierge-Teams, die Gäste bei bescheidener und formeller Anlassmode beraten, Frauen, die Stücke für Botschaftsempfänge, offizielle Besuche, Staatsdinners und kulturelle Termine wählen, Beraterinnen für internationale Besucherinnen bei Golf- und Emirati-Anlässen, Mitglieder königlicher Familien auf Reisen im Ausland, Mitglieder königlicher Haushalte und Sheikhas im Ausland, Prinzessinnen und Königinnen auf internationalen Reisen, VIP-Gäste und Privatkundschaft, Ultra-High-Net-Worth-Personen, Mitglieder vermögender Familien, Family-Office-Personal-Shopper, Luxus-Concierge-Käuferinnen, Frauen bei diplomatischen Galas, Höfen im Ausland, Privatclubs und exklusiven internationalen Events',

  nl: ', ambassadepersoneel en diplomaten, vrouwen die werken met Arabische klanten, Golf-partners en overheidsrelatieteams, internationale zaken- en protocolprofessionals, hospitality- en conciergeteams die gasten begeleiden bij bescheiden en formele gelegenheidskleding, vrouwen die stukken kiezen voor ambassaderecepties, officiële bezoeken, staatsdiners en culturele engagements, adviseurs die internationale bezoekers helpen passend te kleden voor Golf- en Emirati-gelegenheden, leden van koninklijke families die in het buitenland reizen, leden van koninklijke huishoudens en sheikhas in het buitenland, prinsessen en koninginnen op internationale reizen, VIP-gasten en privéklanten, ultra-high-net-worth individuen, leden van vermogende families, family-office personal shoppers, luxe conciergetekopers, vrouwen bij diplomatieke galas, hoven in het buitenland, privéclubs en exclusieve internationale evenementen',

  pt: ', funcionários de embaixadas e diplomatas, mulheres que trabalham com clientes árabes, parceiros do Golfo e equipas de relações governamentais, profissionais de assuntos internacionais e protocolo, equipas de hospitalidade e concierge que orientam convidadas sobre moda modesta e de cerimónia, mulheres que escolhem peças para receções em embaixadas, visitas oficiais, jantares de Estado e compromissos culturais, consultoras que ajudam visitantes internacionais a vestir-se para ocasiões do Golfo e emiratíes, membros de famílias reais a viajar no estrangeiro, membros de casas reais e sheikhas no exterior, princesas e rainhas em viagens internacionais, convidadas VIP e clientela privada, ultra-high-net-worth, membros de famílias de elevado património, personal shoppers de family offices, compradoras de concierge de luxo, mulheres em galas diplomáticas, cortes reais no estrangeiro, clubes privados e eventos internacionais exclusivos',

  id: ', staf kedutaan dan diplomat, wanita yang bekerja dengan klien Arab, mitra Teluk, dan tim hubungan pemerintah, profesional urusan internasional dan protokol, tim hospitality dan concierge yang membimbing tamu memilih busana modest dan formal, wanita memilih busana untuk resepsi kedutaan, kunjungan resmi, jamuan kenegaraan, dan acara budaya, penasihat yang membantu pengunjung internasional berpakaian untuk acara Teluk dan Emirati, anggota keluarga kerajaan yang bepergian ke luar negeri, anggota rumah tangga kerajaan dan sheikha di luar negeri, putri dan ratu dalam perjalanan internasional, tamu VIP dan klien privat, individu ultra-high-net-worth, anggota keluarga bernilai tinggi, personal shopper family office, pembeli concierge mewah, wanita di gala diplomatik, istana kerajaan di luar negeri, klub privat, dan acara internasional eksklusif',

  ms: ', kakitangan kedutaan dan diplomat, wanita yang bekerja dengan pelanggan Arab, rakan kongsi Teluk, dan pasukan hubungan kerajaan, profesional hal ehwal antarabangsa dan protokol, pasukan hospitaliti dan concierge yang membimbing tetamu memilih pakaian sopan dan formal, wanita memilih busana untuk majlis kedutaan, lawatan rasmi, jamuan negara, dan acara kebudayaan, penasihat yang membantu pelawat antarabangsa berpakaian untuk majlis Teluk dan Emirati, ahli keluarga diraja yang melancong ke luar negara, ahli isi rumah diraja dan sheikha di luar negara, puteri dan permaisuri dalam perjalanan antarabangsa, tetamu VIP dan pelanggan peribadi, individu ultra-high-net-worth, ahli keluarga bernilai tinggi, personal shopper pejabat keluarga, pembeli concierge mewah, wanita di gala diplomatik, istana diraja di luar negara, kelab persendirian, dan acara antarabangsa eksklusif',
}

export function getGlobalPdpSchemaAudienceExtension(locale: AppLocale = 'en'): string {
  return GLOBAL_PDP_SCHEMA_AUDIENCE_EXTENSION[locale] ?? GLOBAL_PDP_SCHEMA_AUDIENCE_EXTENSION.en
}

/** Append universal PDP audience segments to any product-specific `audienceType` string. */
export function appendGlobalPdpSchemaAudienceExtension(
  audienceType: string,
  locale: AppLocale = 'en',
): string {
  const extension = getGlobalPdpSchemaAudienceExtension(locale)
  const trimmed = audienceType.trim()
  const base =
    trimmed.endsWith('.') || trimmed.endsWith('。') ? trimmed.slice(0, -1) : trimmed
  return `${base}${extension}.`
}
