import type { Product } from '@/data/products'
import type { AppLocale } from '@/lib/i18n/routing'
import { getProductSlug } from '@/lib/products/links'
import {
  BRAND_GEO_PHRASE,
  getHeritageCraft,
} from '@/lib/products/heritageSeo'
import {
  brandGeoAltPhraseForLocale,
  buildAutoGeneratedProductImageAlt,
  buildCartLineFallbackAlt,
  withLocalizedBrandAlt,
} from '@/lib/products/imageAltI18n'
import {
  getLocalizedProductImageAltOverride,
  getLocalizedProductImageTitleOverride,
} from '@/lib/products/imageAltOverridesI18n'

export {
  altLoc,
  getLocalizedProductImageAltOverride,
  getLocalizedProductImageTitleOverride,
  hasProductImageAltOverride,
  PRODUCT_IMAGE_ALT_I18N,
  PRODUCT_IMAGE_TITLE_I18N,
} from '@/lib/products/imageAltOverridesI18n'

export { BRAND_GEO_PHRASE }

/** @deprecated Use BRAND_GEO_PHRASE */
export const BRAND_ALT_PHRASE = BRAND_GEO_PHRASE

const FALLBACK_ANGLES = ['front', 'side', 'back', 'three-quarter'] as const
const VIEW_SUFFIXES = ['three-quarter', 'cuff-close-up', 'close-up', 'lifestyle-2', 'lifestyle-1', 'lifestyle', 'front', 'back', 'side', 'detail', 'extra'] as const

/** Pixel dimensions for schema ImageObject enrichment (keyed by filename). */
export const PRODUCT_IMAGE_DIMENSIONS: Record<string, { width: number; height: number }> = {
  'bint-saeed-covent-garden-abaya-burgundy-lifestyle-sleeve-detail.webp': {
    width: 819,
    height: 1024,
  },
  'bint-saeed-nothing-hill-kaftan-gold-tone-signature-emblem-close-up.webp': {
    width: 2160,
    height: 2700,
  },
  'bint-saeed-marylebone-abaya-jade-heart-strand-lifestyle.webp': {
    width: 2160,
    height: 2700,
  },
  'bint-saeed-marylebone-abaya-lifestyle-jade-heart-strand-on-arm.webp': {
    width: 1080,
    height: 1350,
  },
  'bint-saeed-marylebone-abaya-signature-strands-gift-box-carnelian-lifestyle.webp': {
    width: 768,
    height: 1024,
  },
  'bint-saeed-marylebone-abaya-signature-strands-gift-box-malachite-carnelian-lifestyle.webp': {
    width: 768,
    height: 1024,
  },
}

const KNOWN_COLOR_SLUGS = [
  'dark-marroon',
  'marroon',
  'peach-pink',
  'navy-grey',
  'navy-blue',
  'dark-brown',
  'light-pink',
  'burgundy',
  'magenta',
  'black',
] as const

const COLOR_SLUG_LABELS: Record<string, string> = {
  'navy-grey': 'Navy Grey',
  'navy-blue': 'Navy Blue',
  'dark-brown': 'Dark Brown',
  'dark-marroon': 'Deep Maroon',
  marroon: 'Deep Maroon',
  'peach-pink': 'Peach Pink',
  'light-pink': 'Light Pink',
  burgundy: 'Burgundy',
  magenta: 'Magenta',
  black: 'Deep Black',
}

function colorNameFromSlug(slug: string): string {
  return COLOR_SLUG_LABELS[slug] ?? slugToColorName(slug)
}

function slugToColorName(slug: string): string {
  return slug.split('-').map(titleCaseToken).join(' ')
}

function titleCaseToken(token: string): string {
  return token.charAt(0).toUpperCase() + token.slice(1)
}

function inferAngleFromSrc(src: string, index = 0): string {
  const p = src.toLowerCase()
  if (p.includes('three-quarter') || p.includes('threequarter') || p.includes('3q')) return 'three-quarter'
  if (p.includes('lifestyle-2')) return 'lifestyle 2'
  if (p.includes('lifestyle-1') || p.includes('lifestyle')) return 'lifestyle'
  if (p.includes('cuff-close-up')) return 'cuff close-up'
  if (p.includes('close-up') || p.includes('closeup')) return 'close-up'
  if (p.includes('front') || /[-_\s]f\./.test(p)) return 'front'
  if (p.includes('back') || /[-_\s]b\./.test(p)) return 'back'
  if (p.includes('side') || /[-_\s]s\./.test(p)) return 'side'
  if (p.includes('detail') || /[-_\s]e\./.test(p)) return 'detail'
  if (p.includes('extra') || /[-_\s]v\./.test(p)) return 'extra'
  return FALLBACK_ANGLES[index % FALLBACK_ANGLES.length] ?? 'front'
}

/** Reads colour token from `bint-saeed-...-{colour}-{angle}.webp` filenames. */
function inferColorFromSrc(src: string): string | null {
  const base = src.split('/').pop()?.toLowerCase() ?? ''
  const stem = base.replace(/\.[^.]+$/, '').replace(/\.+$/, '')
  const withoutBrand = stem.replace(/^bint-saeed-/, '')

  for (const colorSlug of KNOWN_COLOR_SLUGS) {
    if (withoutBrand.includes(`-${colorSlug}-`) || withoutBrand.endsWith(`-${colorSlug}`)) {
      return colorNameFromSlug(colorSlug)
    }
  }

  for (const angle of VIEW_SUFFIXES) {
    const suffix = `-${angle}`
    if (!stem.endsWith(suffix)) continue
    const beforeAngle = stem.slice(0, -suffix.length).replace(/^bint-saeed-/, '')
    const tail = beforeAngle.split('-').pop()
    return tail ? titleCaseToken(tail) : null
  }

  return null
}

/** Ensures every alt string ends with the brand + geo phrase exactly once. */
export function withBrandAlt(alt: string, locale: AppLocale = 'en'): string {
  return withLocalizedBrandAlt(alt, locale)
}

export function getProductImageAlt(
  product: Pick<Product, 'name' | 'category' | 'colors' | 'slug'>,
  imageSrc: string,
  opts?: { color?: string; index?: number; locale?: AppLocale },
): string {
  const locale = opts?.locale ?? 'en'
  const filename = imageSrc.split('/').pop() ?? ''
  const override = getLocalizedProductImageAltOverride(filename, locale)
  if (override) return withLocalizedBrandAlt(override, locale)

  const color =
    opts?.color?.trim() ||
    inferColorFromSrc(imageSrc) ||
    product.colors[0]?.name ||
    'Black'
  const angle = inferAngleFromSrc(imageSrc, opts?.index ?? 0)
  const slug = getProductSlug(product)
  const craft = getHeritageCraft(slug)

  return buildAutoGeneratedProductImageAlt({
    productName: product.name,
    category: product.category,
    color,
    angle,
    locale,
    heritageCraft: craft,
  })
}

/** Curated SEO image titles (HTML title + schema ImageObject name when present). */
export function getProductImageTitle(
  imageSrc: string,
  opts?: { locale?: AppLocale },
): string | undefined {
  const locale = opts?.locale ?? 'en'
  const filename = imageSrc.split('/').pop() ?? ''
  return getLocalizedProductImageTitleOverride(filename, locale)
}

/** Cart / checkout thumbnails — full product alt when catalog match exists. */
export function getCartLineImageAlt(
  item: { id: string; name: string; image: string; color: string },
  catalogProduct: Pick<Product, 'name' | 'category' | 'colors' | 'slug'> | null | undefined,
  locale: AppLocale = 'en',
): string {
  if (catalogProduct) {
    return getProductImageAlt(catalogProduct, item.image, { color: item.color, index: 0, locale })
  }
  return buildCartLineFallbackAlt(item.name, item.color, locale)
}

export { brandGeoAltPhraseForLocale }
