import type { AppLocale } from '@/lib/i18n/routing'
import type { ProductFaqItem, ProductSchemaFacts } from '@/lib/products/productSchemaMeta'
import { getLocalizedKnightsbridgeDressExclusiveKeywords } from '@/lib/products/knightsbridgeDressSchemaKeywordsI18n'
import {
  getLocalizedKnightsbridgeDressFaq,
  getLocalizedKnightsbridgeDressSchemaFacts,
  KNIGHTSBRIDGE_DRESS_SLUG,
} from '@/lib/products/knightsbridgeDressSchemaLocalePacks'

export { KNIGHTSBRIDGE_DRESS_SLUG } from '@/lib/products/knightsbridgeDressSchemaLocalePacks'

/** Schema `audienceType` — discovery-rich for Knowledge Graph, AI Overviews, and semantic search. */
export const KNIGHTSBRIDGE_DRESS_SCHEMA_AUDIENCE: Record<AppLocale, string> = {
  en: 'Women seeking designer dresses, luxury dresses, premium dresses, elegant dresses, maxi dresses, halter dresses, travel dresses, holiday wardrobes, resort wear, contemporary womenswear, European fashion, Middle Eastern fashion, luxury modest fashion, designer modest fashion, women in the GCC, women in the UAE, Emirati women, Saudi women, Qatari women, Kuwaiti women, European women, American women, Canadian women, Asian women, international travellers, business women, creative professionals, luxury buyers, contemporary fashion buyers, women interested in Emirati heritage, and women seeking timeless wardrobes and elegant everyday dressing. Men seeking luxury gifts for their wife, daughter, mother, fiancée, girlfriend, or sister.',
  ar: 'النساء الباحثات عن فساتين مصمّمة، فساتين فاخرة، فساتين راقية، فساتين أنيقة، فساتين ماكسي، فساتين هالتر، فساتين سفر، خزائن عطلات، أزياء منتجعات، أزياء نسائية معاصرة، أزياء أوروبية، أزياء شرق أوسطية، أزياء محتشمة فاخرة، أزياء محتشمة مصمّمة، النساء في دول مجلس التعاون الخليجي، النساء في الإمارات، المرأة الإماراتية، المرأة السعودية، القطرية، الكويتية، الأوروبية، الأمريكية، الكندية، الآسيوية، المسافرات الدوليات، سيدات الأعمال، المبدعات، مشتريات الفاخر، مشتريات الأزياء المعاصرة، المهتمات بالتراث الإماراتي، والباحثات عن خزائن خالدة وأناقة يومية. الرجال الباحثون عن هدايا فاخرة للزوجة أو الابنة أو الأم أو الخطيبة أو الصديقة أو الأخت.',
  fr: 'Femmes en quête de robes de créateur, robes de luxe, robes premium, robes élégantes, robes maxi, robes halter, robes de voyage, garde-robes de vacances, resort wear, prêt-à-porter féminin contemporain, mode européenne, mode du Moyen-Orient, mode modeste de luxe, mode modeste de créateur, femmes du Golfe, femmes des Émirats, femmes émiraties, saoudiennes, qatariennes, koweïtiennes, européennes, américaines, canadiennes, asiatiques, voyageuses internationales, femmes d’affaires, professionnelles créatives, acheteuses de luxe, acheteuses de mode contemporaine, femmes intéressées par le patrimoine émirati, et femmes recherchant des garde-robes intemporelles et une élégance quotidienne. Hommes en quête de cadeaux de luxe pour leur épouse, fille, mère, fiancée, amie ou sœur.',
  it: 'Donne in cerca di abiti designer, abiti di lusso, abiti premium, abiti eleganti, abiti maxi, abiti halter, abiti da viaggio, guardaroba vacanza, resort wear, abbigliamento femminile contemporaneo, moda europea, moda mediorientale, moda modesta di lusso, moda modesta designer, donne nel Golfo, donne negli Emirati, donne emiratine, saudite, qatariote, kuwaitiane, europee, americane, canadesi, asiatiche, viaggiatrici internazionali, donne d’affari, professioniste creative, acquirenti di lusso, acquirenti di moda contemporanea, donne interessate al patrimonio emiratino, e donne che cercano guardaroba senza tempo ed eleganza quotidiana. Uomini in cerca di regali di lusso per moglie, figlia, madre, fidanzata, partner o sorella.',
  es: 'Mujeres que buscan vestidos de diseñador, vestidos de lujo, vestidos premium, vestidos elegantes, vestidos maxi, vestidos halter, vestidos de viaje, armarios vacacionales, resort wear, moda femenina contemporánea, moda europea, moda de Oriente Medio, moda modesta de lujo, moda modesta de diseñador, mujeres en el Golfo, mujeres en los EAU, mujeres emiratíes, saudíes, qataríes, kuwaitíes, europeas, estadounidenses, canadienses, asiáticas, viajeras internacionales, mujeres de negocios, profesionales creativas, compradoras de lujo, compradoras de moda contemporánea, mujeres interesadas en el patrimonio emiratí, y mujeres que buscan armarios atemporales y elegancia cotidiana. Hombres que buscan regalos de lujo para esposa, hija, madre, prometida, novia o hermana.',
  ru: 'Женщины, ищущие дизайнерские платья, роскошные платья, премиальные платья, элегантные платья, платья макси, платья с воротником halter, платья для путешествий, праздничный гардероб, курортную одежду, современную женскую моду, европейскую моду, ближневосточную моду, роскошную скромную моду, дизайнерскую скромную моду, женщин в странах Залива, женщин в ОАЭ, эмираток, саудовок, катарок, кувейтянок, европеек, американок, канадок, азиаток, международных путешественниц, деловых женщин, творческих профессионалок, покупательниц люкса, покупательниц современной моды, женщин, интересующихся эмиратским наследием, и женщин, ищущих вневременной гардероб и элегантный повседневный стиль. Мужчины, ищущие роскошные подарки для жены, дочери, матери, невесты, девушки или сестры.',
  zh: '寻求设计师连衣裙、奢华连衣裙、高端连衣裙、优雅连衣裙、长款连衣裙、挂脖连衣裙、旅行连衣裙、假日衣橱、度假装、当代女装、欧洲时尚、中东时尚、奢华端庄时尚、设计师端庄时尚的海湾女性、阿联酋女性、阿联酋本地女性、沙特女性、卡塔尔女性、科威特女性、欧洲女性、美国女性、加拿大女性、亚洲女性、国际旅行者、职业女性、创意专业人士、奢侈品买家、当代时尚买家、对阿联酋传统感兴趣的女性，以及追求隽永衣橱与日常优雅的女性。为妻子、女儿、母亲、未婚妻、女友或姐妹寻找奢华礼品的男性。',
  de: 'Frauen auf der Suche nach Designer-Kleidern, Luxuskleidern, Premium-Kleidern, eleganten Kleidern, Maxikleidern, Halter-Kleidern, Reisekleidern, Urlaubsgarderoben, Resortwear, zeitgenössischer Damenmode, europäischer Mode, nahöstlicher Mode, luxuriöser bescheidener Mode, Designer-bescheidener Mode, Frauen im Golf, Frauen in den VAE, emiratischen, saudischen, katarischen, kuwaitischen, europäischen, amerikanischen, kanadischen und asiatischen Frauen, internationalen Reisenden, Geschäftsfrauen, Kreativprofis, Luxuskäuferinnen, zeitgenössischen Modekäuferinnen, Frauen mit Interesse am emiratischen Erbe und Frauen, die zeitlose Garderoben und elegante Alltags-eleganz suchen. Männer auf der Suche nach Luxusgeschenken für Ehefrau, Tochter, Mutter, Verlobte, Freundin oder Schwester.',
  nl: 'Vrouwen die op zoek zijn naar designerjurken, luxe jurken, premium jurken, elegante jurken, maxi-jurken, halterjurken, reisjurken, vakantiegarderobes, resort wear, eigentijdse damesmode, Europese mode, Midden-Oosterse mode, luxe bescheiden mode, designer bescheiden mode, vrouwen in de Golfstaten, vrouwen in de VAE, Emiratische, Saoedische, Qatarese, Koeweitse, Europese, Amerikaanse, Canadese en Aziatische vrouwen, internationale reizigers, zakenvrouwen, creatieve professionals, luxe kopers, eigentijdse modekopers, vrouwen geïnteresseerd in Emiratisch erfgoed, en vrouwen die tijdloze garderobes en elegante dagelijkse stijl zoeken. Mannen die luxe cadeaus zoeken voor echtgenote, dochter, moeder, verloofde, vriendin of zus.',
  pt: 'Mulheres que procuram vestidos de designer, vestidos de luxo, vestidos premium, vestidos elegantes, vestidos maxi, vestidos halter, vestidos de viagem, guarda-roupas de férias, resort wear, moda feminina contemporânea, moda europeia, moda do Médio Oriente, moda modesta de luxo, moda modesta de designer, mulheres no Golfo, mulheres nos EAU, mulheres emiratis, sauditas, qatarenses, kuwaitianas, europeias, americanas, canadianas, asiáticas, viajantes internacionais, mulheres de negócios, profissionais criativas, compradoras de luxo, compradoras de moda contemporânea, mulheres interessadas no património emirati, e mulheres que procuram guarda-roupas intemporais e elegância quotidiana. Homens que procuram presentes de luxo para esposa, filha, mãe, noiva, namorada ou irmã.',
  id: 'Wanita yang mencari gaun desainer, gaun mewah, gaun premium, gaun elegan, gaun maxi, gaun halter, gaun perjalanan, lemari liburan, resort wear, busana wanita kontemporer, fashion Eropa, fashion Timur Tengah, busana modest mewah, busana modest desainer, wanita di GCC, wanita di UEA, wanita Emirati, Saudi, Qatar, Kuwait, Eropa, Amerika, Kanada, Asia, pelancong internasional, wanita karier, profesional kreatif, pembeli barang mewah, pembeli fashion kontemporer, wanita yang tertarik warisan Emirati, dan wanita yang mencari lemari abadi serta keanggunan sehari-hari. Pria yang mencari hadiah mewah untuk istri, putri, ibu, tunangan, pacar, atau saudara perempuan.',
  ms: 'Wanita yang mencari gaun pereka, gaun mewah, gaun premium, gaun anggun, gaun maxi, gaun halter, gaun perjalanan, almari percutian, resort wear, fesyen wanita kontemporari, fesyen Eropah, fesyen Timur Tengah, fesyen sopan mewah, fesyen sopan pereka, wanita di GCC, wanita di UAE, wanita Emirati, Saudi, Qatar, Kuwait, Eropah, Amerika, Kanada, Asia, pelancong antarabangsa, wanita profesional, profesional kreatif, pembeli barangan mewah, pembeli fesyen kontemporari, wanita berminat warisan Emirati, dan wanita yang mencari almari abadi serta keanggunan harian. Lelaki yang mencari hadiah mewah untuk isteri, anak perempuan, ibu, tunang, teman wanita, atau kakak.',
}

export function isKnightsbridgeDressSlug(slug: string): boolean {
  return slug.toLowerCase() === KNIGHTSBRIDGE_DRESS_SLUG
}

export function getKnightsbridgeDressSchemaAudience(locale: AppLocale = 'en'): string {
  return KNIGHTSBRIDGE_DRESS_SCHEMA_AUDIENCE[locale] ?? KNIGHTSBRIDGE_DRESS_SCHEMA_AUDIENCE.en
}

export function getKnightsbridgeDressSchemaKeywords(
  locale: AppLocale = 'en',
  colorName?: string,
): string {
  return getLocalizedKnightsbridgeDressExclusiveKeywords(locale, colorName).join(', ')
}

export {
  getLocalizedKnightsbridgeDressSchemaFacts,
  getLocalizedKnightsbridgeDressFaq,
} from '@/lib/products/knightsbridgeDressSchemaLocalePacks'

export type { ProductFaqItem, ProductSchemaFacts }
