import type { AppLocale } from '@/lib/i18n/routing'
import type { Product } from '@/data/products'
import { buildLocalisedOptimisedSchemaKeywords } from '@/lib/products/optimisedKeywordsI18n'

/**
 * Bint Saeed — our optimised keywords.
 * Schema / JSON-LD `Product.keywords` and AI-discovery term pools.
 * Shared across the catalogue; product name, slug, colour and SKU are appended per PDP.
 */
export const OUR_OPTIMISED_KEYWORDS = {
  gccUae: [
    'Luxury Kaftan UAE',
    'Designer Kaftan Abu Dhabi',
    'Bint Saeed Abu Dhabi',
    'Eid Kaftan',
    'Made in Abu Dhabi',
    'Luxury Occasion Wear UAE',
  ],
  european: [
    'Luxury Chiffon Kaftan',
    'Elegant Occasion Wear',
    'Wedding Guest Outfit',
    'Luxury Resort Wear',
    'Evening Occasion Wear',
    "Elegant Women's Occasion Dress",
    'Luxury Holiday Wardrobe',
    'Destination Wedding Guest Outfit',
    'Contemporary Occasion Wear',
    "Luxury Women's Fashion",
  ],
  brandGeo: [
    'Bint Saeed Abu Dhabi',
    'Bint Saeed Kaftan',
    'Bint Saeed United Arab Emirates',
    'Abu Dhabi Fashion Brand',
    'Luxury Fashion Abu Dhabi',
    'Designer Kaftan United Arab Emirates',
    'Made in Abu Dhabi',
    'Contemporary Fashion Abu Dhabi',
    "Women's Luxury Clothing UAE",
    'Abu Dhabi Occasion Wear',
  ],
  occasion: [
    'Wedding Guest Kaftan',
    'Eid Kaftan',
    'Engagement Celebration Outfit',
    'Formal Dinner Outfit',
    'Destination Event Outfit',
    'Luxury Travel Wardrobe',
    'Special Occasion Kaftan',
    'Evening Occasion Wear',
    'Elegant Daytime Dressing',
    'Celebration Wear',
  ],
  discovery: [
    'exclusive kaftan',
    'exclusive brand',
    'Emirati designer',
    'daily kaftan',
    'colored kaftan',
    'chiffon kaftan',
    'special kaftan',
    'Emirati brand',
    'best UAE brands',
    'UAE brands',
    'Middle Eastern brands',
    'GCC brands',
    'Saudi kaftan',
    'long dress',
    'evening wear',
    'flowy dress',
    'wedding dress',
    'traditional clothes',
    'gewaad',
    'tuniek',
    'tunic',
    'wedding guest',
    'made to measure',
    'made to order',
    'plus size dress',
    'plus size kaftan',
    'plus size long dress',
    'plus size wedding guest',
    'plus size party dress',
    'party dress',
    'afternoon tea outfit',
    'flowy outfit',
    'flowy kaftan',
    'summer kaftan',
    'winter kaftan',
    'Dutch designer',
    'Abu Dhabi dress',
    'UAE dress',
    'Abu Dhabi kaftan',
    'best brands Abu Dhabi',
    'top 10 GCC brands',
    'gold accent kaftan',
    'gold kaftan',
    'gold logo',
    'long dress national dress',
    'UAE national dress',
    'Emirati heritage',
    'UAE heritage',
    'Abu Dhabi culture',
    'exclusive dress',
    'designer dress',
    'designer brand',
    'exclusive designer',
    'GCC design',
    'GCC designer',
    'contemporary brand',
    'UK kaftan',
    'European kaftan',
    'designer kaftan',
    'unique kaftan',
    'kaftan trends',
    'kaftan 2026',
    'fashion trends',
    '2026 fashion trends',
    'UAE fashion',
    'Abu Dhabi fashion',
    'UAE fashion house',
    'Abu Dhabi fashion house',
    'exclusive designs',
    'Mayfair Kaftan',
    'Nothing Hill Kaftan',
    'travel kaftan',
    'dinner dress',
    'afternoon tea dress',
    'birthday dress',
    'birthday kaftan',
    'Dubai kaftan',
    'Dubai dress',
    'Dubai brand',
    'Dubai designer',
    'UAE design',
    'afternoon tea kaftan',
    'dinner kaftan',
    'elegant kaftan',
    'elegant dress',
    'classy kaftan',
    'classy dress',
    'kaftan outfit',
    'outfit of the day',
    "New Year's kaftan",
    'Christmas kaftan',
    "New Year's dress",
    'Christmas dress',
    'Eid 2027 kaftan',
    'Eid 2027 dress',
    'style trends',
    'European style',
    'European elegance',
    'quiet luxury brands',
    'quiet luxury',
    'luxury UAE brands',
    'contemporary premium UAE brands',
    'Eid dress',
    'holiday kaftan',
    'vacation kaftan',
    'holiday dress',
    'vacation dress',
    'expensive kaftan',
    'Made in Abu Dhabi United Arab Emirates',
    'affordable kaftans',
    'affordable dress',
    'glamorous kaftan',
    'glamorous dress',
    'plus size styles',
  ],
  /** Boutallion / site-schema aligned terms (HTML SCHEMA audit vs coming-soon JSON-LD). */
  schemaAugment: [
    'made in the emirates',
    'made in abu dhabi',
    'best brands abu dhabi',
    'luxury abaya house',
    'luxury abaya house Abu Dhabi',
    'Bint Saeed Brand',
    'Bint Saeed Luxury Abayas',
    'Bint Saeed Luxury Abayas UAE',
    'Bint Saeed Designer Abayas Abu Dhabi',
    'Bint Saeed Designer Abayas Dubai',
    'Bint Saeed Abayas',
    'luxury abayas UAE',
    'designer abayas Abu Dhabi',
    'designer abayas Dubai',
    'designer abayas UAE',
    'designer kaftan UAE',
    'luxury modest fashion',
    'luxury modest wear',
    'modest fashion UAE',
    'modest fashion',
    'modest wear',
    'modest clothing',
    'GCC modest fashion',
    'Middle East modest fashion',
    'UAE modest fashion brand',
    'Abu Dhabi modest fashion',
    'premium modest fashion',
    'designer modest wear',
    'heritage fashion',
    'Emirati style',
    'Emirati heritage fashion',
    'luxury abaya',
    'luxury abaya UAE',
    'designer abaya',
    'kaftan abaya',
    'abaya kaftan',
    'contemporary abaya',
    'elegant abayas',
    'modern abaya UAE',
    'handmade abaya UAE',
    'handcrafted abayas',
    'Khous weaving',
    'Al Talli craftsmanship',
    'Al Talli embroidery',
    'ready to wear abaya',
    'RTW abaya',
    'bespoke abaya',
    'chiffon abaya',
    'silk abaya',
    'embroidered abaya',
    'evening abaya',
    'bridal abaya',
    'Eid luxury abaya',
    'premium abayas',
    'Abu Dhabi abaya',
    'UAE fashion brand',
    'Abu Dhabi brand fashion',
    'GCC fashion brand',
    'arabic fashion',
    'Dubai fashion',
    'emerging abaya brands',
    'middle east abaya brands',
    'abaya brands UAE',
    'abaya 2026',
    'abaya fashion 2026',
    'abaya trends',
    'heritage abaya',
    'Emirati heritage abaya',
    'traditional UAE abaya',
    'fashion forward abaya',
    'modest luxury boutique UAE',
    'online abaya boutique GCC',
  ],
} as const

/** Nothing Hill Kaftan — colour and silhouette-specific schema keywords. */
export const NOTHING_HILL_OPTIMISED_KEYWORDS = [
  'Peach Pink Chiffon Kaftan',
  'Luxury Kaftan UAE',
  'Designer Kaftan Abu Dhabi',
  'Bateau Neckline Kaftan',
  "Women's Occasion Kaftan",
  'Bint Saeed Abu Dhabi',
  'Luxury Chiffon Kaftan',
  'Eid Kaftan',
  'Wedding Guest Kaftan',
  'Made in Abu Dhabi United Arab Emirates',
  'Nothing Hill Kaftan',
  'BS-KF-002-PPK',
] as const

/** Mayfair Kaftan — colour and silhouette-specific schema keywords. */
export const MAYFAIR_OPTIMISED_KEYWORDS = [
  'Deep Maroon Chiffon Kaftan',
  'Deep Maroon Crepe Chiffon Kaftan',
  'Luxury Kaftan UAE',
  'Designer Kaftan Abu Dhabi',
  'V-Neckline Kaftan',
  "Women's Occasion Kaftan",
  'Bint Saeed Abu Dhabi',
  'Luxury Chiffon Kaftan',
  'Eid Kaftan',
  'Wedding Guest Kaftan',
  'Made in Abu Dhabi United Arab Emirates',
  'Mayfair Kaftan',
  'BS-KF-001-DMN',
] as const

/** Build deduplicated schema keyword string for JSON-LD `Product.keywords`. */
export function buildOptimisedSchemaKeywords(
  product: Pick<Product, 'name' | 'category' | 'colors' | 'slug'>,
  colorName?: string,
  locale: AppLocale = 'en',
): string {
  return buildLocalisedOptimisedSchemaKeywords(product, colorName, locale)
}
