import type { AppLocale } from '@/lib/i18n/routing'

export type CodesExpandedId =
  | 'the-monogram'
  | 'al-talli'
  | 'khous'
  | 'al-ain-rosette'
  | 'knotted-lines-of-lineage'
  | 'the-strands'

const EXPANDED: Record<AppLocale, Record<CodesExpandedId, string>> = {
  en: {
    'the-monogram': 'The monogram is built on the idea of connection and return. Its form draws from interlocking lines, reflecting continuity between past and present. It is applied across garments, jewellery, and objects with precision, either as a quiet detail or as a defining element. As a visual signature, it anchors each piece within the language of the house while remaining adaptable across contexts.',
    'al-talli': 'Al Talli is a heritage craft practiced across the United Arab Emirates, traditionally handwoven using cotton and metallic threads. It forms part of the broader textile traditions of the region, closely tied to techniques recognised on UNESCO’s Representative List of the Intangible Cultural Heritage of Humanity. Historically used to embellish garments, it carries both technical mastery and cultural meaning. Within Bint Saeed, this craft is reinterpreted through placement, structure, and material, allowing it to exist within a contemporary wardrobe while maintaining its origin.',
    'khous': 'Al Khous is a traditional craft of the United Arab Emirates, using dried palm fronds to create woven forms. It belongs to a wider body of heritage practices connected to palm cultivation and craft traditions across the region, which are recognised within UNESCO-listed cultural expressions. Historically used in everyday objects, its strength lies in its structure, built through interlacing patterns that create durability and form. At Bint Saeed, this logic is translated into garment construction and detailing, where lines, folds, and layering reflect the same principles in a modern context.',
    'al-ain-rosette': '',
    'knotted-lines-of-lineage': 'Knotted Lines are developed as a defining element within the house. Each line is shaped in relation to another, forming knots that reflect connection across time, experience, and generation. What is inherited and what is lived become intertwined, creating a continuous thread rather than separate moments.\n\nWithin Bint Saeed, these knots take form as buttons on abayas and as strands across garments. The strands, often composed of natural stones, are placed with care, frequently along the shoulder, where they bring balance to the silhouette while remaining close to the wearer.\n\nTheir placement is considered. Each knot serves as a reminder of the story you carry, shaped by where you come from and what you move through. A story that is interconnected, personal, and ongoing, one you recognise, stand within, and carry forward with pride.',
    'the-strands': 'The Strands belong to a longer lineage of adornment in the region, where thread, stone, and gesture have long marked continuity across generations. At Bint Saeed, each strand is assembled from natural stones chosen for tone, grain, and proportion. They are positioned with care — most often at the shoulder — where they introduce equilibrium to the abaya without disturbing its line.\n\nAs a house code, The Strands translate an abstract principle into something worn: that what is carried from where you come from remains present, yet restrained. They appear across abayas and objects as a recognisable signature of the house — a quiet thread that persists from piece to piece, and from one chapter of the story to the next.',
  },
  ar: {
    'the-monogram': 'يُبنى المونوغرام على فكرة الاتصال والعودة. تستمد هيئته من خطوط متداخلة تعكس الاستمرارية بين الماضي والحاضر. يُطبَّق بدقة على الثياب والمجوهرات والأغراض — تفصيلاً هادئاً أو عنصراً محدِّداً. كتوقيع بصري، يرسّخ كل قطعة في لغة الدار مع بقائه قابلاً للتكيّف عبر السياقات.',
    'al-talli': 'التلي حرفة تراثية تُمارَس في دولة الإمارات العربية المتحدة، تُنسَج يدوياً تقليدياً بخيوط القطن والمعدن. ينتمي إلى تقاليد النسيج الأوسع في المنطقة، ويرتبط بتقنيات مدرجة في القائمة التمثيلية للتراث الثقافي غير المادي لليونسكو. استُخدم تاريخياً لتزيين الثياب، حاملاً إتقاناً تقنياً ومعنى ثقافياً. في بنت سعيد، يُعاد تفسير هذه الحرفة عبر الموضع والبنية والخامة، لتبقى ضمن خزانة معاصرة مع حفظ أصلها.',
    'khous': 'الخوص حرفة تقليدية إماراتية تستخدم سعف النخيل المجفف لصناعة أشكال منسوجة. ينتمي إلى ممارسات تراثية أوسع مرتبطة بزراعة النخيل والحرف في المنطقة، والمعترف بها ضمن تعبيرات ثقافية مدرجة لدى اليونسكو. استُخدم تاريخياً في أغراض يومية، وقوته في بنيته: أنماط متداخلة تخلق متانة وهيئة. في بنت سعيد، تُترجم هذه المنطق إلى بناء الثوب وتفاصيله، حيث تعكس الخطوط والطيات والطبقات المبادئ ذاتها في سياق معاصر.',
    'al-ain-rosette': '',
    'knotted-lines-of-lineage': 'الخطوط المعقودة عنصر محدِّد في الدار. يتشكّل كل خط بالنسبة إلى آخر، مكوناً عقداً تعكس الاتصال عبر الزمن والتجربة والجيل. ما يُورث وما يُعاش يتشابكان، خيطاً متصلاً لا لحظات منفصلة.\n\nفي بنت سعيد، تأخذ هذه العقد شكل أزرار على العباءات وستراندات عبر الثياب. تُوضع الستراندات — غالباً من أحجار طبيعية — بعناية، كثيراً على الكتف، حيث توازن القوام وتبقى قريبة من مرتديتها.\n\nموضعها مدروس. كل عقدة تذكير بالقصة التي تحملينها، مشكَّلة بما جئتِ منه وبما تمرّين به. قصة مترابطة وشخصية ومستمرة — تعرفينها، وتقفين فيها، وتحملينها بفخر.',
    'the-strands': 'ستراندات تنتسب إلى سلالة أطول من الزينة في المنطقة، حيث خيط وحجر وإيماءة طالما وسمت الاستمرارية عبر الأجيال. في بنت سعيد، يُجمع كل ستراند من أحجار طبيعية مختارة للنغمة والحبوب والتناسب. تُوضع بعناية — غالباً على الكتف — حيث تُدخل توازناً إلى العباءة دون إخلال بخطها.\n\nكرمز للدار، تترجم الستراندات مبدأً مجرّداً إلى ما يُرتدى: أن ما يُحمل من أصلك يبقى حاضراً، لكن بتحفّظ. تظهر عبر العباءات والأغراض كتوقيع معروف للدار — خيط هادئ يمتد من قطعة إلى قطعة، ومن فصل في القصة إلى التالي.',
  },
  fr: {
    'the-monogram': 'Le monogramme repose sur l’idée de connexion et de retour. Sa forme s’inspire de lignes entrelacées, reflet d’une continuité entre passé et présent. Il s’applique avec précision aux vêtements, bijoux et objets — détail discret ou élément déterminant. Signature visuelle, il ancre chaque pièce dans le langage de la maison tout en restant adaptable.',
    'al-talli': 'Al Talli est un savoir-faire patrimonial pratiqué aux Émirats arabes unis, traditionnellement tissé à la main en fils de coton et métalliques. Il s’inscrit dans les traditions textiles de la région, liées à des techniques reconnues sur la Liste représentative du patrimoine culturel immatériel de l’UNESCO. Historiquement utilisé pour orner les vêtements, il porte maîtrise technique et sens culturel. Chez Bint Saeed, ce métier est réinterprété par le placement, la structure et la matière, pour exister dans une garde-robe contemporaine sans quitter son origine.',
    'khous': 'Al Khous est un métier traditionnel des Émirats arabes unis, utilisant des frondes de palmier séchées pour créer des formes tissées. Il appartient à un ensemble plus large de pratiques liées à la culture du palmier et aux artisanats de la région, reconnus au sein d’expressions culturelles inscrites à l’UNESCO. Historiquement présent dans le quotidien, sa force réside dans sa structure — motifs entrelacés qui créent durabilité et forme. Chez Bint Saeed, cette logique se traduit dans la construction et le détail du vêtement, où lignes, plis et superpositions reflètent les mêmes principes dans un contexte moderne.',
    'al-ain-rosette': '',
    'knotted-lines-of-lineage': 'Les Knotted Lines sont un élément déterminant de la maison. Chaque ligne se forme par rapport à une autre, nouant des liens à travers le temps, l’expérience et la génération. L’hérité et le vécu s’entrelacent en un fil continu plutôt qu’en moments séparés.\n\nChez Bint Saeed, ces nœuds prennent forme de boutons sur les abayas et de strands sur les vêtements. Les strands, souvent en pierres naturelles, sont placés avec soin — fréquemment à l’épaule — où ils équilibrent la silhouette tout en restant proches de celle qui les porte.\n\nLeur placement est réfléchi. Chaque nœud rappelle l’histoire que l’on porte, façonnée par d’où l’on vient et par ce que l’on traverse. Une histoire interconnectée, personnelle et continue — que l’on reconnaît, où l’on se tient, et que l’on porte avec fierté.',
    'the-strands': 'The Strands appartiennent à une lignée plus longue de parure dans la région, où fil, pierre et geste ont longtemps marqué la continuité entre générations. Chez Bint Saeed, chaque strand est assemblé de pierres naturelles choisies pour le ton, le grain et la proportion. Ils sont placés avec soin — le plus souvent à l’épaule — où ils introduisent un équilibre à l’abaya sans troubler sa ligne.\n\nComme code de maison, The Strands traduisent un principe abstrait en quelque chose de porté : ce qui vient d’où l’on vient demeure présent, pourtant retenu. Ils apparaissent sur abayas et objets comme signature reconnaissable de la maison — un fil discret qui persiste d’une pièce à l’autre, d’un chapitre à l’autre.',
  },
  it: {
    'the-monogram': 'Il monogramma si fonda sull’idea di connessione e ritorno. La sua forma nasce da linee intrecciate, riflesso di continuità tra passato e presente. Si applica con precisione a abiti, gioielli e oggetti — dettaglio quieto o elemento definitorio. Come firma visiva ancora ogni pezzo nel linguaggio della casa, restando adattabile.',
    'al-talli': 'Al Talli è un mestiere patrimoniale praticato negli Emirati Arabi Uniti, tradizionalmente tessuto a mano con fili di cotone e metallici. Fa parte delle tradizioni tessili della regione, legate a tecniche riconosciute nella Lista rappresentativa del patrimonio culturale immateriale dell’UNESCO. Storicamente usato per abbellire gli abiti, porta maestria tecnica e significato culturale. Da Bint Saeed questo mestiere è reinterpretato attraverso disposizione, struttura e materia, per esistere in un guardaroba contemporaneo senza perdere l’origine.',
    'khous': 'Al Khous è un mestiere tradizionale degli Emirati Arabi Uniti che usa foglie di palma essiccate per creare forme tessute. Appartiene a un più ampio insieme di pratiche legate alla coltivazione della palma e agli artigianati della regione, riconosciuti entro espressioni culturali iscritte all’UNESCO. Storicamente presente negli oggetti quotidiani, la sua forza è nella struttura — motivi intrecciati che creano durata e forma. Da Bint Saeed questa logica si traduce nella costruzione e nel dettaglio dell’abito, dove linee, pieghe e stratificazioni riflettono gli stessi principi in un contesto moderno.',
    'al-ain-rosette': '',
    'knotted-lines-of-lineage': 'Le Knotted Lines sono un elemento definitorio della casa. Ogni linea si forma in relazione a un’altra, creando nodi che riflettono connessione attraverso tempo, esperienza e generazione. Ciò che è ereditato e ciò che è vissuto si intrecciano in un filo continuo piuttosto che in momenti separati.\n\nDa Bint Saeed questi nodi prendono forma di bottoni sulle abaya e di strand sugli abiti. Gli strand, spesso in pietre naturali, sono posti con cura — spesso sulla spalla — dove bilanciano la silhouette restando vicini a chi li indossa.\n\nLa loro collocazione è meditata. Ogni nodo ricorda la storia che si porta, plasmata da dove si viene e da ciò che si attraversa. Una storia interconnessa, personale e continua — che si riconosce, in cui si sta, e che si porta con orgoglio.',
    'the-strands': 'The Strands appartengono a una stirpe più lunga di ornamento nella regione, dove filo, pietra e gesto hanno a lungo segnato la continuità tra generazioni. Da Bint Saeed ogni strand è assemblato con pietre naturali scelte per tono, grana e proporzione. Sono posizionati con cura — più spesso sulla spalla — dove introducono equilibrio all’abaya senza disturbare la linea.\n\nCome codice della casa, The Strands traducono un principio astratto in qualcosa di indossato: ciò che si porta da dove si viene rimane presente, eppure contenuto. Appaiono su abaya e oggetti come firma riconoscibile della casa — un filo quieto che persiste da pezzo a pezzo, da un capitolo all’altro.',
  },
  es: {
    'the-monogram': 'El monograma se construye sobre la idea de conexión y retorno. Su forma nace de líneas entrelazadas, reflejo de continuidad entre pasado y presente. Se aplica con precisión a prendas, joyería y objetos — detalle callado o elemento definitorio. Como firma visual ancla cada pieza en el lenguaje de la casa, manteniéndose adaptable.',
    'al-talli': 'Al Talli es un oficio patrimonial practicado en los Emiratos Árabes Unidos, tradicionalmente tejido a mano con hilos de algodón y metálicos. Forma parte de las tradiciones textiles de la región, vinculadas a técnicas reconocidas en la Lista representativa del patrimonio cultural inmaterial de la UNESCO. Históricamente usado para embellecer prendas, porta maestría técnica y sentido cultural. En Bint Saeed este oficio se reinterpreta mediante la colocación, la estructura y el material, para existir en un guardarropa contemporáneo sin abandonar su origen.',
    'khous': 'Al Khous es un oficio tradicional de los Emiratos Árabes Unidos que usa hojas de palma secas para crear formas tejidas. Pertenece a un conjunto más amplio de prácticas ligadas al cultivo de la palma y a los oficios de la región, reconocidos dentro de expresiones culturales inscritas en la UNESCO. Históricamente presente en objetos cotidianos, su fuerza está en la estructura — motivos entrelazados que crean durabilidad y forma. En Bint Saeed esta lógica se traduce en la construcción y el detalle de la prenda, donde líneas, pliegues y capas reflejan los mismos principios en un contexto moderno.',
    'al-ain-rosette': '',
    'knotted-lines-of-lineage': 'Las Knotted Lines son un elemento definitorio de la casa. Cada línea se forma en relación con otra, creando nudos que reflejan conexión a través del tiempo, la experiencia y la generación. Lo heredado y lo vivido se entrelazan en un hilo continuo más que en momentos separados.\n\nEn Bint Saeed estos nudos toman forma de botones en las abayas y de strands en las prendas. Los strands, a menudo de piedras naturales, se colocan con cuidado — frecuentemente en el hombro — donde equilibran la silueta y permanecen cerca de quien los lleva.\n\nSu colocación es meditada. Cada nudo recuerda la historia que se lleva, moldeada por de dónde se viene y por lo que se atraviesa. Una historia interconectada, personal y continua — que se reconoce, en la que se está, y que se lleva con orgullo.',
    'the-strands': 'The Strands pertenecen a un linaje más largo de adorno en la región, donde hilo, piedra y gesto han marcado durante mucho tiempo la continuidad entre generaciones. En Bint Saeed cada strand se ensambla con piedras naturales elegidas por tono, grano y proporción. Se colocan con cuidado — con más frecuencia en el hombro — donde introducen equilibrio a la abaya sin alterar su línea.\n\nComo código de la casa, The Strands traducen un principio abstracto en algo que se lleva: lo que se trae de donde se viene permanece presente, y sin embargo contenido. Aparecen en abayas y objetos como firma reconocible de la casa — un hilo callado que persiste de pieza a pieza, de un capítulo al siguiente.',
  },
  de: {
    'the-monogram': 'Das Monogramm gründet auf der Idee von Verbindung und Rückkehr. Seine Form schöpft aus ineinandergreifenden Linien und spiegelt Kontinuität zwischen Vergangenheit und Gegenwart. Es wird präzise auf Gewänder, Schmuck und Objekte angewendet — als stilles Detail oder bestimmendes Element. Als visuelle Signatur verankert es jedes Stück in der Sprache des Hauses und bleibt dabei anpassungsfähig.',
    'al-talli': 'Al Talli ist ein Heritage-Handwerk in den Vereinigten Arabischen Emiraten, traditionell handgewebt aus Baumwoll- und Metallfäden. Es gehört zu den Textiltraditionen der Region, verbunden mit Techniken, die auf der Repräsentativen Liste des immateriellen Kulturerbes der UNESCO anerkannt sind. Historisch zur Verzierung von Gewändern genutzt, trägt es technische Meisterschaft und kulturelle Bedeutung. Bei Bint Saeed wird dieses Handwerk über Platzierung, Struktur und Material neu gedeutet — in einer zeitgenössischen Garderobe, ohne seinen Ursprung zu verlassen.',
    'khous': 'Al Khous ist ein traditionelles Handwerk der Vereinigten Arabischen Emirate, das getrocknete Palmwedel zu gewebten Formen verarbeitet. Es gehört zu einem weiteren Kreis von Praktiken rund um Palmenkultur und regionale Handwerke, anerkannt innerhalb UNESCO-gelisteter kultureller Ausdrucksformen. Historisch in Alltagsgegenständen präsent, liegt seine Stärke in der Struktur — verschlungene Muster, die Dauerhaftigkeit und Form schaffen. Bei Bint Saeed übersetzt sich diese Logik in Kleidungskonstruktion und Detail, wo Linien, Falten und Schichtungen dieselben Prinzipien im modernen Kontext spiegeln.',
    'al-ain-rosette': '',
    'knotted-lines-of-lineage': 'Knotted Lines sind ein bestimmendes Element des Hauses. Jede Linie formt sich in Bezug auf eine andere und knüpft Verbindungen über Zeit, Erfahrung und Generation. Ererbtes und Gelebtes verflechten sich zu einem durchgehenden Faden statt getrennter Momente.\n\nBei Bint Saeed werden diese Knoten zu Knöpfen an Abayas und zu Strands an Gewändern. Die Strands — oft aus Natursteinen — sind sorgfältig gesetzt, häufig an der Schulter, wo sie die Silhouette ausgleichen und nah am Träger bleiben.\n\nIhre Platzierung ist bedacht. Jeder Knoten erinnert an die Geschichte, die man trägt — geformt davon, woher man kommt und was man durchlebt. Eine miteinander verwobene, persönliche und fortlaufende Geschichte — die man erkennt, in der man steht und die man mit Stolz weiterträgt.',
    'the-strands': 'The Strands gehören zu einer längeren Linie der Schmückung in der Region, in der Faden, Stein und Geste seit Langem Kontinuität über Generationen markieren. Bei Bint Saeed wird jeder Strand aus Natursteinen zusammengesetzt — gewählt nach Ton, Korn und Proportion. Sie sind sorgfältig gesetzt — meist an der Schulter — und bringen der Abaya Gleichgewicht, ohne ihre Linie zu stören.\n\nAls House Code übersetzen The Strands ein abstraktes Prinzip in etwas Getragenes: Was man von dort mitnimmt, woher man kommt, bleibt gegenwärtig, doch zurückhaltend. Sie erscheinen an Abayas und Objekten als erkennbare Signatur des Hauses — ein stiller Faden von Stück zu Stück, von einem Kapitel zum nächsten.',
  },
  nl: {
    'the-monogram': 'Het monogram rust op het idee van verbinding en terugkeer. Zijn vorm put uit ineengrijpende lijnen, weerspiegeling van continuïteit tussen verleden en heden. Het wordt met precisie toegepast op kleding, sieraden en objecten — stil detail of bepalend element. Als visuele handtekening verankert het elk stuk in de taal van het huis, terwijl het aanpasbaar blijft.',
    'al-talli': 'Al Talli is een erfgoedambacht in de Verenigde Arabische Emiraten, traditioneel handgeweven met katoenen en metalen draden. Het hoort bij de textieltradities van de regio, verbonden met technieken erkend op de Representatieve lijst van het immaterieel cultureel erfgoed van UNESCO. Historisch gebruikt om kleding te verfraaien, draagt het technische meesterschap en culturele betekenis. Bij Bint Saeed wordt dit ambacht herinterpreteerd via plaatsing, structuur en materiaal — in een hedendaagse garderobe, zonder de oorsprong te verlaten.',
    'khous': 'Al Khous is een traditioneel ambacht van de Verenigde Arabische Emiraten dat gedroogde palmbladeren gebruikt voor geweven vormen. Het behoort tot een breder veld van praktijken rond palmteelt en regionale ambachten, erkend binnen UNESCO-genoteerde culturele uitingen. Historisch aanwezig in alledaagse objecten, ligt zijn kracht in de structuur — verweven patronen die duurzaamheid en vorm scheppen. Bij Bint Saeed vertaalt deze logica zich in kledingconstructie en detail, waar lijnen, plooien en lagen dezelfde principes in een moderne context weerspiegelen.',
    'al-ain-rosette': '',
    'knotted-lines-of-lineage': 'Knotted Lines zijn een bepalend element van het huis. Elke lijn vormt zich in relatie tot een andere, knopen die verbinding weerspiegelen over tijd, ervaring en generatie. Wat is geërfd en wat is geleefd verstrengelen tot een doorlopende draad in plaats van aparte momenten.\n\nBij Bint Saeed nemen deze knopen de vorm van knopen op abayas en strands op kleding. De strands — vaak van natuursteen — worden zorgvuldig geplaatst, vaak op de schouder, waar ze de silhouet balanceren en dicht bij de draagster blijven.\n\nHun plaatsing is doordacht. Elke knoop herinnert aan het verhaal dat men draagt — gevormd door waar men vandaan komt en wat men doormaakt. Een onderling verbonden, persoonlijk en doorlopend verhaal — dat men herkent, waarin men staat, en dat men met trots voortzet.',
    'the-strands': 'The Strands behoren tot een langere lijn van versiering in de regio, waar draad, steen en gebaar al lang continuïteit over generaties markeren. Bij Bint Saeed wordt elke strand samengesteld uit natuurstenen gekozen op toon, korrel en proportie. Ze worden zorgvuldig geplaatst — meestal op de schouder — waar ze evenwicht brengen in de abaya zonder de lijn te verstoren.\n\nAls house code vertalen The Strands een abstract principe naar iets gedragen: wat men meedraagt van waar men vandaan komt blijft aanwezig, doch ingetogen. Ze verschijnen op abayas en objecten als herkenbare handtekening van het huis — een stille draad van stuk tot stuk, van het ene hoofdstuk naar het volgende.',
  },
  pt: {
    'the-monogram': 'O monograma assenta na ideia de ligação e regresso. A sua forma nasce de linhas entrelaçadas, reflexo de continuidade entre passado e presente. Aplica-se com precisão a peças, joalharia e objetos — detalhe discreto ou elemento definidor. Como assinatura visual ancora cada peça na linguagem da casa, mantendo-se adaptável.',
    'al-talli': 'Al Talli é um ofício patrimonial praticado nos Emirados Árabes Unidos, tradicionalmente tecido à mão com fios de algodão e metálicos. Integra as tradições têxteis da região, ligadas a técnicas reconhecidas na Lista representativa do património cultural imaterial da UNESCO. Historicamente usado para embelezar vestes, porta mestria técnica e sentido cultural. Na Bint Saeed este ofício é reinterpretado através da colocação, da estrutura e do material — num guarda-roupa contemporâneo, sem abandonar a origem.',
    'khous': 'Al Khous é um ofício tradicional dos Emirados Árabes Unidos que usa folhas de palmeira secas para criar formas tecidas. Pertence a um conjunto mais amplo de práticas ligadas ao cultivo da palmeira e aos ofícios da região, reconhecidas dentro de expressões culturais inscritas na UNESCO. Historicamente presente em objetos quotidianos, a sua força está na estrutura — padrões entrelaçados que criam durabilidade e forma. Na Bint Saeed esta lógica traduz-se na construção e no detalhe da peça, onde linhas, pregas e camadas reflectem os mesmos princípios num contexto moderno.',
    'al-ain-rosette': '',
    'knotted-lines-of-lineage': 'As Knotted Lines são um elemento definidor da casa. Cada linha forma-se em relação a outra, criando nós que reflectem ligação através do tempo, da experiência e da geração. O herdado e o vivido entrelaçam-se num fio contínuo em vez de momentos separados.\n\nNa Bint Saeed estes nós tomam forma de botões nas abayas e de strands nas peças. Os strands, muitas vezes de pedras naturais, são colocados com cuidado — frequentemente no ombro — onde equilibram a silhueta e permanecem próximos de quem os usa.\n\nA sua colocação é ponderada. Cada nó recorda a história que se carrega — moldada por de onde se vem e pelo que se atravessa. Uma história interligada, pessoal e contínua — que se reconhece, em que se está, e que se leva com orgulho.',
    'the-strands': 'The Strands pertencem a uma linhagem mais longa de adorno na região, onde fio, pedra e gesto há muito marcam a continuidade entre gerações. Na Bint Saeed cada strand é montado com pedras naturais escolhidas por tom, grão e proporção. São colocados com cuidado — mais frequentemente no ombro — onde introduzem equilíbrio à abaya sem perturbar a linha.\n\nComo código da casa, The Strands traduzem um princípio abstracto em algo vestido: o que se traz de onde se vem permanece presente, e no entanto contido. Aparecem em abayas e objetos como assinatura reconhecível da casa — um fio discreto que persiste de peça a peça, de um capítulo ao seguinte.',
  },
  ru: {
    'the-monogram': 'Монограмма строится на идее связи и возвращения. Её форма рождается из переплетённых линий — отражение непрерывности прошлого и настоящего. Она с точностью ложится на одежду, украшения и предметы — тихой деталью или определяющим элементом. Как визуальная подпись она закрепляет каждое изделие в языке дома, оставаясь при этом гибкой.',
    'al-talli': 'Al Talli — наследие ремесла в Объединённых Арабских Эмиратах, традиционно ткущееся вручную из хлопковых и металлических нитей. Оно входит в текстильные традиции региона, связанные с техниками из Репрезентативного списка нематериального культурного наследия ЮНЕСКО. Исторически украшая одежду, оно несёт техническое мастерство и культурный смысл. В Bint Saeed это ремесло переосмысляется через размещение, структуру и материал — в современном гардеробе, не оставляя своего истока.',
    'khous': 'Al Khous — традиционное ремесло ОАЭ, создающее плетёные формы из сухих пальмовых листьев. Оно принадлежит более широкому кругу практик, связанных с культурой пальмы и ремёслами региона, признанными в рамках выражений культуры, внесённых в списки ЮНЕСКО. Исторически присутствуя в повседневных предметах, его сила — в структуре: переплетённые узоры создают прочность и форму. В Bint Saeed эта логика переводится в крой и деталь одежды, где линии, складки и слои отражают те же принципы в современном контексте.',
    'al-ain-rosette': '',
    'knotted-lines-of-lineage': 'Knotted Lines — определяющий элемент дома. Каждая линия формируется относительно другой, связывая время, опыт и поколения. Унаследованное и прожитое сплетаются в непрерывную нить, а не в отдельные мгновения.\n\nВ Bint Saeed эти узлы становятся пуговицами на абаях и стрендами на одежде. Стренды — часто из натурального камня — размещаются тщательно, нередко на плече, где уравновешивают силуэт и остаются близко к носящей.\n\nИх размещение обдумано. Каждый узел напоминает о истории, которую несёшь, — сформированной тем, откуда ты, и тем, через что проходишь. История взаимосвязанная, личная и продолжающаяся — которую узнаёшь, в которой стоишь и которую несёшь с достоинством.',
    'the-strands': 'The Strands принадлежат более длинной линии украшения в регионе, где нить, камень и жест издавна отмечали непрерывность поколений. В Bint Saeed каждый стренд собирается из натуральных камней, выбранных по тону, зерну и пропорции. Их размещают тщательно — чаще всего на плече — внося равновесие в абаю, не нарушая её линии.\n\nКак код дома, The Strands переводят абстрактный принцип в носимое: то, что несёшь из того, откуда ты, остаётся присутствующим, но сдержанным. Они появляются на абаях и предметах как узнаваемая подпись дома — тихая нить от изделия к изделию, от одной главы истории к следующей.',
  },
  zh: {
    'the-monogram': '字母组合立基于连接与回归。其形态源于交织的线条，映照过去与现在的延续。它以精准施于衣裳、珠宝与器物——或为安静细节，或为界定元素。作为视觉签名，它将每件作品锚定于品牌语言，同时保持可延展性。',
    'al-talli': 'Al Talli 是阿联酋的传承工艺，传统上以棉线与金属线手工织就。它属于该地区更广泛的纺织传统，并与列入联合国教科文组织人类非物质文化遗产代表作名录的技艺相连。历史上用于装饰衣裳，承载技术精湛与文化意涵。在 Bint Saeed，这一工艺经由位置、结构与材质被重新诠释，得以存在于当代衣橱，而不离其本源。',
    'khous': 'Al Khous 是阿联酋的传统工艺，以干燥棕榈叶织成形态。它属于与棕榈种植及地区手工艺相关的更广传承实践，并在教科文组织所列文化表达中得到承认。历史上用于日常器物，其力量在于结构——交织纹样造就耐久与形态。在 Bint Saeed，这一逻辑转化为衣裳结构与细节，线条、褶皱与层叠在当代语境中反映同样原则。',
    'al-ain-rosette': '',
    'knotted-lines-of-lineage': 'Knotted Lines 是品牌的界定元素。每一线条相对于另一线条成形，结成跨越时间、经历与世代的联结。所继承与所经历交织为一条连续之线，而非分隔的瞬间。\n\n在 Bint Saeed，这些结以阿巴雅上的纽扣与衣裳上的挂链呈现。挂链——常以天然石制成——被审慎放置，多在肩部，在贴近穿着者的同时平衡轮廓。\n\n其位置经过考量。每一结提醒你所携带的故事——由你从何处来、经历何事所塑成。一个相互关联、个人而持续的故事——你辨认它、立于其中，并以骄傲向前携带。',
    'the-strands': 'The Strands 属于该地区更长的装饰谱系，线、石与姿态长久标记着世代的延续。在 Bint Saeed，每一挂链以天然石组装，按色调、纹理与比例遴选。它们被审慎安置——多在肩部——为阿巴雅引入均衡，而不扰乱其线条。\n\n作为品牌准则，The Strands 将抽象原则化为可佩之物：你从本源所携之物仍在，却克制。它们出现于阿巴雅与器物上，成为品牌可辨的签名——一条安静的线，从一件到另一件，从一个章节到下一章。',
  },
  id: {
    'the-monogram': 'Monogram dibangun di atas gagasan koneksi dan kembali. Bentuknya lahir dari garis yang saling mengunci, cerminan kesinambungan antara masa lalu dan kini. Diterapkan dengan presisi pada pakaian, perhiasan, dan objek — detail tenang atau elemen penentu. Sebagai tanda visual, ia menambatkan setiap karya dalam bahasa rumah, tetap adaptif.',
    'al-talli': 'Al Talli adalah kerajinan warisan di Uni Emirat Arab, secara tradisional ditenun tangan dengan benang kapas dan logam. Ia bagian dari tradisi tekstil wilayah, terkait teknik yang diakui dalam Daftar Representatif Warisan Budaya Takbenda UNESCO. Secara historis menghiasi pakaian, membawa penguasaan teknis dan makna budaya. Di Bint Saeed, kerajinan ini ditafsir ulang melalui penempatan, struktur, dan material — ada dalam lemari kontemporer tanpa meninggalkan asal.',
    'khous': 'Al Khous adalah kerajinan tradisional UEA yang memakai pelepah palem kering untuk membentuk anyaman. Ia termasuk praktik warisan yang lebih luas terkait budidaya palem dan kerajinan wilayah, diakui dalam ekspresi budaya terdaftar UNESCO. Secara historis hadir pada benda sehari-hari, kekuatannya pada struktur — pola saling jalin yang menciptakan daya tahan dan bentuk. Di Bint Saeed, logika ini diterjemahkan ke konstruksi dan detail pakaian, di mana garis, lipatan, dan lapisan mencerminkan prinsip yang sama dalam konteks modern.',
    'al-ain-rosette': '',
    'knotted-lines-of-lineage': 'Knotted Lines adalah elemen penentu rumah. Setiap garis dibentuk berelasi dengan yang lain, membentuk simpul yang mencerminkan koneksi lintas waktu, pengalaman, dan generasi. Yang diwarisi dan yang dijalani saling menjalin menjadi benang kontinu, bukan momen terpisah.\n\nDi Bint Saeed, simpul ini menjadi kancing pada abaya dan strand pada pakaian. Strand — sering dari batu alam — ditempatkan dengan cermat, sering di bahu, menyeimbangkan siluet sambil dekat dengan pemakainya.\n\nPenempatannya dipikirkan. Setiap simpul mengingatkan kisah yang dibawa — dibentuk oleh dari mana Anda datang dan apa yang dilalui. Kisah yang saling terhubung, personal, dan berkelanjutan — yang dikenali, di dalamnya Anda berdiri, dan dibawa dengan bangga.',
    'the-strands': 'The Strands termasuk garis panjang perhiasan di wilayah ini, di mana benang, batu, dan gestur telah lama menandai kesinambungan generasi. Di Bint Saeed, setiap strand dirakit dari batu alam yang dipilih untuk nada, butir, dan proporsi. Ditempatkan dengan cermat — paling sering di bahu — membawa keseimbangan pada abaya tanpa mengganggu garisnya.\n\nSebagai kode rumah, The Strands menerjemahkan prinsip abstrak menjadi sesuatu yang dikenakan: yang dibawa dari asal tetap hadir, namun tertahan. Mereka muncul pada abaya dan objek sebagai tanda rumah yang dikenali — benang tenang dari karya ke karya, dari satu bab kisah ke berikutnya.',
  },
  ms: {
    'the-monogram': 'Monogram dibina atas idea hubungan dan kembali. Bentuknya lahir daripada garisan saling berkunci, pantulan kesinambungan antara masa lalu dan kini. Digunakan dengan ketepatan pada pakaian, barang kemas dan objek — butiran tenang atau unsur penentu. Sebagai tandatangan visual, ia menambat setiap karya dalam bahasa rumah, kekal boleh disesuaikan.',
    'al-talli': 'Al Talli ialah kraf warisan di Emiriah Arab Bersatu, secara tradisional ditenun tangan dengan benang kapas dan logam. Ia sebahagian daripada tradisi tekstil rantau, berkait dengan teknik yang diiktiraf dalam Senarai Representatif Warisan Budaya Tidak Ketara UNESCO. Secara sejarah digunakan untuk menghias pakaian, membawa penguasaan teknikal dan makna budaya. Di Bint Saeed, kraf ini ditafsir semula melalui penempatan, struktur dan bahan — wujud dalam almari kontemporari tanpa meninggalkan asal.',
    'khous': 'Al Khous ialah kraf tradisional UAE yang menggunakan pelepah palma kering untuk mencipta bentuk anyaman. Ia tergolong dalam amalan warisan yang lebih luas berkaitan penanaman palma dan kraf rantau, diiktiraf dalam ekspresi budaya tersenarai UNESCO. Secara sejarah hadir pada objek harian, kekuatannya pada struktur — corak saling jalin yang mencipta ketahanan dan bentuk. Di Bint Saeed, logik ini diterjemahkan ke pembinaan dan butiran pakaian, di mana garisan, lipatan dan lapisan mencerminkan prinsip yang sama dalam konteks moden.',
    'al-ain-rosette': '',
    'knotted-lines-of-lineage': 'Knotted Lines ialah unsur penentu rumah. Setiap garisan dibentuk berhubung dengan yang lain, membentuk simpul yang mencerminkan hubungan merentas masa, pengalaman dan generasi. Yang diwarisi dan yang dijalani saling menjalin menjadi benang berterusan, bukan detik terpisah.\n\nDi Bint Saeed, simpul ini menjadi butang pada abaya dan strand pada pakaian. Strand — sering daripada batu semula jadi — diletakkan dengan teliti, sering di bahu, mengimbangi siluet sambil dekat dengan pemakainya.\n\nPenempatannya difikirkan. Setiap simpul mengingatkan kisah yang dibawa — dibentuk oleh dari mana anda datang dan apa yang dilalui. Kisah yang saling berkait, peribadi dan berterusan — yang dikenali, di dalamnya anda berdiri, dan dibawa dengan bangga.',
    'the-strands': 'The Strands tergolong dalam salasilah panjang hiasan di rantau ini, di mana benang, batu dan gerak isyarat telah lama menandai kesinambungan generasi. Di Bint Saeed, setiap strand dipasang daripada batu semula jadi yang dipilih untuk nada, butiran dan perkadaran. Diletakkan dengan teliti — paling kerap di bahu — membawa keseimbangan kepada abaya tanpa mengganggu garisnya.\n\nSebagai kod rumah, The Strands menterjemah prinsip abstrak menjadi sesuatu yang dipakai: yang dibawa dari asal kekal hadir, namun tertahan. Ia muncul pada abaya dan objek sebagai tandatangan rumah yang dikenali — benang tenang dari karya ke karya, dari satu bab kisah ke seterusnya.',
  },
}

export function getCodesExpandedText(
  locale: AppLocale | string,
): Record<CodesExpandedId, string> {
  const key = (locale in EXPANDED ? locale : 'en') as AppLocale
  return EXPANDED[key]
}
