/**
 * GCC-focused keyword bundles for regional discoverability (EN + AR).
 * Supplemental LocalBusiness / GCC FAQ JSON-LD copy lives in `lib/translations/seo/{locale}.ts`.
 */

/** GCC-specific keywords for regional discoverability (EN + AR). */
export const gccKeywords = {
  'uae-abu-dhabi': [
    'luxury abaya house abu dhabi',
    'designer abayas abu dhabi',
    'bint saeed abu dhabi',
    'luxury abaya brand abu dhabi',
    'heritage abaya abu dhabi',
    'emirati abaya brand abu dhabi',
    'al talli abaya abu dhabi',
    'luxury modest fashion abu dhabi',
    'dar abaya abu dhabi',
    'عبايات فاخرة أبوظبي',
    'دار عبايات أبوظبي',
    'بنت سعيد أبوظبي',
    'عبايات مصممة أبوظبي',
    'أزياء محتشمة فاخرة أبوظبي',
    'عباية تراث إماراتي أبوظبي',
  ],
  'uae-dubai': [
    'luxury abayas dubai',
    'designer abayas dubai',
    'bint saeed dubai',
    'luxury abaya brand dubai',
    'heritage abaya dubai',
    'emirati heritage abaya dubai',
    'luxury modest fashion dubai',
    'black abaya dubai',
    'silk abaya dubai',
    'عبايات فاخرة دبي',
    'عبايات مصممة دبي',
    'بنت سعيد دبي',
    'دار عبايات فاخرة دبي',
    'أزياء محتشمة فاخرة دبي',
    'عباية حرير دبي',
  ],
  'uae': [
    'luxury abaya house uae',
    'designer abayas uae',
    'bint saeed uae',
    'luxury abaya brand uae',
    'heritage abaya uae',
    'emirati abaya brand uae',
    'luxury modest fashion uae',
    'gcc luxury abayas',
    'عبايات فاخرة الإمارات',
    'دار عبايات الإمارات',
    'بنت سعيد الإمارات',
    'عبايات مصممة الإمارات',
    'أزياء محتشمة فاخرة الإمارات',
    'ماركة عباية إماراتية فاخرة',
  ],
  'qatar-doha': [
    'luxury abayas qatar',
    'luxury abayas doha',
    'designer abayas qatar',
    'bint saeed qatar',
    'luxury abaya brand doha',
    'emirati heritage abaya qatar',
    'luxury modest fashion qatar',
    'gcc abaya delivery qatar',
    'عبايات فاخرة قطر',
    'عبايات فاخرة الدوحة',
    'بنت سعيد قطر',
    'دار عبايات فاخرة الدوحة',
    'أزياء محتشمة فاخرة قطر',
    'عباية تراث خليجي قطر',
  ],
  'saudi': [
    'luxury abayas saudi arabia',
    'luxury abayas ksa',
    'designer abayas saudi',
    'bint saeed saudi arabia',
    'luxury abaya brand saudi',
    'heritage abaya saudi',
    'luxury modest fashion saudi',
    'gcc luxury abayas saudi',
    'عبايات فاخرة السعودية',
    'عبايات فاخرة المملكة',
    'بنت سعيد السعودية',
    'دار عبايات فاخرة السعودية',
    'أزياء محتشمة فاخرة السعودية',
    'عبايات مصممة السعودية',
  ],
  'saudi-riyadh': [
    'luxury abayas riyadh',
    'designer abayas riyadh',
    'bint saeed riyadh',
    'luxury abaya brand riyadh',
    'luxury modest fashion riyadh',
    'gcc abaya delivery riyadh',
    'عبايات فاخرة الرياض',
    'بنت سعيد الرياض',
    'دار عبايات الرياض',
    'أزياء محتشمة فاخرة الرياض',
    'عبايات مصممة الرياض',
  ],
  'saudi-jeddah': [
    'luxury abayas jeddah',
    'designer abayas jeddah',
    'bint saeed jeddah',
    'luxury abaya brand jeddah',
    'luxury modest fashion jeddah',
    'gcc abaya delivery jeddah',
    'عبايات فاخرة جدة',
    'بنت سعيد جدة',
    'دار عبايات جدة',
    'أزياء محتشمة فاخرة جدة',
    'عبايات مصممة جدة',
  ],
} as const
