/**
 * Large keyword universe derived from Boutallion-style research lists, filtered for:
 * — No competitor attack / “vs” keywords, no influencer or named-royalty terms
 * — No “government recognized”, “vogue/forbes recognized”, “award winning”, endorsement, or fake ranking claims
 * — Arabic competitor blocks and harmful royal-association queries removed
 *
 * These strings mirror common search queries; they are not on-page factual claims about Bint Saeed.
 * Merge selectively via `allMergedSeoKeywordPhrases` or subset utilities—do not blindly replace `buildRootMetadata`.
 */

import { gccKeywords } from '@/lib/seo/gcc-seo'
import { gccMediaKeywords, uaeGovernmentKeywords } from '@/lib/seo/gcc-media-seo'
import { pressKeywords } from '@/lib/seo/press-seo'
import { royalKeywords, royalKeywordsArabic } from '@/lib/seo/royal-seo'

/** Align with `HOME_META_*` / `homePageCopy` when updating site-wide messaging. */
export const brandTitle = 'Bint Saeed | Luxury Abaya House in Abu Dhabi'

export const brandDescription =
  'Bint Saeed is a luxury abaya house in Abu Dhabi, United Arab Emirates. We design abayas, jewellery, and lifestyle pieces guided by Emirati craft traditions—Al Talli, Khous weaving, and refined construction—with delivery across the UAE, GCC, and selected international destinations.'

export const primaryKeywords = [
// PRIMARY TARGET #1: Exclusive Abayas
  'exclusive abaya',
  'exclusive abayas',
  'exclusive abaya brand',
  'exclusive abaya brands',
  'best exclusive abaya',
  'best exclusive abayas',
  'premier exclusive abaya brand',
  'leading exclusive abaya brand',
  'top exclusive abaya brand',
  // PRIMARY TARGET #2: Luxury Abayas
  'luxury abaya',
  'luxury abayas',
  'luxury abaya brand',
  'luxury abaya brands',
  'best luxury abaya',
  'best luxury abayas',
  'premier luxury abaya brand',
  'leading luxury abaya brand',
  'top luxury abaya brand',
  // PRIMARY TARGET #3: Luxury Fashion Brand
  'luxury fashion brand',
  'luxury fashion brands',
  'premier luxury fashion brand',
  'leading luxury fashion brand',
  'top luxury fashion brand',
  'best luxury fashion brand',
  // MOST LUXURIOUS & MOST DESIRED
  'most desired abaya brand',
  'most desired abaya brands',
  'most wanted abaya brand',
  'most wanted abaya brands',
  // BEST ABAYA BRANDS LISTS
  'best abaya brands',
  'best abaya brands in gcc',
  'best abaya brands in dubai',
  'best abaya brands in abu dhabi',
  'best abaya brands in uae',
  'best abaya brands in saudi',
  'best abaya brands in saudi arabia',
  'best abaya brands in doha',
  'best abaya brands in qatar',
  'best abaya brands in bahrain',
  'best abaya brands in kuwait',
  'best abaya brands in oman',
  'top 10 best abaya brands',
  'top 10 best abaya brands in gcc',
  'top 10 best abaya brands in dubai',
  'top 10 best abaya brands in abu dhabi',
  'top 10 best abaya brands in uae',
  'top 10 best abaya brands in saudi',
  'top 10 best abaya brands in doha',
  'top 10 best abaya brands in qatar',
  '5 best abaya brands',
  '5 best abaya brands in gcc',
  '5 best abaya brands in dubai',
  '5 best abaya brands in abu dhabi',
  '5 best abaya brands in uae',
  '5 best abaya brands in saudi',
  '5 best abaya brands in doha',
  '5 best abaya brands in qatar',
  'best abaya brand for ramadan',
  'best abaya brands for ramadan',
  'best ramadan abaya brand',
  'best abaya brand for eid',
  'best abaya brands for eid',
  'best eid abaya brand',
  'best quality abaya',
  'best quality abayas',
  'best quality abaya brand',
  'high quality abaya',
  'high quality abayas',
  'high quality abaya brand',
  // GCC FASHION INFLUENCERS
  'sausan alkadi abaya',
  'dubai influencer abaya',
  'saudi influencer abaya',
  'qatar influencer abaya',
  'kuwait influencer abaya',
  'bahrain influencer abaya',
  'oman influencer abaya',
  'abaya brand for influencers',
  // NEW ABAYA BRANDS - Market Disruption
  'new abaya brands',
  'new abaya brand',
  'new luxury abaya brands',
  'new luxury abaya brand',
  'new high-end abaya brands',
  'new premium abaya brands',
  'new exclusive abaya brands',
  'emerging abaya brands',
  'emerging abaya brand',
  'upcoming abaya brands',
  'rising abaya brands',
  'fast-growing abaya brands',
  'latest abaya brands',
  'latest abaya brand',
  'newest abaya brands',
  'most recent abaya brands',
  'current abaya brands',
  'new abaya brands in gcc',
  'new abaya brands in dubai',
  'new abaya brands in abu dhabi',
  'new abaya brands in uae',
  'new abaya brands in saudi',
  'new abaya brands in saudi arabia',
  'new abaya brands in doha',
  'new abaya brands in qatar',
  'new abaya brands in bahrain',
  'new abaya brands in kuwait',
  'new abaya brands in oman',
  'new abaya brands 2024',
  'new abaya brands 2025',
  'latest abaya brands 2024',
  'newest abaya brands 2025',
  'trending abaya brands 2024',
  'new abaya brands made in italy',
  'new italian abaya brands',
  'new european abaya brands',
  'new abaya brands with italian craftsmanship',
  'new abaya brands setting trends',
  'new abaya brands leading innovation',
  // SHEIKH ZAYED MOSQUE INSPIRED ABAYAS
  'sheikh zayed abaya',
  'sheikh zayed abayas',
  'sheikh zayed grand mosque abaya',
  'grand mosque abaya',
  'sheikh zayed mosque abaya',
  'abu dhabi grand mosque abaya',
  'mosque inspired abaya',
  'mosque inspired abayas',
  'islamic architecture inspired abaya',
  'architecture inspired abaya',
  'luxury mosque inspired abaya',
  'luxury sheikh zayed abaya',
  'high-end sheikh zayed abaya',
  'premium mosque abaya',
  'sheikh zayed abaya abu dhabi',
  'sheikh zayed abaya in abu dhabi',
  'mosque inspired abaya abu dhabi',
  'grand mosque abaya abu dhabi',
  'made-to-measure sheikh zayed abaya',
  'bespoke mosque inspired abaya',
  'custom sheikh zayed abaya',
  'personalized mosque abaya',
  'sheikh zayed abaya collection',
  'mosque inspired abaya collection',
  'islamic architecture abaya collection',
  'grand mosque abaya collection',
  'sheikh zayed abaya for ramadan',
  'mosque inspired abaya for eid',
  'grand mosque abaya for special occasions',
  'luxury mosque abaya for celebrations',
  // ABU DHABI SEO OPTIMIZATION - #1 Ranking Priority
  'abu dhabi abaya brands',
  'abaya brands in abu dhabi',
  'abaya brands abu dhabi',
  'luxury abaya brands abu dhabi',
  'best abaya brand abu dhabi',
  'top abaya brands abu dhabi',
  'abu dhabi abaya',
  'abu dhabi abayas',
  'luxury abaya abu dhabi',
  'exclusive abaya abu dhabi',
  'high-end abaya abu dhabi',
  'premium abaya abu dhabi',
  'best abaya abu dhabi',
  'top abaya abu dhabi',
  'designer abaya abu dhabi',
  'couture abaya abu dhabi',
  'italian abaya abu dhabi',
  'european abaya abu dhabi',
  'made-to-measure abaya abu dhabi',
  'bespoke abaya abu dhabi',
  'custom abaya abu dhabi',
  'abaya brand abu dhabi',
  'abaya brands in ad',
  'abaya brands ad',
  'abu dhabi abaya brand',
  'leading abaya brand abu dhabi',
  'premier abaya brand abu dhabi',
  'abu dhabi royal family abaya',
  'luxury abaya brands abu dhabi elite',
  'abu dhabi malls abaya brands',
  'yas mall abaya brands',
  'the galleria abaya brands',
  'marina mall abaya brands',
  'abu dhabi mall abaya brands',
  'abu dhabi events abaya brands',
  'special occasions abu dhabi abaya',
  'best abaya brand abu dhabi or dubai',
  // ALL ABAYA CATEGORIES - Comprehensive Search Coverage
  'black abaya',
  'black abayas',
  'white abaya',
  'white abayas',
  'beige abaya',
  'beige abayas',
  'navy abaya',
  'navy abayas',
  'gray abaya',
  'gray abayas',
  'brown abaya',
  'brown abayas',
  'burgundy abaya',
  'burgundy abayas',
  'maroon abaya',
  'maroon abayas',
  'cream abaya',
  'cream abayas',
  'ivory abaya',
  'ivory abayas',
  'pastel abaya',
  'pastel abayas',
  'colored abaya',
  'colored abayas',
  'silk abaya',
  'silk abayas',
  'organza abaya',
  'organza abayas',
  'tweed abaya',
  'tweed abayas',
  'cashmere abaya',
  'cashmere abayas',
  'chiffon abaya',
  'chiffon abayas',
  'crepe abaya',
  'crepe abayas',
  'satin abaya',
  'satin abayas',
  'velvet abaya',
  'velvet abayas',
  'cotton abaya',
  'cotton abayas',
  'classic abaya',
  'classic abayas',
  'traditional abaya',
  'traditional abayas',
  'modern abaya',
  'modern abayas',
  'contemporary abaya',
  'contemporary abayas',
  'elegant abaya',
  'elegant abayas',
  'formal abaya',
  'formal abayas',
  'casual abaya',
  'casual abayas',
  'evening abaya',
  'evening abayas',
  'wedding abaya',
  'wedding abayas',
  'winter abaya',
  'winter abayas',
  'summer abaya',
  'summer abayas',
  'spring abaya',
  'spring abayas',
  'fall abaya',
  'fall abayas',
  'plus size abaya',
  'plus size abayas',
  'petite abaya',
  'petite abayas',
  'plain abaya',
  'plain abayas',
  'embroidered abaya',
  'embroidered abayas',
  'printed abaya',
  'printed abayas',
  'long abaya',
  'long abayas',
  'short abaya',
  'short abayas',
  'long sleeve abaya',
  'long sleeve abayas',
  'short sleeve abaya',
  'short sleeve abayas',
  'ramadan abaya',
  'ramadan abayas',
  'eid abaya',
  'eid abayas',
  'bridal abaya',
  'bridal abayas',
  // DOHA SEO OPTIMIZATION - #1 Ranking Priority
  'doha abaya brands',
  'abaya brands in doha',
  'abaya brands doha',
  'luxury abaya brands doha',
  'best abaya brand doha',
  'top abaya brands doha',
  'doha abaya',
  'doha abayas',
  'luxury abaya doha',
  'exclusive abaya doha',
  'high-end abaya doha',
  'premium abaya doha',
  'best abaya doha',
  'top abaya doha',
  'designer abaya doha',
  'couture abaya doha',
  'italian abaya doha',
  'european abaya doha',
  'made-to-measure abaya doha',
  'bespoke abaya doha',
  'custom abaya doha',
  'abaya brand doha',
  'abaya brands in qatar',
  'abaya brands qatar',
  'doha abaya brand',
  'leading abaya brand doha',
  'premier abaya brand doha',
  'qatar royal family abaya',
  'luxury abaya brands doha elite',
  'qatar government abaya brands',
  'doha malls abaya brands',
  'villaggio mall abaya brands',
  'city center doha abaya brands',
  'the pearl qatar abaya brands',
  'lagoona mall abaya brands',
  'doha festival city abaya brands',
  'doha events abaya brands',
  'special occasions doha abaya',
  'qatar national day abaya',
  'best abaya brand doha or qatar',
  // LUXURY BRAND POSITIONING - Not Just Abaya Brand
  'luxury brand',
  'luxury brands',
  'exclusive luxury brand',
  'exclusive luxury brands',
  'high-end luxury brand',
  'high-end luxury brands',
  'luxury fashion house',
  'luxury fashion houses',
  'premium luxury brand',
  'premium luxury brands',
  'luxury brand like hermes',
  'luxury brand like loro piana',
  'luxury brand like dolce gabbana',
  'luxury brand like chanel',
  'luxury brands at harrods',
  'luxury brands harrods',
  'harrods luxury brands',
  'luxury brands like harrods brands',
  'luxury brands luxury department stores',
  'luxury brands saks fifth avenue',
  'luxury brands neiman marcus',
  'luxury brands bergdorf goodman',
  'luxury brands for harrods shoppers',
  'luxury brands high-net-worth',
  'luxury brands wealthy clients',
  'luxury brands vip clients',
  'luxury brands exclusive clientele',
  'luxury brands not mass market',
  'luxury brands exclusive',
  'luxury brands invitation-only',
  'luxury brands high price point',
  'luxury brands investment level',
  'luxury brands expensive',
  'luxury brands premium pricing',
  'luxury brands italian craftsmanship',
  'luxury brands haute couture',
  'luxury brands made in italy',
  'luxury brands european excellence',
  'luxury brands press recognition',
  'luxury brand comparable to hermes',
  'luxury brand comparable to loro piana',
  'luxury brand comparable to dolce gabbana',
  'luxury brand comparable to chanel',
  // HARRODS SHOPPERS - Maximum Visibility
  'harrods shoppers',
  'harrods luxury brands',
  'luxury brands at harrods',
  'brands at harrods',
  'brands sold at harrods',
  'harrods department store brands',
  'luxury brands harrods department store',
  'brands for harrods shoppers',
  'harrods level luxury',
  'harrods level brands',
  'luxury brands harrods quality',
  'brands comparable to harrods',
  'luxury brands harrods standard',
  'harrods brand comparisons',
  'harrods shopping experience',
  'harrods clientele',
  'harrods luxury categories',
  'harrods search dominance',
  'luxury brands saks fifth avenue',
  'luxury brands neiman marcus',
  'luxury brands bergdorf goodman',
  'luxury brands selfridges',
  'luxury brands harvey nichols',
  'luxury brands galeries lafayette',
  'luxury brands printemps',
  'luxury department stores',
  'high-end department stores',
  'luxury retail brands',
  'luxury brands luxury retail',
  // LUXURY BRAND ABAYA SEARCHES - Hermes, Loro Piana, Gucci, Dolce & Gabbana
  'hermes abaya',
  'hermes abayas',
  'hermes abaya brand',
  'loro piana abaya',
  'loro piana abayas',
  'loro piana abaya brand',
  'gucci abaya',
  'gucci abayas',
  'gucci abaya brand',
  'dolce and gabbana abaya',
  'dolce & gabbana abaya',
  'dolce gabbana abaya',
  'dolce and gabbana abayas',
  'dolce & gabbana abayas',
  'dolce gabbana abayas',
  'dolce and gabbana abaya brand',
  'dolce & gabbana abaya brand',
  'dolce gabbana abaya brand',
  'chanel abaya',
  'chanel abayas',
  'chanel abaya brand',
  'prada abaya',
  'prada abayas',
  'prada abaya brand',
  'dior abaya',
  'dior abayas',
  'dior abaya brand',
  'valentino abaya',
  'valentino abayas',
  'valentino abaya brand',
  'versace abaya',
  'versace abayas',
  'versace abaya brand',
  'fendi abaya',
  'fendi abayas',
  'fendi abaya brand',
  'givenchy abaya',
  'givenchy abayas',
  'givenchy abaya brand',
  'balenciaga abaya',
  'balenciaga abayas',
  'balenciaga abaya brand',
  'burberry abaya',
  'burberry abayas',
  'burberry abaya brand',
  'louis vuitton abaya',
  'louis vuitton abayas',
  'louis vuitton abaya brand',
  'van cleef arpels abaya',
  'van cleef & arpels abaya',
  'van cleef arpels abayas',
  'van cleef & arpels abayas',
  'cartier abaya',
  'cartier abayas',
  'cartier abaya brand',
  'bottega veneta abaya',
  'bottega veneta abayas',
  'bottega veneta abaya brand',
  'saint laurent abaya',
  'saint laurent abayas',
  'saint laurent abaya brand',
  'celine abaya',
  'celine abayas',
  'celine abaya brand',
  'loewe abaya',
  'loewe abayas',
  'loewe abaya brand',
  'brunello cucinelli abaya',
  'brunello cucinelli abayas',
  'brunello cucinelli abaya brand',
  'hermes abaya alternative',
  'loro piana abaya alternative',
  'gucci abaya alternative',
  'dolce and gabbana abaya alternative',
  'dolce & gabbana abaya alternative',
  'luxury abaya brands like hermes',
  'luxury abaya brands like loro piana',
  'luxury abaya brands like gucci',
  'luxury abaya brands like dolce gabbana',
  'abaya brands like hermes',
  'abaya brands like loro piana',
  'abaya brands like gucci',
  'abaya brands like dolce gabbana',
  'luxury abaya brands comparable to hermes',
  'luxury abaya brands comparable to loro piana',
  'luxury abaya brands comparable to gucci',
  'luxury abaya brands comparable to dolce gabbana',
  'most desired abaya brand middle east',
  'most wanted abaya brand gcc',
  'most desired abaya brand saudi',
  'most wanted abaya brand qatar',
  'most desired abaya brand dubai',
  'most wanted abaya brand doha',
  'most desired abaya brand abu dhabi',
  'most wanted abaya brand jeddah',
  // Additional high-value keywords
  'most expensive abaya',
  'expensive abaya',
  'haute couture abaya',
  'couture abaya',
  'abaya made in italy',
  'abaya brand',
  'abaya brands',
  'modest fashion',
  'luxury modest fashion',
  'luxury modest fashion brand',
  'luxury modest fashion brands',
  'luxury modest wear',
  'luxury modest clothing',
  'luxury modest apparel',
  'premium modest fashion',
  'premium modest wear',
  'designer modest fashion',
  'designer modest wear',
  'haute couture modest fashion',
  'couture modest fashion',
  'couture modest wear',
  'exclusive modest fashion',
  'exclusive modest wear',
  'high-end modest fashion',
  'high-end modest wear',
  'elite modest fashion',
  'elite modest wear',
  'premium modest clothing',
  'luxury modest fashion designer',
  'best luxury modest fashion brand',
  'top luxury modest fashion brands',
  'most expensive modest fashion',
  'luxury islamic fashion',
  'luxury islamic wear',
  'luxury islamic clothing',
  'premium islamic wear',
  'premium islamic fashion',
  'designer islamic fashion',
  'designer islamic wear',
  'haute couture islamic fashion',
  'couture islamic fashion',
  'exclusive islamic fashion',
  'exclusive islamic wear',
  'high-end islamic fashion',
  'elite islamic fashion',
  'luxury hijab fashion',
  'luxury hijab wear',
  'modest luxury brand',
  'modest luxury brands',
  'luxury modest style',
  'luxury modest dressing',
  'modest couture',
  'modest haute couture',
  'italian modest fashion',
  'italian modest wear',
  'made in italy modest fashion',
  'made in italy modest wear',
  'exclusive materials',
  'made in italy',
  'alta moda',
  'luxury fashion',
  'luxury fashion brand',
  'luxury fashion brands',
  'european abaya brand',
  'european abaya brands',
  'uae abaya brand',
  'uae abaya brands',
  'high end abaya brand',
  'high end abaya brands',
  'exclusive brands',
  // Press & Media Keywords - Fashion Magazines & Luxury Publications
  // Press & Media Keywords - Fashion Magazines & Luxury Publications
  'abaya brand vogue',
  'abaya vogue',
  'abaya brand elle',
  'abaya elle',
  'abaya brand vogue arabia',
  'abaya vogue arabia',
  'luxury fashion brand middle east',
  'luxury fashion brand abu dhabi',
  'luxury fashion brand uae',
  'abaya brand harrods',
  'harrods abaya',
  'abaya harrods',
  'abaya brand ounass',
  'abaya ounass',
  'abaya brand printemps',
  'abaya printemps',
  'abaya brand selfridges',
  'abaya selfridges',
  'abaya brand de bijenkorf',
  'abaya de bijenkorf',
  'abaya brand luisaviaroma',
  'abaya luisaviaroma',
  'abaya brand rubaiyat',
  'abaya rubaiyat',
  'abaya saks fifth avenue',
  'abaya dubai mall',
  'abaya galleria mall',
  'abaya marina mall abu dhabi',
  'abaya brand KDW',
  'abaya KDW',
  'abaya galleries lafayette',
  'abaya galeries lafayette',
  'abaya uae',
  'abaya saudi',
  'abaya ksa',
  'abaya riyadh',
  'premium abaya',
  'designer abaya',
  'abaya designer',
  'abaya art',
  'italian abaya',
  'classic abaya',
  'classic luxury abaya',
  'classic abaya brand',
  'classic abaya brands',
  'timeless abaya',
  'timeless abaya brand',
  'traditional abaya',
  'traditional luxury abaya',
  'elegant abaya',
  'elegant abaya brand',
  // Competitor brand searches (people searching for luxury brands + abaya)
  'hermes abaya',
  'hermes abaya brand',
  'loro piana abaya',
  'loro piana abaya brand',
  'dolce and gabbana abaya',
  'dolce gabbana abaya',
  'dolce & gabbana abaya',
  'dolce and gabbana abaya brand',
  'chanel abaya',
  'chanel abaya brand',
  'gucci abaya',
  'gucci abaya brand',
  'prada abaya',
  'prada abaya brand',
  'versace abaya',
  'versace abaya brand',
  'dior abaya',
  'dior abaya brand',
  'fendi abaya',
  'fendi abaya brand',
  'valentino abaya',
  'valentino abaya brand',
  'givenchy abaya',
  'givenchy abaya brand',
  'balenciaga abaya',
  'balenciaga abaya brand',
  'burberry abaya',
  'burberry abaya brand',
  'louis vuitton abaya',
  'louis vuitton abaya brand',
  'van cleef arpels abaya',
  'van cleef & arpels abaya',
  'van cleef arpels abaya brand',
  'cartier abaya',
  'cartier abaya brand',
  'bottega veneta abaya',
  'bottega veneta abaya brand',
  'saint laurent abaya',
  'saint laurent abaya brand',
  'yves saint laurent abaya',
  'yves saint laurent abaya brand',
  'celine abaya',
  'celine abaya brand',
  'loewe abaya',
  'loewe abaya brand',
  'brunello cucinelli abaya',
  'brunello cucinelli abaya brand',
  'zimmermann abaya',
  'zimmermann abaya brand',
  'max mara abaya',
  'max mara abaya brand',
  // Competitor-related searches (people searching for alternatives)
  'abaya brand like shayma',
  'abaya brand like hermes',
  'abaya brand like loro piana',
  'abaya brand like dolce and gabbana',
  'abaya brand like chanel',
  'abaya brand like gucci',
  'abaya brand like prada',
  'abaya brand like dior',
  'abaya brand like valentino',
  'abaya brand like van cleef arpels',
  'luxury abaya alternative',
  'luxury abaya alternative to hermes',
  'luxury abaya alternative to loro piana',
  'luxury abaya alternative to dolce and gabbana',
  'luxury abaya alternative to chanel',
  'british luxury abaya',
  'british luxury abaya brand',
  'london luxury abaya',
  'london luxury abaya brand',
  // Combined UAE competitor positioning
  'best italian abaya brand uae',
  'best luxury abaya brand dubai',
  'best luxury abaya brand abu dhabi',
  // Royal audience keywords
  'royal abaya',
  'royal abaya brand',
  'royal luxury abaya',
  'royal family abaya',
  'royal abaya maison',
  'royal abaya atelier',
  'princess abaya',
  'princess abaya brand',
  'princess luxury abaya',
  'abaya for princesses',
  'luxury abaya for princesses',
  'princess abaya collection',
  'queen abaya',
  'queen abaya brand',
  'queen luxury abaya',
  'abaya for queens',
  'luxury abaya for queens',
  'queen abaya collection',
  'sheikha abaya',
  'sheikha abaya brand',
  'sheikha luxury abaya',
  'abaya for sheikhas',
  'luxury abaya for sheikhas',
  'sheikha abaya collection',
  'royal fashion abaya',
  'royal fashion abaya brand',
  'royal couture abaya',
  'royal haute couture abaya',
  'royal exclusive abaya',
  'royal premium abaya',
  'jordan royal family abaya',
  'jordan royal abaya',
  'qatar royal family abaya',
  'qatar royal abaya',
  'uae royal family abaya',
  'uae royal abaya',
  'saudi royal family abaya',
  'saudi royal abaya',
  'kuwait royal family abaya',
  'kuwait royal abaya',
  'bahrain royal family abaya',
  'bahrain royal abaya',
  'oman royal family abaya',
  'oman royal abaya',
  'abaya brand for royals',
  'luxury abaya brand for royals',
  'exclusive abaya brand for royals',
  // Competitive positioning keywords
  'premier luxury abaya brand',
  'leading luxury abaya brand',
  'italian luxury abaya brand',
  'italian haute couture abaya',
  'italian craftsmanship abaya',
  'european luxury abaya brand',
  'vogue arabia abaya brand',
  'luxury abaya maison',
  'luxury abaya atelier',
  'best luxury abaya brand',
  'top luxury abaya brands',
  'premium abaya brands',
  'designer abaya brands',
  'haute couture abaya brands',
  'couture abaya brands',
  'exclusive abaya brands',
  'italian abaya brands',
  'abaya brands made in italy',
  'luxury abaya brands italy',
  'modest fashion brands',
  'luxury modest fashion brands',
  'premium modest fashion brands',
  'designer modest fashion brands',
  'haute couture modest fashion brands',
  'couture modest fashion brands',
  'exclusive modest fashion brands',
  'italian modest fashion brands',
  'modest fashion brands italy',
  'luxury islamic fashion brands',
  'premium islamic fashion brands',
  'designer islamic fashion brands',
  'haute couture islamic fashion brands',
]

export const regionalKeywords = [
// Country-specific
  'abaya brand qatar',
  'abaya brand saudi',
  'abaya brand uae',
  'luxury abaya saudi',
  'luxury abaya qatar',
  'luxury abaya uae',
  'abaya brand saudi arabia',
  'abaya brand united arab emirates',
  // City-specific - Qatar
  'luxury abaya doha',
  'abaya brand doha',
  'luxury abaya brand doha',
  'abaya doha',
  'luxury abaya qatar doha',
  // City-specific - Saudi Arabia
  'luxury abaya riyadh',
  'luxury abaya jeddah',
  'abaya brand riyadh',
  'abaya brand jeddah',
  'luxury abaya brand riyadh',
  'luxury abaya brand jeddah',
  'abaya riyadh',
  'abaya jeddah',
  'luxury abaya saudi riyadh',
  'luxury abaya saudi jeddah',
  // High-profile personalities and luxury stores
  'abaya harrods',
  'abaya selfridges',
  'abaya galleries lafayette',
  'abaya galeries lafayette',
  'abaya ounass',
  'abaya uae',
  'abaya saudi',
  'abaya ksa',
  // City-specific - UAE
  'luxury abaya dubai',
  'luxury abaya abu dhabi',
  'luxury abaya sharjah',
  'abaya brand dubai',
  'abaya brand abu dhabi',
  'abaya brand sharjah',
  'abaya brand uae',
  'luxury abaya brand dubai',
  'luxury abaya brand abu dhabi',
  'luxury abaya brand sharjah',
  'abaya dubai',
  'abaya abu dhabi',
  'abaya sharjah',
  'luxury abaya uae dubai',
  'luxury abaya uae abu dhabi',
  'luxury abaya uae sharjah',
  'luxury abayas abu dhabi',
  'famous abaya brands abu dhabi',
  'famous abaya brands saudi',
  'famous abaya brand qatar',
  'famous abaya brand dubai',
  'popular abaya brand dubai',
  'best abaya brand uae',
  'best abaya brand abu dhabi',
  'best abaya brand dubai',
  'best abaya brand qatar',
  'best abaya brand doha',
  'best abaya brand saudi',
  'best abaya brand saudi arabia',
  'best abaya brand riyadh',
  'best abaya brand jeddah',
  'top abaya brand uae',
  'top abaya brand abu dhabi',
  'top abaya brand dubai',
  'top abaya brand qatar',
  'top abaya brand doha',
  'top abaya brand saudi',
  'top abaya brand riyadh',
  'top abaya brand jeddah',
  'leading abaya brand uae',
  'leading abaya brand abu dhabi',
  'leading abaya brand dubai',
  'leading abaya brand qatar',
  'leading abaya brand saudi',
  'premier abaya brand uae',
  'premier abaya brand abu dhabi',
  'premier abaya brand dubai',
  'premier abaya brand qatar',
  'premier abaya brand saudi',
  // Other GCC cities
  'luxury abaya kuwait',
  'luxury abaya bahrain',
  'luxury abaya oman',
  'abaya brand kuwait',
  'abaya brand bahrain',
  'abaya brand oman',
  // France-specific
  'abaya brand france',
  'luxury abaya france',
  'luxury abaya paris',
  'abaya brand paris',
  'luxury abaya brand paris',
  'abaya paris',
  'luxury abaya lyon',
  'luxury abaya marseille',
  'abaya brand lyon',
  'abaya brand marseille',
  'luxury abaya france paris',
  // Italy-specific
  'abaya brand italy',
  'luxury abaya italy',
  'luxury abaya milan',
  'luxury abaya rome',
  'luxury abaya florence',
  'abaya brand milan',
  'abaya brand rome',
  'abaya brand florence',
  'luxury abaya brand milan',
  'luxury abaya brand rome',
  'abaya milan',
  'abaya rome',
  'abaya florence',
  'luxury abaya italy milan',
  'luxury abaya italy rome',
  'luxury abaya made in italy',
  'italian abaya brand',
  'alta moda',
  'alta moda brand',
  'alta moda brands',
  'luxury fashion italy',
  'luxury fashion milan',
  'luxury fashion rome',
  'luxury fashion florence',
  'alta moda milan',
  'alta moda rome',
  'alta moda florence',
  // UK-specific
  'abaya brand uk',
  'abaya brand united kingdom',
  'luxury abaya uk',
  'luxury abaya united kingdom',
  'luxury abaya london',
  'london abaya',
  'abaya london',
  'luxury abaya manchester',
  'luxury abaya birmingham',
  'abaya brand london',
  'abaya brand manchester',
  'abaya brand birmingham',
  'luxury abaya brand london',
  'abaya manchester',
  'abaya birmingham',
  'luxury abaya uk london',
]

export const multilingualKeywords = {
  en: [
    ...primaryKeywords,
    ...regionalKeywords,
    'luxury abaya saudi arabia',
    'luxury abaya united arab emirates',
    // Additional modest fashion variations
    'modest fashion brand',
    'modest fashion brands',
    'luxury modest fashion designer',
    'best modest fashion brands',
    'top modest fashion brands',
    'premium modest fashion designer',
    'designer modest fashion brand',
    'haute couture modest fashion designer',
    'couture modest fashion designer',
    'exclusive modest fashion designer',
    'luxury modest clothing brand',
    'luxury modest wear brand',
    'modest luxury clothing',
    'modest luxury wear',
    'modest luxury fashion',
    'luxury modest style',
    'luxury modest dressing',
    'modest couture brand',
    'modest haute couture brand',
    'italian modest fashion brand',
    'modest fashion made in italy',
    'luxury islamic fashion brand',
    'luxury islamic wear brand',
    'premium islamic fashion brand',
    'designer islamic fashion brand',
    'haute couture islamic fashion brand',
    'couture islamic fashion brand',
    'exclusive islamic fashion brand',
    'luxury hijab fashion brand',
    'luxury hijab wear brand',
    // Global positioning keywords
    'european abaya brand',
    'european abaya brands',
    'uae abaya brand',
    'uae abaya brands',
    'high end abaya brand',
    'high end abaya brands',
    'luxury fashion',
    'luxury fashion brand',
    'luxury fashion brands',
    'luxury fashion brand middle east',
    'luxury fashion brand abu dhabi',
    'luxury fashion brand uae',
    'abaya brand vogue',
    'abaya vogue',
    'abaya brand elle',
    'abaya elle',
    'abaya brand vogue arabia',
    'abaya vogue arabia',
    'best abaya brand uae',
    'best abaya brand abu dhabi',
    'best abaya brand dubai',
    'best abaya brand qatar',
    'best abaya brand doha',
    'best abaya brand saudi',
    'best abaya brand saudi arabia',
    'best abaya brand riyadh',
    'best abaya brand jeddah',
    'top abaya brand uae',
    'top abaya brand abu dhabi',
    'top abaya brand dubai',
    'top abaya brand qatar',
    'top abaya brand doha',
    'top abaya brand saudi',
    'top abaya brand riyadh',
    'top abaya brand jeddah',
    'leading abaya brand uae',
    'leading abaya brand abu dhabi',
    'leading abaya brand dubai',
    'leading abaya brand qatar',
    'leading abaya brand saudi',
    'premier abaya brand uae',
    'premier abaya brand abu dhabi',
    'premier abaya brand dubai',
    'premier abaya brand qatar',
    'premier abaya brand saudi',
    // Classic abaya keywords
    'classic abaya',
    'classic luxury abaya',
    'classic abaya brand',
    'classic abaya brands',
    'timeless abaya',
    'timeless abaya brand',
    'traditional abaya',
    'traditional luxury abaya',
    'elegant abaya',
    'elegant abaya brand',
    'best classic abaya brand',
    'top classic abaya brand',
    // Competitor brand searches
    'hermes abaya',
    'hermes abaya brand',
    'loro piana abaya',
    'loro piana abaya brand',
    'dolce and gabbana abaya',
    'dolce gabbana abaya',
    'dolce & gabbana abaya',
    'dolce and gabbana abaya brand',
    'chanel abaya',
    'chanel abaya brand',
    'gucci abaya',
    'gucci abaya brand',
    'prada abaya',
    'prada abaya brand',
    'versace abaya',
    'versace abaya brand',
    'dior abaya',
    'dior abaya brand',
    'fendi abaya',
    'fendi abaya brand',
    'valentino abaya',
    'valentino abaya brand',
    'givenchy abaya',
    'givenchy abaya brand',
    'balenciaga abaya',
    'balenciaga abaya brand',
    'burberry abaya',
    'burberry abaya brand',
    'louis vuitton abaya',
    'louis vuitton abaya brand',
    'van cleef arpels abaya',
    'van cleef & arpels abaya',
    'van cleef arpels abaya brand',
    'cartier abaya',
    'cartier abaya brand',
    'bottega veneta abaya',
    'bottega veneta abaya brand',
    'saint laurent abaya',
    'saint laurent abaya brand',
    'yves saint laurent abaya',
    'yves saint laurent abaya brand',
    'celine abaya',
    'celine abaya brand',
    'loewe abaya',
    'loewe abaya brand',
    'brunello cucinelli abaya',
    'brunello cucinelli abaya brand',
    'zimmermann abaya',
    'zimmermann abaya brand',
    'max mara abaya',
    'max mara abaya brand',
    'abaya brand like hermes',
    'abaya brand like loro piana',
    'abaya brand like dolce and gabbana',
    'abaya brand like chanel',
    'abaya brand like gucci',
    'abaya brand like prada',
    'abaya brand like dior',
    'abaya brand like valentino',
    'abaya brand like van cleef arpels',
    'luxury abaya alternative to hermes',
    'luxury abaya alternative to loro piana',
    'luxury abaya alternative to dolce and gabbana',
    'luxury abaya alternative to chanel',
    // Luxury stores and high-profile personalities
    'abaya brand harrods',
    'abaya harrods',
    'abaya brand ounass',
    'abaya ounass',
    'abaya brand printemps',
    'abaya printemps',
    'abaya brand selfridges',
    'abaya selfridges',
    'abaya brand de bijenkorf',
    'abaya de bijenkorf',
    'abaya brand luisaviaroma',
    'abaya luisaviaroma',
    'abaya brand rubaiyat',
    'abaya rubaiyat',
    'abaya saks fifth avenue',
    'abaya dubai mall',
    'abaya galleria mall',
    'abaya marina mall abu dhabi',
    'abaya brand KDW',
    'abaya KDW',
    'luxury abaya brand abu dhabi',
    'famous abaya brands abu dhabi',
    'luxury abayas abu dhabi',
    'famous abaya brands saudi',
    'famous abaya brand qatar',
    'famous abaya brand dubai',
    'popular abaya brand dubai',
  ],
  ar: [
    'بنت سعيد',
    'بنت سعيد عباية',
    'بنت سعيد ماركة',
    'بنت سعيد إيطاليا',
    'بنت سعيد فاخرة',
    'عباية فاخرة',
    'عباية راقية',
    'عباية إيطالية',
    'عباية حصرية',
    'عباية كوتور',
    'أغلى عباية',
    'أفخم عباية',
    'عباية من إيطاليا',
    'ماركة عباية فاخرة',
    'أزياء محتشمة فاخرة',
    'أزياء محتشمة راقية',
    'أزياء محتشمة فاخرة',
    'أزياء محتشمة حصرية',
    'أزياء محتشمة كوتور',
    'أزياء محتشمة إيطالية',
    'ملابس محتشمة فاخرة',
    'ملابس محتشمة راقية',
    'ملابس محتشمة حصرية',
    'أزياء إسلامية راقية',
    'أزياء إسلامية فاخرة',
    'أزياء إسلامية حصرية',
    'ملابس إسلامية فاخرة',
    'ملابس إسلامية راقية',
    'ماركة أزياء محتشمة فاخرة',
    'ماركة أزياء محتشمة راقية',
    'ماركة أزياء إسلامية فاخرة',
    'ماركة أزياء إسلامية راقية',
    'عباية فاخرة الدوحة',
    'عباية فاخرة الرياض',
    'عباية فاخرة جدة',
    'عباية فاخرة دبي',
    'عباية فاخرة أبوظبي',
    'عباية فاخرة الشارقة',
    'ماركة عباية قطر',
    'ماركة عباية السعودية',
    'ماركة عباية الإمارات',
    // Luxury stores and high-profile personalities
    'عباية هارودز',
    'ماركة عباية هارودز',
    'عباية سيلفريدجز',
    'ماركة عباية سيلفريدجز',
    'عباية جاليري لافاييت',
    'ماركة عباية جاليري لافاييت',
    'عباية أوناس',
    'ماركة عباية أوناس',
    'عباية برينتيمبس',
    'ماركة عباية برينتيمبس',
    'عباية دي بيجينكورف',
    'ماركة عباية دي بيجينكورف',
    'عباية لويزا فياروما',
    'ماركة عباية لويزا فياروما',
    'عباية روبيات',
    'ماركة عباية روبيات',
    'عباية ساكس فيفت أفينيو',
    'عباية دبي مول',
    'عباية جاليريا مول',
    'عباية مارينا مول أبوظبي',
    'عباية كيه دي دبليو',
    'ماركة عباية كيه دي دبليو',
    'عباية الإمارات',
    'عباية السعودية',
    'عباية الرياض',
    'عباية جورجينا',
    'عباية جورجينا رونالدو',
    'عباية زوجة كريستيانو رونالدو',
    'عباية فاخرة أبوظبي',
    'ماركة عباية أبوظبي',
    'ماركات عباية مشهورة أبوظبي',
    'عبايات فاخرة أبوظبي',
    'ماركات عباية مشهورة السعودية',
    'ماركة عباية مشهورة قطر',
    'ماركة عباية مشهورة دبي',
    'ماركة عباية شائعة دبي',
    // Khaleeji/Gulf Arabic dialect keywords
    'عباية فاخرة خليجية',
    'عباية راقية خليجية',
    'عباية فاخرة سعودية',
    'عباية فاخرة إماراتية',
    'عباية فاخرة قطرية',
    'عباية فاخرة كويتية',
    'عباية فاخرة بحرينية',
    'عباية فاخرة عمانية',
    'عباية خليجية',
    'عباية سعودية',
    'عباية إماراتية',
    'عباية قطرية',
    'عباية كويتية',
    'عباية بحرينية',
    'عباية عمانية',
    // Additional Khaleeji Arabic keywords
    'مصمم عباية',
    'عباية مصمم',
    'عباية فنية',
    'عباية لندن',
    'لندن عباية',
    'أزياء فاخرة',
    'أزياء محتشمة',
    'موضة فاخرة',
    'موضة محتشمة',
    // Global positioning in Arabic
    'ماركة عباية أوروبية',
    'ماركات عباية أوروبية',
    'ماركة عباية إماراتية',
    'ماركات عباية إماراتية',
    'ماركة عباية عالية الجودة',
    'ماركات عباية عالية الجودة',
    'أزياء فاخرة',
    'ماركة أزياء فاخرة',
    'ماركات أزياء فاخرة',
    'ماركة أزياء فاخرة الشرق الأوسط',
    'ماركة أزياء فاخرة أبوظبي',
    'ماركة أزياء فاخرة الإمارات',
    'عباية فوج',
    'ماركة عباية فوج',
    'عباية إيل',
    'ماركة عباية إيل',
    'عباية فوج العربية',
    'ماركة عباية فوج العربية',
    'ألطا مودا',
    'ألطا مودا إيطاليا',
    // GCC Ranking Arabic Keywords
    'أفضل ماركة عباية الإمارات',
    'أفضل ماركة عباية أبوظبي',
    'أفضل ماركة عباية دبي',
    'أفضل ماركة عباية قطر',
    'أفضل ماركة عباية الدوحة',
    'أفضل ماركة عباية السعودية',
    'أفضل ماركة عباية الرياض',
    'أفضل ماركة عباية جدة',
    'أفضل ماركة عباية الخليج',
    'أفضل ماركة عباية فاخرة الإمارات',
    'أفضل ماركة عباية فاخرة أبوظبي',
    'أفضل ماركة عباية فاخرة دبي',
    'أفضل ماركة عباية فاخرة قطر',
    'أفضل ماركة عباية فاخرة السعودية',
    'أفضل ماركة عباية فاخرة الرياض',
    'أفضل ماركة عباية فاخرة جدة',
    'أفضل ماركة عباية فاخرة الخليج',
    'ماركة عباية رقم 1 الإمارات',
    'ماركة عباية رقم 1 أبوظبي',
    'ماركة عباية رقم 1 دبي',
    'ماركة عباية رقم 1 قطر',
    'ماركة عباية رقم 1 السعودية',
    'ماركة عباية رقم 1 الرياض',
    'ماركة عباية رقم 1 جدة',
    'ماركة عباية رقم 1 الخليج',
    'أفضل ماركة عباية في الإمارات',
    'أفضل ماركة عباية في أبوظبي',
    'أفضل ماركة عباية في دبي',
    'أفضل ماركة عباية في قطر',
    'أفضل ماركة عباية في السعودية',
    'أفضل ماركة عباية في الرياض',
    'أفضل ماركة عباية في جدة',
    'عباية إيفا',
    'أفضل ماركة عباية فاخرة من جميع المنافسين',
    'عباية فاخرة بريطانية',
    'عباية فاخرة لندن',
    'ماركة عباية فاخرة بريطانية',
    'ماركة عباية فاخرة لندن',
    'أفضل ماركة عباية فاخرة في الإمارات',
    'أفضل ماركة عباية فاخرة في دبي',
    'أفضل ماركة عباية فاخرة في أبوظبي',
    // Royal audience Arabic keywords
    'عباية ملكية',
    'ماركة عباية ملكية',
    'عباية فاخرة ملكية',
    'عباية العائلة المالكة',
    'عباية للعائلة المالكة',
    'عباية أميرة',
    'عباية للأميرات',
    'عباية فاخرة للأميرات',
    'ماركة عباية للأميرات',
    'عباية أميرات',
    'عباية الأميرة',
    'عباية ملكة',
    'عباية للملكات',
    'عباية فاخرة للملكات',
    'ماركة عباية للملكات',
    'عباية الملكة',
    'عباية ملكات',
    'عباية شيخة',
    'عباية للشيخات',
    'عباية فاخرة للشيخات',
    'ماركة عباية للشيخات',
    'عباية الشيخة',
    'عباية شيخات',
    'عباية أزياء ملكية',
    'عباية كوتور ملكية',
    'عباية ألطا مودا ملكية',
    'عباية حصرية ملكية',
    'عباية فاخرة ملكية',
    'عباية العائلة المالكة الأردنية',
    'عباية العائلة المالكة القطرية',
    'عباية العائلة المالكة الإماراتية',
    'عباية العائلة المالكة السعودية',
    'عباية العائلة المالكة الكويتية',
    'عباية العائلة المالكة البحرينية',
    'عباية العائلة المالكة العمانية',
    'ماركة عباية للملوك',
    'ماركة عباية فاخرة للملوك',
    'ماركة عباية حصرية للملوك',
    // Classic abaya Arabic keywords
    'عباية كلاسيكية',
    'عباية كلاسيكية فاخرة',
    'ماركة عباية كلاسيكية',
    'عباية خالدة',
    'عباية تقليدية',
    'عباية تقليدية فاخرة',
    'عباية أنيقة',
    'أفضل ماركة عباية كلاسيكية',
    // Competitor brand Arabic keywords
    'عباية هيرميس',
    'عباية لورو بيانا',
    'عباية دولتشي أند غابانا',
    'عباية شانيل',
    'عباية غوتشي',
    'عباية برادا',
    'عباية فيرساتشي',
    'عباية ديور',
    'عباية فيندي',
    'عباية فالنتينو',
    'عباية جيفنشي',
    'عباية بالنسياغا',
    'عباية بيربيري',
    'عباية لويس فويتون',
    'عباية فان كليف أند أربلز',
    'عباية كارتيه',
    'عباية بوتيغا فينيتا',
    'عباية سان لوران',
    'عباية سيلين',
    'عباية لوي',
    'عباية برونيلو كوكينيلي',
    'عباية زيمرمان',
    'عباية ماكس مارا',
    'ماركة عباية مثل هيرميس',
    'ماركة عباية مثل لورو بيانا',
    'ماركة عباية مثل دولتشي أند غابانا',
    'ماركة عباية مثل شانيل',
    'بديل عباية فاخرة لهيرميس',
    'بديل عباية فاخرة للورو بيانا',
    'بديل عباية فاخرة لدولتشي أند غابانا',
    'بديل عباية فاخرة لشانيل',
  ],
  fr: [
    'abaya de luxe',
    'abaya haute couture',
    'abaya exclusive',
    'abaya italienne',
    'mode modeste de luxe',
    'mode modeste luxueuse',
    'mode modeste haut de gamme',
    'mode modeste premium',
    'mode modeste exclusive',
    'mode modeste couture',
    'mode modeste haute couture',
    'vêtements modestes de luxe',
    'vêtements modestes luxueux',
    'vêtements modestes haut de gamme',
    'vêtements modestes premium',
    'mode islamique de luxe',
    'mode islamique luxueuse',
    'mode islamique haut de gamme',
    'mode islamique premium',
    'marque mode modeste de luxe',
    'marque mode modeste luxueuse',
    'marque vêtements modestes de luxe',
    'marque mode islamique de luxe',
    'marque abaya de luxe',
    'abaya de luxe paris',
    'abaya de luxe france',
    'abaya paris',
    'abaya lyon',
    'abaya marseille',
    'marque abaya paris',
    'abaya haute couture paris',
    'abaya italienne paris',
    'abaya italienne france',
    // Luxury stores and high-profile personalities
    'abaya harrods',
    'marque abaya harrods',
    'abaya selfridges',
    'marque abaya selfridges',
    'abaya galeries lafayette',
    'marque abaya galeries lafayette',
    'abaya ounass',
    'marque abaya ounass',
    'abaya printemps',
    'marque abaya printemps',
    'abaya de bijenkorf',
    'marque abaya de bijenkorf',
    'abaya luisaviaroma',
    'marque abaya luisaviaroma',
    'abaya rubaiyat',
    'marque abaya rubaiyat',
    'abaya saks fifth avenue',
    'abaya dubai mall',
    'abaya galleria mall',
    'abaya marina mall abu dhabi',
    'abaya KDW',
    'marque abaya KDW',
    'abaya eau',
    'abaya arabie saoudite',
    'abaya riyad',
    'abaya reine rania',
    'abaya de luxe abu dhabi',
    'marque abaya abu dhabi',
    'marques abaya célèbres abu dhabi',
    'abayas de luxe abu dhabi',
    'marques abaya célèbres arabie saoudite',
    'marque abaya célèbre qatar',
    'marque abaya célèbre dubai',
    'marque abaya populaire dubai',
    // Global positioning in French
    'marque abaya européenne',
    'marques abaya européennes',
    'marque abaya émirats',
    'marques abaya émirats',
    'marque abaya haut de gamme',
    'marques abaya haut de gamme',
    'mode de luxe',
    'marque mode de luxe',
    'marques mode de luxe',
    'marque mode de luxe moyen-orient',
    'marque mode de luxe abu dhabi',
    'marque mode de luxe émirats',
    'abaya vogue',
    'marque abaya vogue',
    'abaya elle',
    'marque abaya elle',
    'abaya vogue arabia',
    'marque abaya vogue arabia',
  ],
  it: [
    'abaya di lusso',
    'abaya alta moda',
    'abaya esclusiva',
    'abaya italiana',
    'moda modesta di lusso',
    'moda modesta lussuosa',
    'moda modesta di alta gamma',
    'moda modesta premium',
    'moda modesta esclusiva',
    'moda modesta couture',
    'moda modesta alta moda',
    'abbigliamento modesto di lusso',
    'abbigliamento modesto lussuoso',
    'abbigliamento modesto di alta gamma',
    'abbigliamento modesto premium',
    'moda islamica di lusso',
    'moda islamica lussuosa',
    'moda islamica di alta gamma',
    'moda islamica premium',
    'marca moda modesta di lusso',
    'marca moda modesta lussuosa',
    'marca abbigliamento modesto di lusso',
    'marca moda islamica di lusso',
    'marca abaya di lusso',
    'abaya di lusso milano',
    'abaya di lusso roma',
    'abaya di lusso firenze',
    'abaya di lusso italia',
    'abaya milano',
    'abaya roma',
    'abaya firenze',
    'marca abaya milano',
    'marca abaya roma',
    'abaya alta moda milano',
    'abaya alta moda roma',
    'abaya italiana milano',
    'abaya made in italy',
    'abaya fatta in italia',
    // Luxury stores and high-profile personalities
    'abaya harrods',
    'marca abaya harrods',
    'abaya selfridges',
    'marca abaya selfridges',
    'abaya galeries lafayette',
    'marca abaya galeries lafayette',
    'abaya ounass',
    'marca abaya ounass',
    'abaya printemps',
    'marca abaya printemps',
    'abaya de bijenkorf',
    'marca abaya de bijenkorf',
    'abaya luisaviaroma',
    'marca abaya luisaviaroma',
    'abaya rubaiyat',
    'marca abaya rubaiyat',
    'abaya saks fifth avenue',
    'abaya dubai mall',
    'abaya galleria mall',
    'abaya marina mall abu dhabi',
    'abaya KDW',
    'marca abaya KDW',
    'abaya regina rania',
    'abaya di lusso abu dhabi',
    'marca abaya abu dhabi',
    'marche abaya famose abu dhabi',
    'abaya di lusso abu dhabi',
    'marche abaya famose arabia saudita',
    'marca abaya famosa qatar',
    'marca abaya famosa dubai',
    'marca abaya popolare dubai',
    // Global positioning in Italian
    'marca abaya europea',
    'marche abaya europee',
    'marca abaya emirati',
    'marche abaya emirati',
    'marca abaya alta gamma',
    'marche abaya alta gamma',
    'alta moda',
    'marca alta moda',
    'marche alta moda',
    'moda di lusso',
    'marca moda di lusso',
    'marche moda di lusso',
    'marca moda di lusso medio oriente',
    'marca moda di lusso abu dhabi',
    'marca moda di lusso emirati',
    'abaya vogue',
    'marca abaya vogue',
    'abaya elle',
    'marca abaya elle',
    'abaya vogue arabia',
    'marca abaya vogue arabia',
    'alta moda milano',
    'alta moda roma',
    'alta moda firenze',
    'moda di lusso milano',
    'moda di lusso roma',
    'moda di lusso firenze',
    // Additional Italian keywords
    'abaya designer',
    'abaya arte',
    'abaya londra',
    'londra abaya',
    'moda di lusso',
    'moda modesta',
  ],
  ru: [
    'люксовая абайя',
    'бренд абайя',
    'люксовая абайя бренд',
    'дорогая абайя',
    'эксклюзивная абайя',
    'высокая мода абайя',
    'кутюр абайя',
    'итальянская абайя',
    'абайя из италии',
    'люксовый бренд абайя',
    'элитная абайя',
    'дизайнерская абайя',
    'премиум абайя',
    'люксовая мусульманская мода',
    'эксклюзивная мусульманская мода',
    'люксовая абайя дубай',
    'люксовая абайя доха',
    'люксовая абайя эр-рияд',
    'люксовая абайя джидда',
    'люксовая абайя абу-даби',
    'бренд абайя катар',
    'бренд абайя саудовская аравия',
    'бренд абайя оаэ',
    // Additional Russian keywords
    'дизайнер абайя',
    'абайя дизайнер',
    'абайя искусство',
    'абайя лондон',
    'лондон абайя',
    'люксовая мода',
    'скромная мода',
    'модная абайя',
    'люксовая модная марка ближний восток',
    'люксовая модная марка абу-даби',
    'люксовая модная марка оаэ',
    'абайя вог',
    'бренд абайя вог',
    'абайя эль',
    'бренд абайя эль',
    'абайя вог арабия',
    'бренд абайя вог арабия',
    // Luxury stores and high-profile personalities
    'абайя хэрродс',
    'бренд абайя хэрродс',
    'абайя селфридж',
    'бренд абайя селфридж',
    'абайя галери лафайет',
    'бренд абайя галери лафайет',
    'абайя унас',
    'бренд абайя унас',
    'абайя принтан',
    'бренд абайя принтан',
    'абайя де биенкорф',
    'бренд абайя де биенкорф',
    'абайя луизавиарома',
    'бренд абайя луизавиарома',
    'абайя рубайят',
    'бренд абайя рубайят',
    'абайя сакс фифт авеню',
    'абайя дубай молл',
    'абайя галерия молл',
    'абайя марина молл абу-даби',
    'абайя КДВ',
    'бренд абайя КДВ',
    'абайя оаэ',
    'абайя саудовская аравия',
    'абайя эр-рияд',
    'абайя георгина',
    'абайя георгина роналдо',
    'абайя жена криштиану роналду',
    'абайя шейха моза',
    'абайя королева рания',
    'люксовая абайя абу-даби',
    'бренд абайя абу-даби',
    'известные бренды абайя абу-даби',
    'люксовые абайи абу-даби',
    'известные бренды абайя саудовская аравия',
    'известный бренд абайя катар',
    'известный бренд абайя дубай',
    'популярный бренд абайя дубай',
  ],
  nl: [
    'luxe abaya',
    'abaya merk',
    'luxe abaya merk',
    'dure abaya',
    'exclusieve abaya',
    'haute couture abaya',
    'couture abaya',
    'italiaanse abaya',
    'abaya uit italië',
    'luxe abaya merk',
    'elite abaya',
    'designer abaya',
    'premium abaya',
    'luxe islamitische mode',
    'exclusieve islamitische mode',
    'luxe abaya dubai',
    'luxe abaya doha',
    'luxe abaya riyad',
    'luxe abaya jeddah',
    'luxe abaya abu dhabi',
    'abaya merk qatar',
    'abaya merk saudi arabië',
    'abaya merk vae',
    // Priority Dutch keywords for first page ranking
    'modemerk midden oosten',
    'modemerk midden-oosten',
    'modest fashion',
    'modest fashion merk',
    'modest fashion merken',
    'luxe modest fashion',
    'luxe modest fashion merk',
    'abaya',
    'abaya merk',
    'abaya merken',
    'luxe abaya',
    'luxe abaya merk',
    'europees abaya merk',
    'europese abaya merken',
    'vae abaya merk',
    'vae abaya merken',
    'high end abaya merk',
    'high end abaya merken',
    'luxe mode',
    'luxe mode merk',
    'luxe mode merken',
    'luxe mode merk midden oosten',
    'luxe mode merk abu dhabi',
    'luxe mode merk vae',
    'abaya vogue',
    'abaya merk vogue',
    'abaya elle',
    'abaya merk elle',
    'abaya vogue arabia',
    'abaya merk vogue arabia',
    'modest fashion brand',
    'modest fashion brands',
    'abaya brand',
    'abaya brands',
    // Luxury stores and high-profile personalities
    'abaya harrods',
    'abaya merk harrods',
    'abaya selfridges',
    'abaya merk selfridges',
    'abaya galeries lafayette',
    'abaya merk galeries lafayette',
    'abaya ounass',
    'abaya merk ounass',
    'abaya printemps',
    'abaya merk printemps',
    'abaya de bijenkorf',
    'abaya merk de bijenkorf',
    'abaya luisaviaroma',
    'abaya merk luisaviaroma',
    'abaya rubaiyat',
    'abaya merk rubaiyat',
    'abaya saks fifth avenue',
    'abaya dubai mall',
    'abaya galleria mall',
    'abaya marina mall abu dhabi',
    'abaya KDW',
    'abaya merk KDW',
    'abaya koningin rania',
    'luxe abaya merk abu dhabi',
    'abaya merk abu dhabi',
    'bekende abaya merken abu dhabi',
    'luxe abaya\'s abu dhabi',
    'bekende abaya merken saudi arabië',
    'bekend abaya merk qatar',
    'bekend abaya merk dubai',
    'populair abaya merk dubai',
    // Additional Dutch keywords
    'abaya designer',
    'abaya kunst',
    'londen abaya',
    'abaya londen',
    'luxe mode',
    'modest fashion',
  ],
  // Khaleeji Arabic dialects
  'ar-SA': [
    'عباية فاخرة',
    'عباية راقية',
    'عباية سعودية فاخرة',
    'عباية نجدية',
    'عباية حجازية',
    'ماركة عباية سعودية',
    'عباية فاخرة الرياض',
    'عباية فاخرة جدة',
    'عباية فاخرة الدمام',
    'عباية فاخرة الخبر',
  ],
  'ar-AE': [
    'عباية فاخرة',
    'عباية راقية',
    'عباية إماراتية فاخرة',
    'ماركة عباية إماراتية',
    'عباية فاخرة دبي',
    'عباية فاخرة أبوظبي',
    'عباية فاخرة الشارقة',
    'عباية فاخرة عجمان',
  ],
  'ar-QA': [
    'عباية فاخرة',
    'عباية راقية',
    'عباية قطرية فاخرة',
    'ماركة عباية قطرية',
    'عباية فاخرة الدوحة',
  ],
  'ar-KW': [
    'عباية فاخرة',
    'عباية راقية',
    'عباية كويتية فاخرة',
    'ماركة عباية كويتية',
    'عباية فاخرة الكويت',
  ],
  'ar-BH': [
    'عباية فاخرة',
    'عباية راقية',
    'عباية بحرينية فاخرة',
    'ماركة عباية بحرينية',
    'عباية فاخرة المنامة',
  ],
  'ar-OM': [
    'عباية فاخرة',
    'عباية راقية',
    'عباية عمانية فاخرة',
    'ماركة عباية عمانية',
    'عباية فاخرة مسقط',
  ],
}


function dedupeKeywords(list: readonly string[]): string[] {
  const seen = new Set<string>()
  const out: string[] = []
  for (const raw of list) {
    const k = raw.trim()
    if (!k) continue
    const lower = k.toLowerCase()
    if (seen.has(lower)) continue
    seen.add(lower)
    out.push(k)
  }
  return out
}

export function flattenGccKeywordBuckets(): string[] {
  return Object.values(gccKeywords).flat() as string[]
}

/** Very large list — use for tooling or selective merges only. */
export function allMergedSeoKeywordPhrases(): string[] {
  const multiFlat = Object.values(multilingualKeywords).flat() as string[]
  return dedupeKeywords([
    ...primaryKeywords,
    ...regionalKeywords,
    ...multiFlat,
    ...pressKeywords,
    ...flattenGccKeywordBuckets(),
    ...gccMediaKeywords,
    ...uaeGovernmentKeywords,
    ...royalKeywords,
    ...royalKeywordsArabic,
  ])
}

/** Comma-separated string for legacy tooling (avoid huge HTML meta unless intentional). */
export function allMergedSeoKeywordsCsv(): string {
  return allMergedSeoKeywordPhrases().join(', ')
}
