/**
 * “Royal occasion” keyword bundles for optional SEO use.
 * Supplemental FAQ JSON-LD for royal-adjacent queries is localized in `lib/translations/seo/{locale}.ts`.
 * Does not claim royal endorsement, approval, or associations with named individuals—see comments in keyword lists.
 */

/** English search patterns (style and occasion framing; no implied royal endorsement). */
export const royalKeywords = [
  'royal abaya',
  'royal abaya brand',
  'royal luxury abaya',
  'royal family abaya',
  'royal abaya maison',
  'royal abaya atelier',
  'princess abaya',
  'princess abaya brand',
  'princess luxury abaya',
  'abaya for princesses',
  'luxury abaya for princesses',
  'princess abaya collection',
  'queen abaya',
  'queen abaya brand',
  'queen luxury abaya',
  'abaya for queens',
  'luxury abaya for queens',
  'queen abaya collection',
  'sheikha abaya',
  'sheikha abaya brand',
  'sheikha luxury abaya',
  'abaya for sheikhas',
  'luxury abaya for sheikhas',
  'sheikha abaya collection',
  'royal fashion abaya',
  'royal fashion abaya brand',
  'royal couture abaya',
  'royal haute couture abaya',
  'royal exclusive abaya',
  'royal premium abaya',
  'jordan royal family abaya',
  'jordan royal abaya',
  'qatar royal family abaya',
  'qatar royal abaya',
  'uae royal family abaya',
  'uae royal abaya',
  'saudi royal family abaya',
  'saudi royal abaya',
  'kuwait royal family abaya',
  'kuwait royal abaya',
  'bahrain royal family abaya',
  'bahrain royal abaya',
  'oman royal family abaya',
  'oman royal abaya',
  'abaya brand for royals',
  'luxury abaya brand for royals',
  'exclusive abaya brand for formal occasions',
  'formal occasion luxury abaya uae',
  'gala luxury abaya abu dhabi',
  'vip appointment luxury abaya dubai',
  'private fitting luxury abaya abu dhabi',
] as const

/** Arabic patterns—same occasion/style framing; no “approved by royals” claims. */
export const royalKeywordsArabic = [
  'عباية ملكية',
  'ماركة عباية ملكية',
  'عباية فاخرة ملكية',
  'عباية العائلة المالكة',
  'عباية للعائلة المالكة',
  'عباية أميرة',
  'عباية للأميرات',
  'عباية فاخرة للأميرات',
  'ماركة عباية للأميرات',
  'عباية أميرات',
  'عباية الأميرة',
  'عباية ملكة',
  'عباية للملكات',
  'عباية فاخرة للملكات',
  'ماركة عباية للملكات',
  'عباية الملكة',
  'عباية ملكات',
  'عباية شيخة',
  'عباية للشيخات',
  'عباية فاخرة للشيخات',
  'ماركة عباية للشيخات',
  'عباية الشيخة',
  'عباية شيخات',
  'عباية أزياء ملكية',
  'عباية كوتور ملكية',
  'عباية ألطا مودا ملكية',
  'عباية حصرية ملكية',
  'عباية فاخرة ملكية',
  'عباية العائلة المالكة الأردنية',
  'عباية العائلة المالكة القطرية',
  'عباية العائلة المالكة الإماراتية',
  'عباية العائلة المالكة السعودية',
  'عباية العائلة المالكة الكويتية',
  'عباية العائلة المالكة البحرينية',
  'عباية العائلة المالكة العمانية',
  'ماركة عباية للمناسبات الرسمية',
  'ماركة عباية فاخرة للمناسبات الرسمية',
  'عباية فاخرة للسهرة الإمارات',
  'موعد خاص عباية فاخرة أبوظبي',
] as const
