import type { AppLocale } from '@/lib/i18n/routing'

function dedupe(list: readonly string[]): string[] {
  const seen = new Set<string>()
  const out: string[] = []
  for (const raw of list) {
    const k = raw.trim()
    if (!k) continue
    const lower = k.toLowerCase()
    if (seen.has(lower)) continue
    seen.add(lower)
    out.push(k)
  }
  return out
}

function outfitSetPairs(outfits: readonly string[]): string[] {
  return outfits.flatMap((phrase) => {
    const setPhrase = phrase.replace(/\boutfit\b/gi, 'set')
    return setPhrase.toLowerCase() !== phrase.toLowerCase() ? [phrase, setPhrase] : [phrase]
  })
}

const SEASON_AND_RTW_EN = [
  'womenswear',
  "women's wear",
  'ready-to-wear',
  'ready to wear',
  'RTW',
  'spring summer 2026',
  'SS2026',
  'SS 2026',
  'spring summer collection',
  'fw 2026',
  'FW 2026',
  'FW26',
  'fall winter 2026',
  'fall winter 26',
  'fall styles',
  'winter styles',
  'summer styles',
  'spring styles',
  'style edit',
  'fashion edit',
  'seasonal edit',
] as const

const STYLE_AND_HERITAGE_EN = [
  'dubai outfit',
  'dubai style',
  'dubai fashion',
  'uae style',
  'uae fashion',
  'uae outfit',
  'uae heritage outfit',
  'national dress UAE',
  'national dress uae',
  'khaleeji style',
  'khaleeji fashion',
  'khaleej fashion',
  'Khaleeji fashion',
  'modest fashion',
  'cultural fashion',
  'heritage fashion',
  'Emirati fashion',
  'emirati designers',
  'Emirati designers',
  'best brand Abu Dhabi',
  'best brand abu dhabi',
  'emerging brands',
  'emerging fashion brands',
  'promising fashion brands',
  'fashion magazine',
  'extraordinary fashion',
  'fashion trends',
  'fashion trends 2027',
  'fashion trends 2026',
] as const

const DRESS_CODE_EN = [
  'dress code',
  'dress codes',
  'event dress',
  'formal dress code',
  'Abu Dhabi dress code',
  'UAE dress code',
  'Dubai dress code',
  'Saudi dress code',
  'KSA dress code',
  'Qatar dress code',
  'Doha dress code',
  'Muslim country dress code',
  'Jeddah dress code',
  'Al Ain dress code',
  'Ras Al Khaimah dress code',
  'Sharjah dress code',
  'Riyadh dress code',
  'Kuwait dress code',
  'Muscat dress code',
  'Manama dress code',
] as const

const SET_AND_TRAVEL_EN = outfitSetPairs([
  'travel set',
  'travel outfit',
  'elegant set',
  'elegant outfit',
  'europe outfit',
  'europe set',
  'summer outfit',
  'summer set',
  'black outfit',
  'black set',
  'winter outfit',
  'winter set',
  'spring outfit',
  'spring set',
  'city outfit',
  'city set',
  'airport outfit',
  'airport set',
  'holiday outfit',
  'holiday set',
  'weekend outfit',
  'weekend set',
  'day to evening outfit',
  'day to evening set',
  'modest outfit',
  'modest set',
  'luxury outfit',
  'luxury set',
  'heritage outfit',
  'heritage set',
])

const SET_PRODUCT_EN = [
  'best seller',
  'best sellers',
  'bestseller',
  'best selling top',
  'best selling shirt',
  'best selling pants',
  'best selling trousers',
  'oversized shirt',
  'oversized top',
  'oversized blouse',
  'oversized trousers',
  'oversized pants',
  'wide leg trousers',
  'wide-leg trousers',
  'palazzo trousers',
  'palazzo pants',
  'wide leg pants',
  'coordinate set',
  'two piece set',
  'two-piece set',
  'shirt and trouser set',
  'shirt and pants set',
  'luxury travel set',
  'designer travel set',
  'premium crepe set',
  'modest travel outfit',
  'GCC travel outfit',
  'UAE travel outfit',
] as const

const CITY_FASHION_EN = [
  'London fashion',
  'Paris fashion',
  'Parisian fashion',
  'Milan fashion',
  'New York fashion',
  'Rome fashion',
  'Berlin fashion',
  'Amsterdam fashion',
  'Madrid fashion',
  'Barcelona fashion',
  'Moscow fashion',
  'Shanghai fashion',
  'Beijing fashion',
  'Lisbon fashion',
  'Jakarta fashion',
  'Kuala Lumpur fashion',
  'Singapore fashion',
  'Toronto fashion',
  'Sydney fashion',
  'Abu Dhabi fashion',
  'Dubai fashion',
  'Al Ain fashion',
  'Al Quaa fashion',
  'Sharjah fashion',
  'Ras Al Khaimah fashion',
  'Doha fashion',
  'Riyadh fashion',
  'Jeddah fashion',
  'Kuwait City fashion',
  'Manama fashion',
  'Muscat fashion',
  'Los Angeles fashion',
  'LA fashion',
  'Miami fashion',
  'Rabat fashion',
  'Brunei fashion',
  'Brunei Darussalam fashion',
  'Singapore style',
  'Singapore outfit',
  'Los Angeles outfit',
  'Los Angeles style',
  'Miami outfit',
  'Miami style',
  'Rabat outfit',
  'Rabat style',
  'Brunei outfit',
  'Brunei style',
] as const

function placeDiscoveryTerms(place: string): string[] {
  const p = place.trim()
  const variants = [p, p.replace(/\s+/g, '')]
  const suffixes = [
    'fashion',
    'style',
    'outfit',
    'shop',
    'beauty',
    'jewellery',
    'jewelry',
    'abaya',
    'dress',
    'ladies wear',
    'ladies',
    'mkhawer',
    'mkhawer fashion',
  ]
  const terms: string[] = []
  for (const v of variants) {
    for (const s of suffixes) {
      terms.push(`${v} ${s}`)
    }
  }
  return terms
}

const PLACE_TARGET_EN = dedupe([
  ...placeDiscoveryTerms('Al Quaa'),
  ...placeDiscoveryTerms('Al Qua\'a'),
  ...placeDiscoveryTerms('AlQuaa'),
  ...placeDiscoveryTerms('Abu Dhabi'),
  ...placeDiscoveryTerms('Al Ain'),
  ...placeDiscoveryTerms('Doha'),
  ...placeDiscoveryTerms('Los Angeles'),
  ...placeDiscoveryTerms('LA'),
  ...placeDiscoveryTerms('Miami'),
  ...placeDiscoveryTerms('Rabat'),
  ...placeDiscoveryTerms('Brunei'),
  ...placeDiscoveryTerms('Singapore'),
  'al quaa mkhawer',
  'al quaa abaya',
  'alquaa fashion',
  'al quaa ladies wear',
])

/** Heavy London discovery — city, neighbourhoods, modest/luxury/abaya intent. */
const LONDON_HEAVY_EN = dedupe([
  ...placeDiscoveryTerms('London'),
  'London fashion',
  'London style',
  'London outfit',
  'London UK fashion',
  'UK London fashion',
  'London modest fashion',
  'London luxury fashion',
  'London designer fashion',
  'London contemporary fashion',
  'London womenswear',
  'London ready-to-wear',
  'London travel outfit',
  'London travel set',
  'London elegant outfit',
  'London summer outfit',
  'London evening outfit',
  'London day to evening outfit',
  'London abaya',
  'London abayas',
  'luxury abaya London',
  'designer abaya London',
  'modest fashion London',
  'best brand London',
  'emerging designers London',
  'Emirati fashion London',
  'GCC fashion London',
  'khaleeji fashion London',
  'UAE fashion London',
  'London shopping',
  'London ladies wear',
  'London dress',
  'London set',
  'buy abaya London',
  'buy modest fashion London',
  'Mayfair fashion',
  'Knightsbridge fashion',
  'Chelsea fashion',
  'Notting Hill fashion',
  'Covent Garden fashion',
  'Belgravia fashion',
  'Kensington fashion',
  'Marylebone fashion',
  'Hyde Park fashion',
  'Soho London fashion',
  'West London fashion',
  'Central London fashion',
  'East London fashion',
  'London Fashion Week',
])

/** London brand discovery — abaya brands, modest fashion, niche, GCC & contemporary designers. */
const LONDON_BRAND_DISCOVERY_EN = dedupe([
  'abaya brand London',
  'abaya brands London',
  'best abaya brand London',
  'best abaya brands London',
  'luxury abaya brand London',
  'luxury abaya brands London',
  'designer abaya brand London',
  'designer abaya brands London',
  'high end abaya brand London',
  'high-end abaya brands London',
  'contemporary abaya brand London',
  'contemporary abaya brands London',
  'contemporary abaya London',
  'premium abaya brand London',
  'new abaya brand London',
  'emerging abaya brand London',
  'niche abaya brand London',
  'boutique abaya brand London',
  'independent abaya brand London',
  'London abaya boutique',
  'London abaya brands',
  'modest fashion brand London',
  'modest fashion brands London',
  'best modest fashion brand London',
  'best modest fashion brands London',
  'luxury modest fashion London',
  'luxury modest fashion brands London',
  'modest wear brands London',
  'modest luxury brands London',
  'modest designer brands London',
  'contemporary modest fashion London',
  'contemporary modest fashion brands London',
  'London modest fashion boutique',
  'niche fashion brand London',
  'niche brands London',
  'niche fashion brands London',
  'niche abaya brand London',
  'niche modest fashion London',
  'boutique modest fashion London',
  'independent fashion brand London',
  'emerging fashion brands London',
  'emerging designers London',
  'promising fashion brands London',
  'GCC designer London',
  'GCC designers London',
  'GCC fashion brand London',
  'GCC fashion brands London',
  'Gulf designer London',
  'Gulf designers London',
  'Gulf fashion brand London',
  'Gulf fashion brands London',
  'khaleeji designer London',
  'khaleeji designers London',
  'khaleeji fashion brand London',
  'khaleeji fashion brands London',
  'khaleeji abaya brand London',
  'Emirati designer London',
  'Emirati designers London',
  'Emirati fashion brand London',
  'Emirati abaya brand London',
  'UAE designer London',
  'UAE designers London',
  'UAE fashion brand London',
  'UAE abaya brand London',
  'contemporary fashion brand London',
  'contemporary fashion brands London',
  'contemporary designer London',
  'contemporary designers London',
  'contemporary brands London',
  'contemporary fashion house London',
  'London contemporary fashion brand',
  'London heritage abaya brand',
  'London luxury modest brand',
  'buy abaya brands London',
  'discover abaya brands London',
])

const ABAYA_DISCOVERY_EN = [
  'high end abaya',
  'high-end abaya',
  'most beautiful abaya',
  'abaya trends',
  'abaya trend',
  'abaya in all colors',
  'abaya in all colours',
  'abaya all colors',
  'cotton abaya',
  'open abaya',
  'closed abaya',
  'abaya cuff',
  'abaya cuffs',
  'A-line abaya',
  'a line abaya',
  'A line abaya',
  'wide abaya',
  'straight abaya',
  'sexy abaya',
  'new abaya',
  'new abayas',
] as const

const COLLECTION_AND_DESIGNER_EN = [
  'new collection',
  'new collections',
  'fashion collection',
  'fashion collections',
  'latest collection',
  'seasonal collection',
  'Dutch designer',
  'Dutch designers',
  'Netherlands designer',
  'Amsterdam designer',
  'Dutch fashion designer',
] as const

const FASHION_WEEKS_EN = [
  'Paris Fashion Week',
  'Milan Fashion Week',
  'London Fashion Week',
  'New York Fashion Week',
  'Dubai Fashion Week',
  'Abu Dhabi Fashion Week',
  'Arab Fashion Week',
  'Copenhagen Fashion Week',
  'Berlin Fashion Week',
  'Madrid Fashion Week',
  'Barcelona Fashion Week',
  'Rome Fashion Week',
  'Tokyo Fashion Week',
  'Shanghai Fashion Week',
  'Hong Kong Fashion Week',
  'São Paulo Fashion Week',
  'Lagos Fashion Week',
  'Riyadh Fashion Week',
  'Jeddah Fashion Week',
  'Doha Fashion Week',
  'Kuwait Fashion Week',
  'Amsterdam Fashion Week',
  'Los Angeles Fashion Week',
  'Miami Fashion Week',
  'Fashion Week',
] as const

/** Localized city + fashion terms — Los Angeles, Miami, Rabat, Brunei, Singapore. */
const REGION_CITY_FASHION_LOCALIZED: Partial<Record<AppLocale, readonly string[]>> = {
  ar: [
    'أزياء لوس أنجلوس',
    'أزياء ميامي',
    'أزياء الرباط',
    'أزياء بروناي',
    'أزياء سنغافورة',
    'إطلالة لوس أنجلوس',
    'إطلالة ميامي',
    'إطلالة الرباط',
    'إطلالة بروناي',
    'إطلالة سنغافورة',
    'ستايل لوس أنجلوس',
    'ستايل ميامي',
    'ستايل الرباط',
    'ستايل بروناي',
    'ستايل سنغافورة',
  ],
  fr: [
    'mode Los Angeles',
    'mode Miami',
    'mode Rabat',
    'mode Brunei',
    'mode Singapour',
    'tenue Los Angeles',
    'tenue Miami',
    'tenue Rabat',
    'tenue Brunei',
    'tenue Singapour',
    'style Los Angeles',
    'style Miami',
    'style Rabat',
    'style Brunei',
    'style Singapour',
  ],
  it: [
    'moda Los Angeles',
    'moda Miami',
    'moda Rabat',
    'moda Brunei',
    'moda Singapore',
    'outfit Los Angeles',
    'outfit Miami',
    'outfit Rabat',
    'outfit Brunei',
    'outfit Singapore',
    'stile Los Angeles',
    'stile Miami',
    'stile Rabat',
    'stile Brunei',
    'stile Singapore',
  ],
  es: [
    'moda Los Ángeles',
    'moda Miami',
    'moda Rabat',
    'moda Brunéi',
    'moda Singapur',
    'outfit Los Ángeles',
    'outfit Miami',
    'outfit Rabat',
    'outfit Brunéi',
    'outfit Singapur',
    'estilo Los Ángeles',
    'estilo Miami',
    'estilo Rabat',
    'estilo Brunéi',
    'estilo Singapur',
  ],
  de: [
    'Mode Los Angeles',
    'Mode Miami',
    'Mode Rabat',
    'Mode Brunei',
    'Mode Singapur',
    'Outfit Los Angeles',
    'Outfit Miami',
    'Outfit Rabat',
    'Outfit Brunei',
    'Outfit Singapur',
    'Stil Los Angeles',
    'Stil Miami',
    'Stil Rabat',
    'Stil Brunei',
    'Stil Singapur',
  ],
  nl: [
    'mode Los Angeles',
    'mode Miami',
    'mode Rabat',
    'mode Brunei',
    'mode Singapore',
    'outfit Los Angeles',
    'outfit Miami',
    'outfit Rabat',
    'outfit Brunei',
    'outfit Singapore',
    'stijl Los Angeles',
    'stijl Miami',
    'stijl Rabat',
    'stijl Brunei',
    'stijl Singapore',
  ],
  pt: [
    'moda Los Angeles',
    'moda Miami',
    'moda Rabat',
    'moda Brunei',
    'moda Singapura',
    'outfit Los Angeles',
    'outfit Miami',
    'outfit Rabat',
    'outfit Brunei',
    'outfit Singapura',
    'estilo Los Angeles',
    'estilo Miami',
    'estilo Rabat',
    'estilo Brunei',
    'estilo Singapura',
  ],
  ru: [
    'мода Лос-Анджелес',
    'мода Майами',
    'мода Рабат',
    'мода Бруней',
    'мода Сингапур',
    'образ Лос-Анджелес',
    'образ Майами',
    'образ Рабат',
    'образ Бруней',
    'образ Сингапур',
    'стиль Лос-Анджелес',
    'стиль Майами',
    'стиль Рабат',
    'стиль Бруней',
    'стиль Сингапур',
  ],
  zh: [
    '洛杉矶时尚',
    '迈阿密时尚',
    '拉巴特时尚',
    '文莱时尚',
    '新加坡时尚',
    '洛杉矶穿搭',
    '迈阿密穿搭',
    '拉巴特穿搭',
    '文莱穿搭',
    '新加坡穿搭',
    '洛杉矶风格',
    '迈阿密风格',
    '拉巴特风格',
    '文莱风格',
    '新加坡风格',
  ],
  id: [
    'fashion Los Angeles',
    'fashion Miami',
    'fashion Rabat',
    'fashion Brunei',
    'fashion Singapura',
    'outfit Los Angeles',
    'outfit Miami',
    'outfit Rabat',
    'outfit Brunei',
    'outfit Singapura',
  ],
  ms: [
    'fesyen Los Angeles',
    'fesyen Miami',
    'fesyen Rabat',
    'fesyen Brunei',
    'fesyen Singapura',
    'outfit Los Angeles',
    'outfit Miami',
    'outfit Rabat',
    'outfit Brunei',
    'outfit Singapura',
  ],
}

/** Heavy London targeting — all locales. */
const LONDON_HEAVY_LOCALIZED: Partial<Record<AppLocale, readonly string[]>> = {
  ar: [
    'أزياء لندن',
    'ستايل لندن',
    'إطلالة لندن',
    'أزياء لندن المملكة المتحدة',
    'أزياء محتشمة لندن',
    'أزياء فاخرة لندن',
    'أزياء مصمّمة لندن',
    'أزياء نسائية لندن',
    'إطلالة سفر لندن',
    'إطلالة أنيقة لندن',
    'عباية لندن',
    'عبايات لندن',
    'عباية فاخرة لندن',
    'أفضل علامة لندن',
    'أزياء خليجية لندن',
    'أزياء إماراتية لندن',
    'تسوق لندن',
    'أزياء ميڤير',
    'أزياء نايتسبرج',
    'أزياء تشيلسي',
    'أزياء كوفنت غاردن',
    'أزياء بلغرافيا',
    'أزياء كنسينغتون',
    'أزياء ماريلبون',
    'أزياء هايد بارك',
    'أزياء سوهو لندن',
    'غرب لندن أزياء',
    'وسط لندن أزياء',
    'أسبوع الموضة لندن',
    'شراء عباية لندن',
  ],
  fr: [
    'mode Londres',
    'style Londres',
    'tenue Londres',
    'mode modeste Londres',
    'mode de luxe Londres',
    'mode créateur Londres',
    'prêt-à-porter Londres',
    'tenue voyage Londres',
    'tenue élégante Londres',
    'abaya Londres',
    'abaya de luxe Londres',
    'meilleure marque Londres',
    'mode khaleeji Londres',
    'mode émiratie Londres',
    'shopping Londres',
    'mode Mayfair',
    'mode Knightsbridge',
    'mode Chelsea',
    'mode Covent Garden',
    'mode Belgravia',
    'mode Kensington',
    'mode Marylebone',
    'mode Hyde Park',
    'mode Soho Londres',
    'Ouest de Londres mode',
    'Semaine de la mode Londres',
    'acheter abaya Londres',
  ],
  it: [
    'moda Londra',
    'stile Londra',
    'outfit Londra',
    'moda modesta Londra',
    'moda di lusso Londra',
    'moda designer Londra',
    'pronto moda Londra',
    'outfit viaggio Londra',
    'outfit elegante Londra',
    'abaya Londra',
    'abaya di lusso Londra',
    'miglior brand Londra',
    'moda khaleeji Londra',
    'moda emiratina Londra',
    'shopping Londra',
    'moda Mayfair',
    'moda Knightsbridge',
    'moda Chelsea',
    'moda Covent Garden',
    'moda Belgravia',
    'moda Kensington',
    'moda Marylebone',
    'moda Hyde Park',
    'moda Soho Londra',
    'Settimana della moda Londra',
    'comprare abaya Londra',
  ],
  es: [
    'moda Londres',
    'estilo Londres',
    'outfit Londres',
    'moda modesta Londres',
    'moda de lujo Londres',
    'moda de diseñador Londres',
    'prêt-à-porter Londres',
    'outfit viaje Londres',
    'outfit elegante Londres',
    'abaya Londres',
    'abaya de lujo Londres',
    'mejor marca Londres',
    'moda khaleeji Londres',
    'moda emiratí Londres',
    'compras Londres',
    'moda Mayfair',
    'moda Knightsbridge',
    'moda Chelsea',
    'moda Covent Garden',
    'moda Belgravia',
    'moda Kensington',
    'moda Marylebone',
    'moda Hyde Park',
    'moda Soho Londres',
    'Semana de la moda Londres',
    'comprar abaya Londres',
  ],
  de: [
    'Mode London',
    'Stil London',
    'Outfit London',
    'bescheidene Mode London',
    'Luxusmode London',
    'Designermode London',
    'Ready-to-Wear London',
    'Reise-Outfit London',
    'elegantes Outfit London',
    'Abaya London',
    'Luxus-Abaya London',
    'beste Marke London',
    'Khaleeji-Mode London',
    'emiratische Mode London',
    'Shopping London',
    'Mode Mayfair',
    'Mode Knightsbridge',
    'Mode Chelsea',
    'Mode Covent Garden',
    'Mode Belgravia',
    'Mode Kensington',
    'Mode Marylebone',
    'Mode Hyde Park',
    'Mode Soho London',
    'London Fashion Week',
    'Abaya London kaufen',
  ],
  nl: [
    'mode Londen',
    'stijl Londen',
    'outfit Londen',
    'bescheiden mode Londen',
    'luxemode Londen',
    'designermode Londen',
    'ready-to-wear Londen',
    'reiskleding Londen',
    'elegant outfit Londen',
    'abaya Londen',
    'luxe abaya Londen',
    'beste merk Londen',
    'khaleeji mode Londen',
    'Emiratische mode Londen',
    'winkelen Londen',
    'mode Mayfair',
    'mode Knightsbridge',
    'mode Chelsea',
    'mode Covent Garden',
    'mode Belgravia',
    'mode Kensington',
    'mode Marylebone',
    'mode Hyde Park',
    'mode Soho Londen',
    'Londen Fashion Week',
    'abaya kopen Londen',
  ],
  pt: [
    'moda Londres',
    'estilo Londres',
    'outfit Londres',
    'moda modesta Londres',
    'moda de luxo Londres',
    'moda de designer Londres',
    'prêt-à-porter Londres',
    'outfit viagem Londres',
    'outfit elegante Londres',
    'abaya Londres',
    'abaya de luxo Londres',
    'melhor marca Londres',
    'moda khaleeji Londres',
    'moda emirati Londres',
    'compras Londres',
    'moda Mayfair',
    'moda Knightsbridge',
    'moda Chelsea',
    'moda Covent Garden',
    'moda Belgravia',
    'moda Kensington',
    'moda Marylebone',
    'moda Hyde Park',
    'moda Soho Londres',
    'Semana de moda Londres',
    'comprar abaya Londres',
  ],
  ru: [
    'мода Лондон',
    'стиль Лондон',
    'образ Лондон',
    'скромная мода Лондон',
    'люксовая мода Лондон',
    'дизайнерская мода Лондон',
    'готовая одежда Лондон',
    'travel outfit Лондон',
    'элегантный образ Лондон',
    'абайя Лондон',
    'люксовая абайя Лондон',
    'лучший бренд Лондон',
    'мода хали́джи Лондон',
    'эмиратская мода Лондон',
    'шопинг Лондон',
    'мода Мейфэр',
    'мода Найтсбридж',
    'мода Челси',
    'мода Ковент-Гарден',
    'мода Белгравия',
    'мода Кенсингтон',
    'мода Мэрилбон',
    'мода Хайд-Парк',
    'мода Сохо Лондон',
    'Неделя моды Лондон',
    'купить абайю Лондон',
  ],
  zh: [
    '伦敦时尚',
    '伦敦风格',
    '伦敦穿搭',
    '伦敦端庄时尚',
    '伦敦奢华时尚',
    '伦敦设计师时尚',
    '伦敦成衣',
    '伦敦旅行穿搭',
    '伦敦优雅穿搭',
    '伦敦长袍',
    '伦敦奢华长袍',
    '伦敦最佳品牌',
    '伦敦海湾时尚',
    '伦敦阿联酋时尚',
    '伦敦购物',
    '梅菲尔时尚',
    '骑士桥时尚',
    '切尔西时尚',
    '考文特花园时尚',
    '贝尔格莱维亚时尚',
    '肯辛顿时尚',
    '马里波恩时尚',
    '海德公园时尚',
    '伦敦苏活时尚',
    '伦敦时装周',
    '伦敦购买长袍',
  ],
  id: [
    'fashion London',
    'style London',
    'outfit London',
    'modest fashion London',
    'luxury fashion London',
    'designer fashion London',
    'London travel outfit',
    'London elegant outfit',
    'abaya London',
    'luxury abaya London',
    'best brand London',
    'khaleeji fashion London',
    'Emirati fashion London',
    'London shopping',
    'Mayfair fashion',
    'Knightsbridge fashion',
    'Covent Garden fashion',
    'Belgravia fashion',
    'Kensington fashion',
    'Marylebone fashion',
    'Hyde Park fashion',
    'London Fashion Week',
    'beli abaya London',
  ],
  ms: [
    'fesyen London',
    'gaya London',
    'outfit London',
    'fesyen sopan London',
    'fesyen mewah London',
    'fesyen pereka London',
    'outfit perjalanan London',
    'outfit anggun London',
    'abaya London',
    'abaya mewah London',
    'jenama terbaik London',
    'fesyen khaleeji London',
    'fesyen Emirati London',
    'membeli-belah London',
    'fesyen Mayfair',
    'fesyen Knightsbridge',
    'fesyen Covent Garden',
    'fesyen Belgravia',
    'fesyen Kensington',
    'fesyen Marylebone',
    'fesyen Hyde Park',
    'London Fashion Week',
    'beli abaya London',
  ],
}

/** London abaya, modest, niche, GCC & contemporary brand discovery — all locales. */
const LONDON_BRAND_DISCOVERY_LOCALIZED: Partial<Record<AppLocale, readonly string[]>> = {
  ar: [
    'علامة عباية لندن',
    'علامات عباية لندن',
    'أفضل علامة عباية لندن',
    'عباية مصمّمة لندن',
    'عباية فاخرة لندن',
    'علامة عباية معاصرة لندن',
    'علامات أزياء محتشمة لندن',
    'أفضل علامة أزياء محتشمة لندن',
    'أزياء محتشمة فاخرة لندن',
    'علامات أزياء محتشمة راقية لندن',
    'علامة نيش لندن',
    'علامات نيش لندن',
    'علامة نيش عباية لندن',
    'علامات ناشئة لندن',
    'مصممون خليجيون لندن',
    'مصممون إماراتيون لندن',
    'مصممو الخليج لندن',
    'علامة أزياء خليجية لندن',
    'علامة أزياء إماراتية لندن',
    'علامة أزياء معاصرة لندن',
    'علامات معاصرة لندن',
    'دار أزياء معاصرة لندن',
    'بوتيك عباية لندن',
    'بوتيك أزياء محتشمة لندن',
    'شراء عباية ماركات لندن',
  ],
  fr: [
    'marque abaya Londres',
    'marques abaya Londres',
    'meilleure marque abaya Londres',
    'abaya de créateur Londres',
    'abaya de luxe Londres',
    'marque abaya contemporaine Londres',
    'marques mode modeste Londres',
    'meilleure marque mode modeste Londres',
    'mode modeste de luxe Londres',
    'marque de niche Londres',
    'marques de niche Londres',
    'marques émergentes Londres',
    'créateurs du Golfe Londres',
    'créateurs émiratis Londres',
    'créateurs khaleeji Londres',
    'marque mode du Golfe Londres',
    'marque mode émiratie Londres',
    'marque mode contemporaine Londres',
    'marques contemporaines Londres',
    'maison de mode contemporaine Londres',
    'boutique abaya Londres',
    'boutique mode modeste Londres',
  ],
  it: [
    'brand abaya Londra',
    'marchi abaya Londra',
    'miglior brand abaya Londra',
    'abaya designer Londra',
    'abaya di lusso Londra',
    'brand abaya contemporaneo Londra',
    'marchi modest fashion Londra',
    'miglior brand modest fashion Londra',
    'modest fashion di lusso Londra',
    'brand di nicchia Londra',
    'marchi di nicchia Londra',
    'marchi emergenti Londra',
    'designer del Golfo Londra',
    'designer emiratini Londra',
    'designer khaleeji Londra',
    'brand moda del Golfo Londra',
    'brand moda emiratina Londra',
    'brand moda contemporanea Londra',
    'marchi contemporanei Londra',
    'boutique abaya Londra',
    'boutique modest fashion Londra',
  ],
  es: [
    'marca abaya Londres',
    'marcas abaya Londres',
    'mejor marca abaya Londres',
    'abaya de diseñador Londres',
    'abaya de lujo Londres',
    'marca abaya contemporánea Londres',
    'marcas moda modesta Londres',
    'mejor marca moda modesta Londres',
    'moda modesta de lujo Londres',
    'marca nicho Londres',
    'marcas nicho Londres',
    'marcas emergentes Londres',
    'diseñadores del Golfo Londres',
    'diseñadores emiratíes Londres',
    'diseñadores khaleeji Londres',
    'marca moda del Golfo Londres',
    'marca moda emiratí Londres',
    'marca moda contemporánea Londres',
    'marcas contemporáneas Londres',
    'boutique abaya Londres',
    'boutique moda modesta Londres',
  ],
  de: [
    'Abaya-Marke London',
    'Abaya-Marken London',
    'beste Abaya-Marke London',
    'Designer-Abaya London',
    'Luxus-Abaya London',
    'zeitgenössische Abaya-Marke London',
    'bescheidene Mode Marken London',
    'beste bescheidene Mode Marke London',
    'Luxus bescheidene Mode London',
    'Nischenmarke London',
    'Nischenmarken London',
    'aufstrebende Marken London',
    'Golf-Designer London',
    'emiratische Designer London',
    'Khaleeji-Designer London',
    'Golf-Modemarke London',
    'emiratische Modemarke London',
    'zeitgenössische Modemarke London',
    'zeitgenössische Marken London',
    'Abaya-Boutique London',
    'bescheidene Mode Boutique London',
  ],
  nl: [
    'abaya merk Londen',
    'abaya merken Londen',
    'beste abaya merk Londen',
    'designer abaya Londen',
    'luxe abaya Londen',
    'eigentijds abaya merk Londen',
    'bescheiden mode merken Londen',
    'beste bescheiden mode merk Londen',
    'luxe bescheiden mode Londen',
    'niche merk Londen',
    'niche merken Londen',
    'opkomende merken Londen',
    'Golf designers Londen',
    'Emiratische designers Londen',
    'khaleeji designers Londen',
    'Golf modemerk Londen',
    'Emiratisch modemerk Londen',
    'eigentijds modemerk Londen',
    'eigentijdse merken Londen',
    'abaya boutique Londen',
    'bescheiden mode boutique Londen',
  ],
  pt: [
    'marca abaya Londres',
    'marcas abaya Londres',
    'melhor marca abaya Londres',
    'abaya de designer Londres',
    'abaya de luxo Londres',
    'marca abaya contemporânea Londres',
    'marcas moda modesta Londres',
    'melhor marca moda modesta Londres',
    'moda modesta de luxo Londres',
    'marca de nicho Londres',
    'marcas de nicho Londres',
    'marcas emergentes Londres',
    'designers do Golfo Londres',
    'designers emiratis Londres',
    'designers khaleeji Londres',
    'marca moda do Golfo Londres',
    'marca moda emirati Londres',
    'marca moda contemporânea Londres',
    'marcas contemporâneas Londres',
    'boutique abaya Londres',
    'boutique moda modesta Londres',
  ],
  ru: [
    'бренд абай London',
    'бренды абай London',
    'лучший бренд абай London',
    'дизайнерская абайя London',
    'люксовая абайя London',
    'современный бренд абай London',
    'бренды скромной моды London',
    'лучший бренд скромной моды London',
    'люксовая скромная мода London',
    'нишевый бренд London',
    'нишевые бренды London',
    'новые бренды London',
    'дизайнеры Персидского залива London',
    'эмиратские дизайнеры London',
    'дизайнеры хали́джи London',
    'бренд моды Залива London',
    'эмиратский бренд моды London',
    'современный бренд моды London',
    'современные бренды London',
    'бутик абай London',
    'бутик скромной моды London',
  ],
  zh: [
    '伦敦长袍品牌',
    '伦敦长袍品牌推荐',
    '最佳伦敦长袍品牌',
    '伦敦设计师长袍',
    '伦敦奢华长袍',
    '伦敦当代长袍品牌',
    '伦敦端庄时尚品牌',
    '最佳伦敦端庄时尚品牌',
    '伦敦奢华端庄时尚',
    '伦敦小众品牌',
    '伦敦小众时尚品牌',
    '伦敦新兴品牌',
    '伦敦海湾设计师',
    '伦敦阿联酋设计师',
    '伦敦海湾时尚品牌',
    '伦敦阿联酋时尚品牌',
    '伦敦当代时尚品牌',
    '伦敦当代品牌',
    '伦敦长袍精品店',
    '伦敦端庄时尚精品店',
  ],
  id: [
    'abaya brand London',
    'best abaya brand London',
    'luxury abaya brand London',
    'contemporary abaya brand London',
    'modest fashion brand London',
    'best modest fashion brand London',
    'niche brand London',
    'niche fashion brands London',
    'emerging brands London',
    'GCC designers London',
    'Gulf designers London',
    'khaleeji designers London',
    'Emirati designers London',
    'contemporary fashion brand London',
    'contemporary brands London',
    'London abaya boutique',
    'London modest fashion boutique',
  ],
  ms: [
    'jenama abaya London',
    'jenama abaya terbaik London',
    'jenama abaya mewah London',
    'jenama abaya kontemporari London',
    'jenama fesyen sopan London',
    'jenama fesyen sopan terbaik London',
    'jenama niche London',
    'jenama niche fesyen London',
    'jenama baharu London',
    'pereka GCC London',
    'pereka Gulf London',
    'pereka khaleeji London',
    'pereka Emirati London',
    'jenama fesyen kontemporari London',
    'jenama kontemporari London',
    'butik abaya London',
    'butik fesyen sopan London',
  ],
}

const LOCALIZED_EXPANSION: Partial<Record<AppLocale, readonly string[]>> = {
  ar: [
    'أزياء نسائية',
    'جاهز للارتداء',
    'ربيع صيف 2026',
    'خريف شتاء 2026',
    'إطلالة دبي',
    'ستايل دبي',
    'أزياء الإمارات',
    'زي التراث الإماراتي',
    'الزي الوطني الإماراتي',
    'أسلوب خليجي',
    'أزياء خليجية',
    'أزياء محتشمة',
    'أزياء ثقافية',
    'أزياء إماراتية',
    'مصممون إماراتيون',
    'أفضل علامة أبوظبي',
    'علامات ناشئة',
    'اتجاهات الموضة',
    'اتجاهات الموضة 2027',
    'قواعد اللباس',
    'قواعد اللباس أبوظبي',
    'قواعد اللباس الإمارات',
    'قواعد اللباس السعودية',
    'قواعد اللباس قطر',
    'قواعد اللباس الدوحة',
    'قواعد اللباس جدة',
    'قواعد اللباس العين',
    'قواعد اللباس الشارقة',
    'قواعد اللباس رأس الخيمة',
    'طقم سفر',
    'إطلالة سفر',
    'طقم أنيق',
    'إطلالة أنيقة',
    'إطلالة صيفية',
    'طقم صيفي',
    'إطلالة سوداء',
    'الأكثر مبيعاً',
    'قميص واسع',
    'بنطال واسع',
    'بنطال بالازو',
    'أزياء لندن',
    'أزياء باريس',
    'أزياء ميلانو',
    'أزياء نيويورك',
    'أزياء أبوظبي',
    'أزياء دبي',
    'أزياء العين',
    'أزياء العقة',
    'أزياء الدوحة',
    'أزياء الرياض',
    'أزياء جدة',
    'عباية العقة',
    'أزياء العقة',
    'مخاوير العقة',
    'أزياء أبوظبي',
    'أزياء العين',
    'عباية فاخرة راقية',
    'أجمل عباية',
    'اتجاهات العباية',
    'عباية بجميع الألوان',
    'عباية قطنية',
    'عباية مفتوحة',
    'عباية مغلقة',
    'أسورة العباية',
    'عباية A-line',
    'عباية واسعة',
    'عباية مستقيمة',
    'عباية جديدة',
    'مجموعة جديدة',
    'مجموعة أزياء',
    'مصمم هولندي',
    'أسبوع الموضة باريس',
    'أسبوع الموضة ميلانو',
    'أسبوع الموضة لندن',
    'أسبوع الموضة نيويورك',
    'أسبوع الموضة دبي',
    'أسبوع الموضة أبوظبي',
    'أسبوع الموضة الدوحة',
    'أسبوع الموضة الرياض',
  ],
  fr: [
    'prêt-à-porter',
    'prêt à porter',
    'printemps été 2026',
    'automne hiver 2026',
    'tenue Dubaï',
    'style Dubaï',
    'mode EAU',
    'tenue patrimoine EAU',
    'style khaleeji',
    'mode khaleeji',
    'mode modeste',
    'mode culturelle',
    'mode émiratie',
    'créateurs émiratis',
    'code vestimentaire Abou Dabi',
    'code vestimentaire EAU',
    'code vestimentaire Arabie saoudite',
    'code vestimentaire Qatar',
    'code vestimentaire Doha',
    'set voyage',
    'tenue voyage',
    'set élégant',
    'tenue élégante',
    'chemise oversize',
    'pantalon palazzo',
    'mode Londres',
    'mode Paris',
    'mode Milan',
    'mode New York',
    'mode Abou Dabi',
    'mode Dubaï',
    'mode Al Ain',
    'mode Al Quaa',
    'mode Doha',
    'abaya haut de gamme',
    'plus belle abaya',
    'tendances abaya',
    'abaya toutes couleurs',
    'abaya coton',
    'abaya ouverte',
    'abaya fermée',
    'manchette abaya',
    'abaya A-line',
    'abaya large',
    'abaya droite',
    'nouvelle abaya',
    'nouvelle collection',
    'collection mode',
    'créateur néerlandais',
    'Semaine de la mode Paris',
    'Semaine de la mode Milan',
    'Semaine de la mode Londres',
    'Semaine de la mode New York',
    'Semaine de la mode Dubaï',
    'Semaine de la mode Abou Dabi',
    'Semaine de la mode Doha',
  ],
  it: [
    'prêt-à-porter',
    'pronto moda',
    'primavera estate 2026',
    'autunno inverno 2026',
    'outfit Dubai',
    'stile Dubai',
    'moda EAU',
    'stile khaleeji',
    'moda khaleeji',
    'moda modesta',
    'moda culturale',
    'moda emiratina',
    'designer emiratini',
    'dress code Abu Dhabi',
    'dress code EAU',
    'dress code Qatar',
    'dress code Doha',
    'set da viaggio',
    'outfit da viaggio',
    'set elegante',
    'camicia oversize',
    'pantaloni palazzo',
    'moda Londra',
    'moda Parigi',
    'moda Milano',
    'moda New York',
    'moda Abu Dhabi',
    'moda Dubai',
    'moda Al Ain',
    'moda Al Quaa',
    'moda Doha',
    'abaya di alta gamma',
    'abaya più bella',
    'tendenze abaya',
    'abaya tutti i colori',
    'abaya cotone',
    'abaya aperta',
    'abaya chiusa',
    'polsino abaya',
    'abaya A-line',
    'abaya ampia',
    'abaya dritta',
    'nuova abaya',
    'nuova collezione',
    'collezione moda',
    'designer olandese',
    'Settimana della moda Parigi',
    'Settimana della moda Milano',
    'Settimana della moda Londra',
    'Settimana della moda New York',
    'Settimana della moda Dubai',
    'Settimana della moda Abu Dhabi',
    'Settimana della moda Doha',
  ],
  es: [
    'prêt-à-porter',
    'prêt a porter',
    'primavera verano 2026',
    'otoño invierno 2026',
    'outfit Dubái',
    'estilo Dubái',
    'moda EAU',
    'estilo khaleeji',
    'moda khaleeji',
    'moda modesta',
    'moda cultural',
    'moda emiratí',
    'diseñadores emiratíes',
    'código de vestimenta Abu Dabi',
    'código de vestimenta EAU',
    'código de vestimenta Catar',
    'código de vestimenta Doha',
    'set de viaje',
    'outfit de viaje',
    'set elegante',
    'camisa oversize',
    'pantalones palazzo',
    'moda Londres',
    'moda París',
    'moda Milán',
    'moda Nueva York',
    'moda Abu Dabi',
    'moda Dubái',
    'moda Al Ain',
    'moda Al Quaa',
    'moda Doha',
    'abaya de alta gama',
    'abaya más bella',
    'tendencias abaya',
    'abaya todos los colores',
    'abaya algodón',
    'abaya abierta',
    'abaya cerrada',
    'puño abaya',
    'abaya A-line',
    'abaya ancha',
    'abaya recta',
    'abaya nueva',
    'nueva colección',
    'colección moda',
    'diseñador holandés',
    'Semana de la moda París',
    'Semana de la moda Milán',
    'Semana de la moda Londres',
    'Semana de la moda Nueva York',
    'Semana de la moda Dubái',
    'Semana de la moda Abu Dabi',
    'Semana de la moda Doha',
  ],
  de: [
    'Ready-to-Wear',
    'Frühjahr Sommer 2026',
    'Herbst Winter 2026',
    'Dubai Outfit',
    'Dubai Style',
    'VAE Mode',
    'Khaleeji Stil',
    'Khaleeji Mode',
    'bescheidene Mode',
    'kulturelle Mode',
    'emiratische Mode',
    'emiratische Designer',
    'Kleiderordnung Abu Dhabi',
    'Kleiderordnung VAE',
    'Kleiderordnung Katar',
    'Kleiderordnung Doha',
    'Reise-Set',
    'Reise-Outfit',
    'elegantes Set',
    'Oversize-Hemd',
    'Palazzo-Hose',
    'Mode London',
    'Mode Paris',
    'Mode Mailand',
    'Mode New York',
    'Mode Abu Dhabi',
    'Mode Dubai',
    'Mode Al Ain',
    'Mode Al Quaa',
    'Mode Doha',
    'High-End-Abaya',
    'schönste Abaya',
    'Abaya-Trends',
    'Abaya alle Farben',
    'Baumwoll-Abaya',
    'offene Abaya',
    'geschlossene Abaya',
    'Abaya-Manschette',
    'A-Linien-Abaya',
    'weite Abaya',
    'gerade Abaya',
    'neue Abaya',
    'neue Kollektion',
    'Modekollektion',
    'niederländischer Designer',
    'Paris Fashion Week',
    'Mailand Fashion Week',
    'London Fashion Week',
    'New York Fashion Week',
    'Dubai Fashion Week',
    'Abu Dhabi Fashion Week',
    'Doha Fashion Week',
  ],
  nl: [
    'ready-to-wear',
    'lente zomer 2026',
    'herfst winter 2026',
    'Dubai outfit',
    'Dubai stijl',
    'VAE mode',
    'khaleeji stijl',
    'khaleeji mode',
    'bescheiden mode',
    'culturele mode',
    'Emiratische mode',
    'Emiratische designers',
    'dresscode Abu Dhabi',
    'dresscode VAE',
    'dresscode Qatar',
    'dresscode Doha',
    'reisset',
    'reiskleding',
    'elegant set',
    'oversized overhemd',
    'palazzo broek',
    'mode Londen',
    'mode Parijs',
    'mode Milaan',
    'mode New York',
    'mode Abu Dhabi',
    'mode Dubai',
    'mode Al Ain',
    'mode Al Quaa',
    'mode Doha',
    'high end abaya',
    'mooiste abaya',
    'abaya trends',
    'abaya alle kleuren',
    'katoenen abaya',
    'open abaya',
    'gesloten abaya',
    'abaya manchet',
    'A-lijn abaya',
    'wijde abaya',
    'rechte abaya',
    'nieuwe abaya',
    'nieuwe collectie',
    'modecollectie',
    'Nederlandse designer',
    'Amsterdam Fashion Week',
    'Paris Fashion Week',
    'Milaan Fashion Week',
    'Londen Fashion Week',
    'New York Fashion Week',
    'Dubai Fashion Week',
    'Abu Dhabi Fashion Week',
    'Doha Fashion Week',
  ],
  pt: [
    'prêt-à-porter',
    'primavera verão 2026',
    'outono inverno 2026',
    'outfit Dubai',
    'estilo Dubai',
    'moda EAU',
    'estilo khaleeji',
    'moda khaleeji',
    'moda modesta',
    'moda cultural',
    'moda emirati',
    'designers emiratis',
    'código de vestuário Abu Dhabi',
    'código de vestuário EAU',
    'código de vestuário Catar',
    'código de vestuário Doha',
    'set de viagem',
    'outfit de viagem',
    'set elegante',
    'camisa oversize',
    'calças palazzo',
    'moda Londres',
    'moda Paris',
    'moda Milão',
    'moda Nova Iorque',
    'moda Abu Dhabi',
    'moda Dubai',
    'moda Al Ain',
    'moda Al Quaa',
    'moda Doha',
    'abaya de alta gama',
    'abaya mais bela',
    'tendências abaya',
    'abaya todas as cores',
    'abaya algodão',
    'abaya aberta',
    'abaya fechada',
    'punho abaya',
    'abaya A-line',
    'abaya larga',
    'abaya reta',
    'abaya nova',
    'nova coleção',
    'coleção moda',
    'designer holandês',
    'Semana de moda Paris',
    'Semana de moda Milão',
    'Semana de moda Londres',
    'Semana de moda Nova Iorque',
    'Semana de moda Dubai',
    'Semana de moda Abu Dhabi',
    'Semana de moda Doha',
  ],
  ru: [
    'женская одежда',
    'готовая одежда',
    'весна-лето 2026',
    'осень-зима 2026',
    'образ Дубай',
    'стиль Дубай',
    'мода ОАЭ',
    'стиль хали́джи',
    'мода хали́джи',
    'скромная мода',
    'культурная мода',
    'эмиратская мода',
    'дресс-код Абу-Даби',
    'дресс-код ОАЭ',
    'дресс-код Катар',
    'дресс-код Доха',
    'travel set',
    'комплект для путешествий',
    'оверсайз рубашка',
    'брюки palazzo',
    'мода Лондон',
    'мода Париж',
    'мода Милан',
    'мода Нью-Йорк',
    'мода Абу-Даби',
    'мода Дубай',
    'мода Эль-Айн',
    'мода Эль-Куа',
    'мода Доха',
    'люксовая абайя',
    'самая красивая абайя',
    'тренды абай',
    'абайя всех цветов',
    'хлопковая абайя',
    'открытая абайя',
    'закрытая абайя',
    'манжет абайи',
    'абайя A-line',
    'широкая абайя',
    'прямая абайя',
    'новая абайя',
    'новая коллекция',
    'модная коллекция',
    'голландский дизайнер',
    'Неделя моды Париж',
    'Неделя моды Милан',
    'Неделя моды Лондон',
    'Неделя моды Нью-Йорк',
    'Неделя моды Дубай',
    'Неделя моды Абу-Даби',
    'Неделя моды Доха',
  ],
  zh: [
    '女装',
    '成衣',
    '2026春夏',
    '2026秋冬',
    '迪拜穿搭',
    '迪拜风格',
    '阿联酋时尚',
    '阿联酋传承穿搭',
    '海湾风格',
    '海湾时尚',
    '端庄时尚',
    '文化时尚',
    '阿联酋设计师',
    '阿布扎比着装规范',
    '阿联酋着装规范',
    '卡塔尔着装规范',
    '多哈着装规范',
    '旅行套装',
    '旅行穿搭',
    '优雅套装',
    '宽松衬衫',
    '阔腿长裤',
    '伦敦时尚',
    '巴黎时尚',
    '米兰时尚',
    '纽约时尚',
    '阿布扎比时尚',
    '迪拜时尚',
    '艾因时尚',
    '阿尔奎阿时尚',
    '多哈时尚',
    '高端长袍',
    '最美长袍',
    '长袍趋势',
    '全色长袍',
    '棉质长袍',
    '开襟长袍',
    '闭合长袍',
    '长袍袖口',
    'A字长袍',
    '宽版长袍',
    '直筒长袍',
    '新款长袍',
    '新系列',
    '时尚系列',
    '荷兰设计师',
    '巴黎时装周',
    '米兰时装周',
    '伦敦时装周',
    '纽约时装周',
    '迪拜时装周',
    '阿布扎比时装周',
    '多哈时装周',
  ],
  id: [],
  ms: [],
}

export const SCHEMA_KEYWORD_EXPANSION_EN: readonly string[] = dedupe([
  ...SEASON_AND_RTW_EN,
  ...STYLE_AND_HERITAGE_EN,
  ...DRESS_CODE_EN,
  ...SET_AND_TRAVEL_EN,
  ...SET_PRODUCT_EN,
  ...CITY_FASHION_EN,
  ...PLACE_TARGET_EN,
  ...ABAYA_DISCOVERY_EN,
  ...COLLECTION_AND_DESIGNER_EN,
  ...FASHION_WEEKS_EN,
  ...LONDON_HEAVY_EN,
  ...LONDON_BRAND_DISCOVERY_EN,
])

/** Site-wide + PDP schema keyword expansion — all locales. */
export function getGlobalSchemaKeywordExpansion(locale: AppLocale = 'en'): string[] {
  const localized = LOCALIZED_EXPANSION[locale] ?? []
  const regionCity = REGION_CITY_FASHION_LOCALIZED[locale] ?? []
  const londonHeavy = LONDON_HEAVY_LOCALIZED[locale] ?? []
  const londonBrand = LONDON_BRAND_DISCOVERY_LOCALIZED[locale] ?? []
  if (locale === 'en') {
    return [...SCHEMA_KEYWORD_EXPANSION_EN]
  }
  if (locale === 'id' || locale === 'ms') {
    return dedupe([...SCHEMA_KEYWORD_EXPANSION_EN, ...localized, ...regionCity, ...londonHeavy, ...londonBrand])
  }
  return dedupe([...SCHEMA_KEYWORD_EXPANSION_EN, ...localized, ...regionCity, ...londonHeavy, ...londonBrand])
}

/** Soho Set PDP — product-specific discovery on top of global expansion. */
export function getSohoSetSchemaKeywordExpansion(locale: AppLocale = 'en'): string[] {
  const sohoEn = dedupe([
    ...SET_AND_TRAVEL_EN,
    ...SET_PRODUCT_EN,
    'Soho travel set',
    'Soho elegant set',
    'Soho summer outfit',
    'Soho black outfit',
    'Soho europe outfit',
    'Soho best seller',
    'Bint Saeed travel set',
    'Bint Saeed elegant set',
    'crepe shirt and palazzo set',
    'Al Talli travel set',
    'Knotted Line set',
    'modest travel set UAE',
    'Dubai travel outfit',
    'UAE travel outfit',
    'Doha travel outfit',
    'Abu Dhabi travel outfit',
    'Al Ain travel outfit',
    'GCC coordinate set',
  ])
  const sohoLocalized: Partial<Record<AppLocale, readonly string[]>> = {
    ar: [
      'طقم سفر Soho',
      'طقم أنيق Soho',
      'إطلالة سفر دبي',
      'إطلالة سفر أبوظبي',
      'إطلالة سفر الدوحة',
      'طقم منسّق خليجي',
    ],
    fr: ['set voyage Soho', 'tenue voyage Dubaï', 'set coordonné EAU'],
    it: ['set viaggio Soho', 'outfit viaggio Dubai'],
    es: ['set viaje Soho', 'outfit viaje Dubái'],
    de: ['Soho Reise-Set', 'Reise-Outfit Dubai'],
    nl: ['Soho reisset', 'reiskleding Dubai'],
    pt: ['set viagem Soho', 'outfit viagem Dubai'],
    ru: ['комплект Soho для путешествий'],
    zh: ['Soho 旅行套装', '迪拜旅行穿搭'],
  }
  return dedupe([
    ...getGlobalSchemaKeywordExpansion(locale),
    ...sohoEn,
    ...(sohoLocalized[locale] ?? []),
  ])
}
