import type { Accessory } from '@/data/accessories'
import type { AppLocale } from '@/lib/i18n/routing'

const NECKLACE_AUDIENCE: Record<AppLocale, string> = {
  en: 'Women worldwide who buy and collect natural stone jewellery — gemstone necklace enthusiasts, luxury hand-strung bead jewellery buyers, natural gemstone jewellery collectors, coordinated Al Ain Rosette jewellery set clients, modest fashion jewellery shoppers, UAE and GCC natural stone jewellery buyers, expatriates and international gift buyers, women pairing natural stone necklaces with Bint Saeed Signature Strands and Al Ain earrings, jewellery lovers who value handcrafted Abu Dhabi designer gemstone pieces, and buyers of malachite, onyx, rose quartz, tiger eye, lapis lazuli and sunstone necklace jewellery.',
  ar: 'النساء حول العالم اللواتي يشترين ويجمعن مجوهرات الأحجار الطبيعية — عاشقات قلادات الأحجار الكريمة، مشتريات المجوهرات الفاخرة المرصّعة يدوياً، جامعات مجوهرات الأحجار الطبيعية، عميلات مجموعات القوع روزيت المتناسقة، متسوقات مجوهرات الأزياء المحتشمة، مشتريات مجوهرات الأحجار الطبيعية في الإمارات والخليج، المغتربات ومشتريات الهدايا الدولية، النساء اللواتي يزاوجن قلادات الأحجار الطبيعية مع خيوط Bint Saeed وأقراط القوع، محبات المجوهرات المصنوعة يدوياً في أبوظبي، ومشتريات قلادات الملاكيت والأونكس والكوارتز الوردي وعين النمر واللازورد والشمس الحجر.',
  fr: "Femmes du monde entier qui achètent et collectionnent des bijoux en pierres naturelles — passionnées de colliers en pierres précieuses, acheteuses de colliers de perles de luxe enfilés à la main, collectionneuses de bijoux en gemmes naturelles, clientes de parures Al Ain Rosette coordonnées, acheteuses de bijoux mode modeste, clientes de bijoux en pierres naturelles aux EAU et dans le Golfe, expatriées et acheteuses de cadeaux internationales, femmes associant colliers en pierres naturelles aux Signature Strands et boucles Al Ain, amatrices de bijoux artisanaux en pierres à Abu Dhabi, et acheteuses de colliers malachite, onyx, quartz rose, œil de tigre, lapis lazuli et pierre de soleil.",
  it: 'Donne in tutto il mondo che acquistano e collezionano gioielli in pietre naturali — appassionate di collane in gemme, acquirenti di collane di perle di lusso infilate a mano, collezioniste di gioielli in pietre naturali, clienti di set Al Ain Rosette coordinati, acquirenti di gioielli moda modesta, clienti di gioielli in pietre naturali negli EAU e nel Golfo, espatriate e acquirenti di regali internazionali, donne che abbinano collane in pietre naturali a Signature Strands e orecchini Al Ain, amanti di gioielli artigianali in pietre ad Abu Dhabi, e acquirenti di collane in malachite, onice, quarzo rosa, occhio di tigre, lapislazzuli e sunstone.',
  es: 'Mujeres en todo el mundo que compran y coleccionan joyería de piedra natural — entusiastas de collares de gemas, compradoras de collares de cuentas de lujo ensartados a mano, coleccionistas de joyería de gemas naturales, clientas de sets Al Ain Rosette coordinados, compradoras de joyería de moda modesta, clientas de joyería de piedra natural en EAU y el Golfo, expatriadas y compradoras de regalos internacionales, mujeres que combinan collares de piedra natural con Signature Strands y pendientes Al Ain, amantes de joyería artesanal de gemas en Abu Dhabi, y compradoras de collares de malaquita, ónix, cuarzo rosa, ojo de tigre, lapislázuli y piedra solar.',
  ru: 'Женщины по всему миру, которые покупают и коллекционируют украшения из натуральных камней — ценительницы ожерелий из драгоценных камней, покупательницы роскошных ожерелий из бусин ручной работы, коллекционерки украшений из натуральных камней, клиентки координированных наборов Al Ain Rosette, покупательницы украшений скромной моды, клиентки украшений из натуральных камней в ОАЭ и странах Залива, экспатриантки и международные покупательницы подарков, женщины, сочетающие ожерелья из натуральных камней с Signature Strands и серьгами Al Ain, любительницы ювелирных изделий ручной работы из камней в Абу-Даби, и покупательницы ожерелий из малахита, оникса, розового кварца, тигрового глаза, лазурита и солнечного камня.',
  zh: '全球购买和收藏天然石珠宝的女性——宝石项链爱好者、奢华手工串珠项链买家、天然宝石珠宝收藏家、Al Ain Rosette协调珠宝套装客户、端庄时尚珠宝购物者、阿联酋与海湾天然石珠宝买家、侨居女性与国际礼品购买者、将天然石项链与Bint Saeed Signature Strands及Al Ain耳环搭配的女性、珍视阿布扎比手工宝石珠宝的爱好者，以及孔雀石、玛瑙、玫瑰石英、虎眼石、青金石与太阳石项链购买者。',
  de: 'Frauen weltweit, die Natursteinschmuck kaufen und sammeln — Liebhaberinnen von Edelsteinketten, Käuferinnen luxuriöser handgefädelter Perlenketten, Sammlerinnen von Natursteinschmuck, Kundinnen koordinierter Al-Ain-Rosette-Schmucksets, Käuferinnen bescheidener Mode-Schmuck, Natursteinschmuck-Kundinnen in den VAE und im Golf, Expatriates und internationale Geschenkkäuferinnen, Frauen, die Natursteinketten mit Signature Strands und Al-Ain-Ohrringen kombinieren, Liebhaberinnen handgefertigten Edelsteinschmucks aus Abu Dhabi, und Käuferinnen von Malachit-, Onyx-, Rosenquarz-, Tigerauge-, Lapislazuli- und Sonnenstein-Ketten.',
  nl: 'Vrouwen wereldwijd die natuursteen sieraden kopen en verzamelen — liefhebsters van edelsteen kettingen, kopers van luxe handgeregen kralenkettingen, verzamelaars van natuursteen sieraden, klanten van gecoördineerde Al Ain Rosette sets, kopers van bescheiden mode sieraden, natuursteen sieraden kopers in VAE en Golf, expats en internationale cadeaukopers, vrouwen die natuursteen kettingen combineren met Signature Strands en Al Ain oorbellen, liefhebbers van handgemaakt edelsteen sieraden uit Abu Dhabi, en kopers van malachiet-, onyx-, roze kwarts-, tijgeroog-, lapis lazuli- en zonnesteen kettingen.',
  pt: 'Mulheres em todo o mundo que compram e colecionam joias de pedra natural — entusiastas de colares de gemas, compradoras de colares de contas de luxo enfiadas à mão, colecionadoras de joias de pedras naturais, clientes de sets Al Ain Rosette coordenados, compradoras de joias de moda modesta, clientes de joias de pedra natural nos EAU e no Golfo, expatriadas e compradoras de presentes internacionais, mulheres que combinam colares de pedra natural com Signature Strands e brincos Al Ain, amantes de joias artesanais de gemas em Abu Dhabi, e compradoras de colares de malaquita, ônix, quartzo rosa, olho de tigre, lápis-lazúli e pedra-sol.',
  id: 'Perempuan di seluruh dunia yang membeli dan mengoleksi perhiasan batu alami — penggemar kalung batu permata, pembeli kalung manik mewah yang dirangkai tangan, kolektor perhiasan batu alami, klien set perhiasan Al Ain Rosette yang selaras, pembeli perhiasan mode modest, pembeli perhiasan batu alami di UEA dan GCC, ekspatriat dan pembeli hadiah internasional, perempuan yang memadukan kalung batu alami dengan Signature Strands dan anting Al Ain, pecinta perhiasan batu buatan tangan Abu Dhabi, dan pembeli kalung malachite, onyx, rose quartz, tiger eye, lapis lazuli, dan sunstone.',
  ms: 'Wanita di seluruh dunia yang membeli dan mengumpul barang kemas batu semula jadi — peminat kalung batu permata, pembeli kalung manik mewah yang dirangkai tangan, pengumpul barang kemas batu semula jadi, pelanggan set barang kemas Al Ain Rosette yang selaras, pembeli barang kemas fesyen modest, pembeli barang kemas batu semula jadi di UAE dan GCC, ekspatriat dan pembeli hadiah antarabangsa, wanita yang memadankan kalung batu semula jadi dengan Signature Strands dan anting pin Al Ain, pencinta barang kemas batu buatan tangan Abu Dhabi, dan pembeli kalung malachite, onyx, rose quartz, tiger eye, lapis lazuli, dan sunstone.',
}

const EARRING_AUDIENCE: Record<AppLocale, string> = {
  en: 'Women worldwide who buy and collect natural stone jewellery — designer earring enthusiasts, luxury gemstone jewellery buyers, coordinated Al Ain Rosette jewellery set clients, modest fashion earring shoppers, UAE and GCC natural stone jewellery buyers, expatriates and international gift buyers, women styling natural stone earrings with Bint Saeed necklaces and Signature Strands, jewellery collectors who value handcrafted Abu Dhabi designer pieces, and buyers seeking pearl, geometric and gold hoop earrings to complete natural stone jewellery looks.',
  ar: 'النساء حول العالم اللواتي يشترين ويجمعن مجوهرات الأحجار الطبيعية — عاشقات الأقراط المصممة، مشتريات مجوهرات الأحجار الكريمة الفاخرة، عميلات مجموعات القوع روزيت المتناسقة، متسوقات أقراط الأزياء المحتشمة، مشتريات مجوهرات الأحجار الطبيعية في الإمارات والخليج، المغتربات ومشتريات الهدايا الدولية، النساء اللواتي يزاوجن أقراط الأحجار الطبيعية مع قلادات Bint Saeed وخيوط التوقيع، جامعات المجوهرات التي تقدّر القطع المصنوعة يدوياً في أبوظبي، ومشتريات أقراط اللؤلؤ والهندسية والحلقية الذهبية لإكمال إطلالات مجوهرات الأحجار الطبيعية.',
  fr: "Femmes du monde entier qui achètent et collectionnent des bijoux en pierres naturelles — passionnées de boucles d'oreilles designer, acheteuses de bijoux en gemmes de luxe, clientes de parures Al Ain Rosette coordonnées, acheteuses de boucles mode modeste, clientes de bijoux en pierres naturelles aux EAU et dans le Golfe, expatriées et acheteuses de cadeaux internationales, femmes stylisant boucles en pierres naturelles avec colliers Bint Saeed et Signature Strands, collectionneuses de bijoux artisanaux à Abu Dhabi, et acheteuses de boucles perles, géométriques et créoles dorées pour compléter des looks en pierres naturelles.",
  it: 'Donne in tutto il mondo che acquistano e collezionano gioielli in pietre naturali — appassionate di orecchini designer, acquirenti di gioielli in gemme di lusso, clienti di set Al Ain Rosette coordinati, acquirenti di orecchini moda modesta, clienti di gioielli in pietre naturali negli EAU e nel Golfo, espatriate e acquirenti di regali internazionali, donne che abbinano orecchini in pietre naturali a collane Bint Saeed e Signature Strands, collezioniste di gioielli artigianali ad Abu Dhabi, e acquirenti di orecchini perla, geometrici e cerchi dorati per completare look in pietre naturali.',
  es: 'Mujeres en todo el mundo que compran y coleccionan joyería de piedra natural — entusiastas de pendientes de diseñador, compradoras de joyería de gemas de lujo, clientas de sets Al Ain Rosette coordinados, compradoras de pendientes de moda modesta, clientas de joyería de piedra natural en EAU y el Golfo, expatriadas y compradoras de regalos internacionales, mujeres que combinan pendientes de piedra natural con collares Bint Saeed y Signature Strands, coleccionistas de joyería artesanal en Abu Dhabi, y compradoras de pendientes de perla, geométricos y aros dorados para completar looks de piedra natural.',
  ru: 'Женщины по всему миру, которые покупают и коллекционируют украшения из натуральных камней — ценительницы дизайнерских серег, покупательницы люксовых украшений из драгоценных камней, клиентки координированных наборов Al Ain Rosette, покупательницы серег скромной моды, клиентки украшений из натуральных камней в ОАЭ и странах Залива, экспатриантки и международные покупательницы подарков, женщины, сочетающие серьги из натуральных камней с ожерельями Bint Saeed и Signature Strands, коллекционерки ювелирных изделий ручной работы из Абу-Даби, и покупательницы жемчужных, геометрических и золотых серег-колец для завершения образов из натуральных камней.',
  zh: '全球购买和收藏天然石珠宝的女性——设计师耳环爱好者、奢华宝石珠宝买家、Al Ain Rosette协调珠宝套装客户、端庄时尚耳环购物者、阿联酋与海湾天然石珠宝买家、侨居女性与国际礼品购买者、将天然石耳环与Bint Saeed项链及Signature Strands搭配的女性、珍视阿布扎比手工珠宝的收藏家，以及购买珍珠、几何与金圈耳环以完善天然石珠宝造型的买家。',
  de: 'Frauen weltweit, die Natursteinschmuck kaufen und sammeln — Liebhaberinnen von Designer-Ohrringen, Käuferinnen luxuriösen Edelsteinschmucks, Kundinnen koordinierter Al-Ain-Rosette-Sets, Käuferinnen bescheidener Mode-Ohrringe, Natursteinschmuck-Kundinnen in den VAE und im Golf, Expatriates und internationale Geschenkkäuferinnen, Frauen, die Naturstein-Ohrringe mit Bint-Saeed-Ketten und Signature Strands stylen, Sammlerinnen handgefertigten Schmucks aus Abu Dhabi, und Käuferinnen von Perlen-, geometrischen und Gold-Creolen-Ohrringen für Naturstein-Looks.',
  nl: 'Vrouwen wereldwijd die natuursteen sieraden kopen en verzamelen — liefhebsters van designer oorbellen, kopers van luxe edelsteen sieraden, klanten van gecoördineerde Al Ain Rosette sets, kopers van bescheiden mode oorbellen, natuursteen sieraden kopers in VAE en Golf, expats en internationale cadeaukopers, vrouwen die natuursteen oorbellen stylen met Bint Saeed kettingen en Signature Strands, verzamelaars van handgemaakt sieraden uit Abu Dhabi, en kopers van parel-, geometrische en gouden hoepel oorbellen voor natuursteen looks.',
  pt: 'Mulheres em todo o mundo que compram e colecionam joias de pedra natural — entusiastas de brincos designer, compradoras de joias de gemas de luxo, clientes de sets Al Ain Rosette coordenados, compradoras de brincos de moda modesta, clientes de joias de pedra natural nos EAU e no Golfo, expatriadas e compradoras de presentes internacionais, mulheres que combinam brincos de pedra natural com colares Bint Saeed e Signature Strands, colecionadoras de joias artesanais em Abu Dhabi, e compradoras de brincos de pérola, geométricos e argolas douradas para completar looks de pedra natural.',
  id: 'Perempuan di seluruh dunia yang membeli dan mengoleksi perhiasan batu alami — penggemar anting desainer, pembeli perhiasan batu permata mewah, klien set perhiasan Al Ain Rosette yang selaras, pembeli anting mode modest, pembeli perhiasan batu alami di UEA dan GCC, ekspatriat dan pembeli hadiah internasional, perempuan yang menata anting batu alami dengan kalung Bint Saeed dan Signature Strands, kolektor perhiasan buatan tangan Abu Dhabi, dan pembeli anting mutiara, geometris, dan hoop emas untuk melengkapi tampilan perhiasan batu alami.',
  ms: 'Wanita di seluruh dunia yang membeli dan mengumpul barang kemas batu semula jadi — peminat anting pereka, pembeli barang kemas batu permata mewah, pelanggan set barang kemas Al Ain Rosette yang selaras, pembeli anting fesyen modest, pembeli barang kemas batu semula jadi di UAE dan GCC, ekspatriat dan pembeli hadiah antarabangsa, wanita yang menggayakan anting batu semula jadi dengan kalung Bint Saeed dan Signature Strands, pengumpul barang kemas buatan tangan Abu Dhabi, dan pembeli anting mutiara, geometri, dan hoop emas untuk melengkapkan gaya barang kemas batu semula jadi.',
}

const NECKLACE_GEMSTONE_LABELS: Record<string, string> = {
  malachite: 'Malachite',
  'lapis-lazuli': 'Lapis Lazuli',
  'rose-quartz': 'Rose Quartz',
  'tiger-eye': 'Tiger Eye',
  onyx: 'Onyx',
  sunstone: 'Sunstone',
}

export function getNecklaceEarringSchemaAudience(
  category: Extract<Accessory['category'], 'necklaces' | 'earrings'>,
  locale: AppLocale = 'en',
): string {
  const pack = category === 'necklaces' ? NECKLACE_AUDIENCE : EARRING_AUDIENCE
  return pack[locale] ?? pack.en
}

export function getNecklaceGemstoneLabel(accessoryId: string): string | undefined {
  if (!accessoryId.startsWith('al-ain-oasis-necklace-')) return undefined
  const variant = accessoryId.slice('al-ain-oasis-necklace-'.length)
  return NECKLACE_GEMSTONE_LABELS[variant] ?? variant.replace(/-/g, ' ')
}
